---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/1/12 0012 12:57
---
BaseProperty = class()

function BaseProperty:ctor(config)
    self.config = config
    self:onCreate()
end

function BaseProperty:onCreate()

end

function BaseProperty:onPlayerGet(player)

end

function BaseProperty:onPlayerEquip(player)

end

function BaseProperty:onPlayerUnload(player)

end

function BaseProperty:onPlayerUsed(player, target, damage)

end

return BaseProperty