---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/4/8 0008 10:34
---
local Sender
local CommonSender

PacketSender = {}

function PacketSender:init()
    Sender = ServerNetwork.Instance():getLuaSender()
    CommonSender = ServerNetwork.Instance():getLuaCommonSender()
end

function PacketSender:getSender()
    return Sender
end

function PacketSender:getCommonSender()
    return CommonSender
end

function PacketSender:sendPlayerDBReady(rakssid)
    Sender:sendPlayerDBDataReady(rakssid)
end

function PacketSender:sendInitMoney(rakssid, diamondBlues, diamondGolds, golds)
    diamondBlues = diamondBlues or 0
    diamondGolds = diamondGolds or 0
    golds = golds or 0
    Sender:sendInitMoney(rakssid, diamondBlues, diamondGolds, golds)
end

function PacketSender:sendServerCommonData(rakssid, name, key, data)
    CommonSender:sendServerCommonData(rakssid, name, key, data or "")
end

function PacketSender:broadCastServerCommonData(name, key, data)
    CommonSender:broadCastServerCommonData(name, key, data or "")
end

function PacketSender:sendLuaCommonData(rakssid, key, data)
    CommonSender:sendServerCommonData(rakssid, "Lua", key, data or "")
end

function PacketSender:broadCastLuaCommonData(key, data)
    CommonSender:broadCastServerCommonData("Lua", key, data or "")
end

function PacketSender:sendServerCommonDataToTrackingPlayers(entityId, name, key, data)
    CommonSender:sendServerCommonDataToTrackingPlayers(entityId, name, key, data or "")
end

function PacketSender:sendLuaCommonDataToTrackingPlayers(entityId, key, data)
    CommonSender:sendServerCommonDataToTrackingPlayers(entityId, "Lua", key, data or "")
end

function PacketSender:syncEntityPlayerInfo(userId, key, value, rakssid)
    local data = DataBuilder.new()
                            :addParam("userId", userId)
                            :addParam(key, value)
                            :getData()
    if rakssid then
        PacketSender:sendServerCommonData(rakssid, "SyncEntityPlayerInfo", "", data)
    else
        PacketSender:broadCastServerCommonData("SyncEntityPlayerInfo", "", data)
    end
end

function PacketSender:syncEntityActorNpcInfo(entityId, key, value, rakssid)
    local data = DataBuilder.new()
                            :addParam("entityId", entityId)
                            :addParam(key, value)
                            :getData()
    if rakssid then
        PacketSender:sendServerCommonData(rakssid, "SyncEntityActorNpcInfo", "", data)
    else
        PacketSender:broadCastServerCommonData("SyncEntityActorNpcInfo", "", data)
    end
end

function PacketSender:sendDispatchInfo(rakssid, dispatchInfo)
    local data = DataBuilder.new():fromTable(dispatchInfo):getData()
    PacketSender:sendServerCommonData(rakssid, "DispatchInfo", "", data)
end

function PacketSender:sendIntoFollowMode(rakssid, followerId)
    PacketSender:sendLuaCommonData(rakssid, "IntoFollowMode", followerId)
end

function PacketSender:sendWatcherInfo(rakssid, name)
    PacketSender:sendLuaCommonData(rakssid, "WatcherInfo", name)
end

function PacketSender:sendFollowerInfo(rakssid, name)
    PacketSender:sendLuaCommonData(rakssid, "FollowerInfo", name)
end

function PacketSender:sendDataReport(rakssid, main, child)
    local reportData = {
        mainEvent = main or "",
        childEvent = child or "",
    }
    local data = DataBuilder.new():fromTable(reportData):getData()
    PacketSender:sendServerCommonData(rakssid, "DataReport", "", data)
end

return PacketSender