---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/5/10 0010 15:33
---
local ServerConfig
local MaxRunTime = 86400
local RunningTime = os.time()
local IsCloseServer = false
local CloseServerTime = 0

GameServer = {}

function GameServer:onTick()
    self:checkRunningTime()
    self:tryCloseServer()
end

function GameServer:setServerConfig(config)
    ServerConfig = config
end

function GameServer:getServerConfig()
    return ServerConfig
end

function GameServer:setMaxRunTime(maxRunTime)
    MaxRunTime = maxRunTime
end

---The server runs for more than a day and does not let the player enter the game.
function GameServer:checkRunningTime()
    local time = os.time()
    if time - RunningTime >= MaxRunTime then
        RunningTime = time
        HostApi.sendStartGame(PlayerManager:getPlayerCount())
    end
end

function GameServer:isCloseServer()
    return IsCloseServer
end

function GameServer:closeServer()
    if IsCloseServer then
        return
    end
    GameAnalytics.RetryTimes = 0
    local players = PlayerManager:getPlayers()
    for _, player in pairs(players) do
        ReportManager:onPlayerLogout(player)
    end
    DBManager:saveAllDataCache()
    IsCloseServer = true
    CloseServerTime = os.time()
end

function GameServer:tryCloseServer()
    if not IsCloseServer then
        return
    end
    if os.time() - CloseServerTime >= 5 then
        HostApi.stopServer()
    end
end

function GameServer:getRoomManager()
    return Server.Instance():getLuaRoomManager()
end

function GameServer:setInitPos(initPos)
    Server.Instance():setInitPos(initPos)
end

function GameServer:isPrivateParty()
    if ServerConfig == nil then
        return false
    end
    return ServerConfig.isPrivateParty
end

return GameServer