---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/6/25 14:49
---
AIListener = {}

function AIListener:init()
    CheckStateChangeCondition1Event.registerCallBack(self.onCheckStateChangeCondition1)
    CheckStateChangeCondition2Event.registerCallBack(self.onCheckStateChangeCondition2)
    CheckStateChangeCondition3Event.registerCallBack(self.onCheckStateChangeCondition3)
    CheckStateChangeCondition4Event.registerCallBack(self.onCheckStateChangeCondition4)

    --FindTargetEvent.registerCallBack(self.onFindTarget)
    PatrolStateEvent.registerCallBack(self.onPatrolState)
    ChaseStateEvent.registerCallBack(self.onChaseState)
end

function AIListener.onPatrolState(entityId)
    --HostApi.log("AIListener.onPatrolState")

    local monster = MonsterManager:getMonster(entityId)
    if monster == nil then
        return
    end

    monster:onPatrolState()
end

function AIListener.onChaseState(entityId)
    --HostApi.log("AIListener.onChaseState")

    local monster = MonsterManager:getMonster(entityId)
    if monster == nil then
        return
    end

    monster:onChaseState()
end

function AIListener.onCheckStateChangeCondition1(entityId, monsterId)
    --local monster = MonsterManager:getMonster(entityId)
    --if monster == nil then
    --    return false
    --end

    --for _, player in pairs(PlayerManager:getPlayers()) do
    --    local distance = MathUtil:distanceSquare3d(monster:getPosition(), player:getPosition())
    --    if distance <= math.pow(monster.senseRange, 2) then
    --        HostApi.log("AIListener:onCheckStateChangeCondition1")
    --        return true
    --    end
    --end

    return false
end

function AIListener.onCheckStateChangeCondition2(entityId, monsterId)
    return false
end

function AIListener.onCheckStateChangeCondition3(entityId, monsterId)
    return false
end

function AIListener.onCheckStateChangeCondition4(entityId, monsterId)
    return false
end

function AIListener.onFindTarget(entityId)
    local monster = MonsterManager:getMonster(entityId)
    if monster == nil then
        --HostApi.log("AIListener:onFindTarget monster == nil " .. entityId)
        return true
    end

    --HostApi.log(string.format("AIListener:onFindTarget %d %f %f %f", monster.senseRange,
    --        monster:getPosition().x, monster:getPosition().y, monster:getPosition().z))

    return false
end

function AIListener:findClosestTarget(monster)
    --local result = -1
    --
    --local min_dis = monster.senseRange * monster.senseRange
    --for _, player in pairs(PlayerManager:getPlayers()) do
    --    local dis = MathUtil:distanceSquare3d(monster:getPosition(), player.entityPlayerMP:getPosition())
    --    if dis < min_dis then
    --        min_dis = dis
    --        result = 0
    --    end
    --end
    --
    --return result
end

return AIListener