---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wu.
--- DateTime: 2019/7/1 15:00
TitleListener = {}
function TitleListener:init()
    DesignationChangeEvent:registerCallBack(self.designationChange)
end

function TitleListener.designationChange(userId, data)
    local player = PlayerManager:getPlayerByUserId(userId)
    local titleId = DataBuilder.new():fromData(data):getNumberParam("titleId")
    local titleStatus = DataBuilder.new():fromData(data):getNumberParam("titleStatus")
    local config = TitleConfig:getTitleById(titleId)
    if not player == nil or not config then
        return
    end
    if titleStatus == GameTitle.TitleStatus.Has then
        GameTitle:useTitle(player, titleId)
    elseif titleStatus ==GameTitle.TitleStatus.Use then
        GameTitle:unloadTitle(player,titleId)
    end
end