---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/10/11 0011 20:58
---
BaseProcessor = class("BaseProcessor")

function BaseProcessor:processData(key, data)
    return data
end

return BaseProcessor

