---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/10/11 0011 21:00
---
local IJsonBuilderProcessor = class("IJsonBuilderProcessor", BaseProcessor)

function IJsonBuilderProcessor:processData(key, data)
    return json.decode(data)
end

return IJsonBuilderProcessor