---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/8/13 0013 15:00
---
GamePacketSender = {}

function GamePacketSender:sendPixelGunShow1v1(rakssid, isOpen)
    local params = { isOpen = isOpen }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendServerCommonData(rakssid, "PixelGunGameData", "Show1v1", data)
end

function GamePacketSender:sendPixelGun1v1Data(rakssid, isOpen, data)
    GamePacketSender:sendPixelGunShow1v1(rakssid, isOpen)
    if isOpen then
        PacketSender:sendServerCommonData(rakssid, "PixelGunGameData", "1v1Data", data)
    end
end

function GamePacketSender:sendPixelGunShowRevive(rakssid, isOpen)
    local params = { isOpen = isOpen }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendServerCommonData(rakssid, "PixelGunGameData", "ShowRevive", data)
end

function GamePacketSender:sendPixelGunReviveData(rakssid, isOpen, data)
    GamePacketSender:sendPixelGunShowRevive(rakssid, isOpen)
    if isOpen then
        PacketSender:sendServerCommonData(rakssid, "PixelGunGameData", "ReviveData", data)
    end
end

function GamePacketSender:sendPixelGunPersonGameData(rakssid, time, rank, kills)
    local params = {
        time = time,
        rank = rank,
        kills = kills
    }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendServerCommonData(rakssid, "ToolBarData", "PixelGunPersonData", data)
end

function GamePacketSender:sendPixelGun1v1GameData(rakssid, time, redKills, blueKills, selfTeam)
    local params = {
        time = time,
        redKills = redKills,
        blueKills = blueKills,
        selfTeam = selfTeam
    }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendServerCommonData(rakssid, "ToolBarData", "PixelGun1v1Data", data)
end

function GamePacketSender:sendPixelGunTeamGameData(rakssid, time, redKills, redCurPlayers, redMaxPlayers, blueKills, blueCurPlayers, blueMaxPlayers, selfTeam)
    local params = {
        time = time,
        redKills = redKills,
        redCurPlayers = redCurPlayers,
        redMaxPlayers = redMaxPlayers,
        blueKills = blueKills,
        blueCurPlayers = blueCurPlayers,
        blueMaxPlayers = blueMaxPlayers,
        selfTeam = selfTeam
    }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendServerCommonData(rakssid, "ToolBarData", "PixelGunTeamData", data)
end

function GamePacketSender:sendPixelGunShowGameResult(rakssid, isOpen)
    local params = { isOpen = isOpen }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendServerCommonData(rakssid, "PixelGunGameData", "ShowGameResult", data)
end

function GamePacketSender:sendPixelGunGameResultExtra(rakssid, canRevenge)
    local params = { canRevenge = canRevenge }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendServerCommonData(rakssid, "PixelGunGameData", "GameResultExtra", data)
end

function GamePacketSender:sendPixelGun1v1ResultData(rakssid, isOpen, data)
    GamePacketSender:sendPixelGunShowGameResult(rakssid, isOpen)
    if isOpen then
        PacketSender:sendServerCommonData(rakssid, "PixelGunGameData", "1v1ResultData", data)
    end
end

function GamePacketSender:sendPixelGunPersonResultData(rakssid, isOpen, data)
    GamePacketSender:sendPixelGunShowGameResult(rakssid, isOpen)
    if isOpen then
        PacketSender:sendServerCommonData(rakssid, "PixelGunGameData", "PersonResultData", data)
    end
end

function GamePacketSender:sendPixelGunTeamResultData(rakssid, isOpen, data)
    GamePacketSender:sendPixelGunShowGameResult(rakssid, isOpen)
    if isOpen then
        PacketSender:sendServerCommonData(rakssid, "PixelGunGameData", "TeamResultData", data)
    end
end

function GamePacketSender:sendPixelGunLevelUpData(rakssid, data)
    PacketSender:sendServerCommonData(rakssid, "PixelGunGameData", "LevelUpData", data)
end

function GamePacketSender:sendPixelGunChangeWeapon(rakssid, image, bgImage, time)
    local params = {
        image = image,
        bgImage = bgImage,
        time = time
    }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendServerCommonData(rakssid, "PixelGunGameData", "ChangeWeapon", data)
end

function GamePacketSender:sendPixelGunChickenGameData(rakssid, data)
    PacketSender:sendServerCommonData(rakssid, "PixelGunGameData", "ChickenGameData", data)
end

function GamePacketSender:sendPixelGunChickenResultData(rakssid, data)
    PacketSender:sendServerCommonData(rakssid, "PixelGunGameData", "ChickenResultData", data)
end

function GamePacketSender:sendShowPixelGunChickenResult(rakssid, data)
    PacketSender:broadCastServerCommonData("PixelGunGameData", "ShowChickenResult", data)
end

function GamePacketSender:sendPixelGunChickenWarningSetting(rakssid, canShow, shootRange, footRange, weaponRange)
    local params = {
        canShow = canShow,
        shootRange = shootRange,
        footRange = footRange,
        weaponRange = weaponRange,
    }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendServerCommonData(rakssid, "PixelGunGameData", "ChickenWarningSetting", data)
end

function GamePacketSender:sendPixelGunHideChickenWarning(rakssid, type)
    local params = { type = type }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendServerCommonData(rakssid, "PixelGunGameData", "HideChickenWarning", data)
end

function GamePacketSender:sendPixelGunShowChickenWarning(rakssid, position, type)
    local params = {
        position = VectorUtil.hashVector3(position),
        type = type
    }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendServerCommonData(rakssid, "PixelGunGameData", "ShowChickenWarning", data)
end

function GamePacketSender:sendPixelGunShowPoisonMask(rakssid, isShow)
    local params = {
        isShow = isShow
    }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendServerCommonData(rakssid, "PixelGunGameData", "ShowPoisonMask", data)
end

function GamePacketSender:sendPixelGunWeaponInfo(rakssid, data)
    PacketSender:sendServerCommonData(rakssid, "PixelGunGameData", "WeaponInfo", json.encode(data))
end

return GamePacketSender