---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/8/1 0001 10:07
---
require "packet.GamePacketSender"

VideoAdHelper = {}

function VideoAdHelper:doUnlockVehicleReward(player, entityId)
    if player.isLife and player.clientPeer ~= nil then
        player.clientPeer:tryAskVehicle(entityId, true, true)
    end
end

function VideoAdHelper:tryShowRespawnVideoAd(player)
    local key = DateUtil.getYearDay()
    if player.dayKey ~= key then
        player.dayKey = key
        player.respawnAdTimes = 0
    end
    if player.respawnAdTimes < GameConfig.respawnAdMaxTimes then
        local params = {
            Title = "g1014.respawn.ad.title",
            Content = "g1014.respawn.ad.content",
            AdButtonTxt = "g1014.respawn.ad.button.txt",
            AdIcon = "set:tycoon_ad.json image:ic_ad",
            AdType = Define.AdType.RespawnAd,
            TryShowReport = "die_revive_apply",
            ShowReport = "die_revive",
            WatchReport = "revive_click_AD",
            ShowCloseButton = true,
            IsAutoClose = true,
        }
        local data = DataBuilder.new():fromTable(params):getData()
        GamePacketSender:sendShowRespawnAd(player.rakssid, data)
    else
        RespawnHelper.sendRespawnCountdown(player, 1)
    end
end

function VideoAdHelper:doRespawnVideoAdReward(player)
    player.isWatchRespawnAd = true
    player.respawnAdTimes = player.respawnAdTimes + 1
    RespawnHelper.sendRespawnCountdown(player, 1)
end

function VideoAdHelper:initShopVideoAd(player)
    if TableUtil.getTableSize(player.itemAdRecords) == 0 then
        player.itemAdRecords = {
            [tostring(ItemID.HELMET_IRON)] = 0,
            [tostring(ItemID.PLATE_IRON)] = 0,
            [tostring(ItemID.LEGS_IRON)] = 0,
            [tostring(ItemID.BOOTS_IRON)] = 0
        }
    end
    local itemIds = { ItemID.HELMET_IRON, ItemID.PLATE_IRON, ItemID.LEGS_IRON, ItemID.BOOTS_IRON }
    local curTime = os.time()
    for _, itemId in pairs(itemIds) do
        local time = player.itemAdRecords[tostring(itemId)] or 0
        local params = {
            itemId = itemId,
            adType = Define.AdType.Shop,
            isShow = (curTime - time) >= GameConfig.shopAdRefreshTime
        }
        if not params.isShow then
            local delay = GameConfig.shopAdRefreshTime - (curTime - time)
            LuaTimer:schedule(function(userId, itemId)
                local c_player = PlayerManager:getPlayerByUserId(userId)
                if not c_player then
                    return
                end
                local c_params = {
                    itemId = itemId,
                    adType = Define.AdType.Shop,
                    isShow = true
                }
                local c_data = DataBuilder.new():fromTable(c_params):getData()
                GamePacketSender:sendShopVideoData(c_player.rakssid, c_data)
            end, delay * 1000, nil, player.userId, itemId)
        end
        local data = DataBuilder.new():fromTable(params):getData()
        GamePacketSender:sendShopVideoData(player.rakssid, data)
    end
end

function VideoAdHelper:doShopVideoAdReward(player, itemId)
    player:addItem(itemId, 1, 0)
    player.itemAdRecords[tostring(itemId)] = os.time()
    HostApi.notifyGetItem(player.rakssid, itemId, 0, 1)
    local params = {
        itemId = itemId,
        adType = Define.AdType.Shop,
        isShow = false
    }
    local data = DataBuilder.new():fromTable(params):getData()
    GamePacketSender:sendShopVideoData(player.rakssid, data)
    LuaTimer:schedule(function(userId, itemId)
        local c_player = PlayerManager:getPlayerByUserId(userId)
        if not c_player then
            return
        end
        local c_params = {
            itemId = itemId,
            adType = Define.AdType.Shop,
            isShow = true
        }
        local c_data = DataBuilder.new():fromTable(c_params):getData()
        GamePacketSender:sendShopVideoData(c_player.rakssid, c_data)
    end, GameConfig.shopAdRefreshTime * 1000, nil, player.userId, itemId)
end

return VideoAdHelper