---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/1/3 0003 16:05
---
ChestRewardConfig = {}
ChestRewardConfig.ChestRewards = {}

function ChestRewardConfig:initConfig(rewards)
    for _, reward in pairs(rewards) do
        local item = {
            Id = tonumber(reward.Id) or 0,
            Type = tonumber(reward.Type) or 0,
            RewardId = tonumber(reward.RewardId) or 0,
            Weight = tonumber(reward.Weight) or 0
        }
        table.insert(self.ChestRewards, item)
    end
end

function ChestRewardConfig:getChestRewardByType(type)
    local rewards = {}
    for _, reward in pairs(self.ChestRewards) do
        if reward.Type == type then
            table.insert(rewards, reward)
        end
    end
    return rewards
end

function ChestRewardConfig:getChestRewardId(id)
    for _, reward in pairs(self.ChestRewards) do
        if reward.Id == id then
            return reward
        end
    end
end

return ChestRewardConfig