---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/4/22 12:27
---

GiftBagConfig = {}
GiftBagConfig.giftBags = {}
GiftBagConfig.newGifts = {}
GiftBagConfig.GiftType = {
    NEW = 1,
    GENERAL = 2,
}
GiftBagConfig.GiftStatus = {
    UNBUY = 1,
    BOUGHT = 2,
}

function GiftBagConfig:initConfig(config)
    for _, item in pairs(config) do
        local gift = {}
        gift.id = tonumber(item.Id)
        gift.price = tonumber(item.Price)
        gift.discount = tonumber(item.Discount)
        gift.type = tonumber(item.Type)
        gift.weight = tonumber(item.Weight)
        gift.items = StringUtil.split(item.Items, "#")
        gift.moneyType = tonumber(item.MoneyType)
        gift.status = GiftBagConfig.GiftStatus.UNBUY
        if item.Repeat == "1" then
            gift.canRepeat = true
        else
            gift.canRepeat = false
        end
        if gift.type == self.GiftType.NEW then
            self.newGifts[gift.id] = gift
        end
        self.giftBags[gift.id] = gift
    end
end

function GiftBagConfig:getGiftBagById(id)
    if self.giftBags[tonumber(id)] == nil then
        return nil
    end
    local GiftBag = {}
    self:copy(self.giftBags[tonumber(id)], GiftBag)
    return GiftBag
end

function GiftBagConfig:getGiftBags()
    local result = {}
    self:copy(self.giftBags, result)
    return result
end

function GiftBagConfig:getNewGifts()
    local result = {}
    self:copy(self.newGifts, result)
    return result
end

function GiftBagConfig:copy(org, res)
    for k,v in pairs(org) do
        if type(v) ~= "table" then
            res[k] = v;
        else
            res[k] = {};
            self:copy(v, res[k])
        end
    end
end

return GiftBagConfig