---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wu.
--- DateTime: 2019/5/15 11:42
---
ModuleConfig = {}
ModuleConfig.Modules = {}

function ModuleConfig:initConfig(config)
    for i, v in pairs(config) do
        local module = {}
        module.Id = tonumber(v.Id)
        module.ItemId = tonumber(v.ItemId)
        module.Type = tonumber(v.Type)
        module.PriceType = tonumber(v.PriceType)
        module.Price = tonumber(v.Price)
        module.UnlockLevel = tonumber(v.UnlockLevel)
        module.HasGet = v.HasGet == "1"
        table.insert(self.Modules, module)
    end
end

function ModuleConfig:getModuleById(moduleId)
    for _, module in pairs(self.Modules) do
        if module.Id == tonumber(moduleId) then
            return module
        end
    end
end

function ModuleConfig:getModuleByItemId(moduleItemId)
    for _, module in pairs(self.Modules) do
        if module.ItemId == tonumber(moduleItemId) then
            return module
        end
    end
end
return ModuleConfig