---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/2/21 0021 11:12
---
NotificationConfig = {}
NotificationConfig.notifications = {}

function NotificationConfig:initConfig(config)
    for _, notification in pairs(config) do
        table.insert(self.notifications, json.encode({ message = notification.message }))
    end
end

function NotificationConfig:onPlayerReady(player)
    for _, notification in pairs(self.notifications) do
        HostApi.addDefaultNotification(player.rakssid, notification)
    end
end

return NotificationConfig