---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2018/12/30 0030 13:51
---
PropConfig = {}
PropConfig.PropType = {
    Prop = 1,
    Block = 2
}
PropConfig.Props = {}

function PropConfig:initConfig(props)
    for _, config in pairs(props) do
        local prop = {}
        prop.Id = tonumber(config.Id)
        prop.ItemId = tonumber(config.ItemId)
        prop.TabType = config.TabType
        prop.Type = tonumber(config.Type)
        prop.PropertyIds = config.PropertyIds
        prop.MaxLevel = tonumber(config.MaxLevel)
        prop.PriceType = tonumber(config.PriceType) or 0
        prop.Price = tonumber(config.Price) or 0
        prop.UnlockLevel = tonumber(config.UnlockLevel)
        prop.HasGet = config.HasGet == "1"
        table.insert(self.Props, prop)
    end
end

function PropConfig:getProp(propId)
    for _, config in pairs(PropConfig.Props) do
        if config.Id == propId then
            return config
        end
    end
end

function PropConfig:getPropsTab(gunId)
    for _, config in pairs(PropConfig.Props) do
        if config.ItemId == gunId then
            return tonumber(config.TabType)
        end
    end
    return nil
end

return PropConfig