---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2019/12/12 14:39
---

GamePacketSender = {}

function GamePacketSender:sendAdvertData(rakssid, type, times, seconds)
    local player = PlayerManager:getPlayerByRakssid(rakssid)
    if not player then
        return
    end
    local params = {
        type = type,
        times = times,
        seconds = seconds
    }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendLuaCommonData(rakssid, "SendAdvertData", data)
end

function GamePacketSender:sendAdvertRewardData(rakssid, type, id)
    local player = PlayerManager:getPlayerByRakssid(rakssid)
    if not player then
        return
    end
    local params = {
        type = type,
        rewardId = id
    }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendLuaCommonData(rakssid, "SendAdvertRewardData", data)
end

function GamePacketSender:sendCustomTip(rakssid, key)
    local player = PlayerManager:getPlayerByRakssid(rakssid)
    if not player then
        return
    end
    local params = {
        key = key,
    }
    PacketSender:sendLuaCommonData(rakssid, "SendCustomTipData", json.encode(params))
end

function GamePacketSender:sendCurrentSeasonInfo(rakssid, honorId, rank, honor, days)
    local player = PlayerManager:getPlayerByRakssid(rakssid)
    if not player then
        return
    end
    local params = {
        honorId = honorId,
        rank = rank,
        honor = honor,
        days = days
    }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendLuaCommonData(rakssid, "CurrentSeasonInfo", data)
end

function GamePacketSender:sendLastSeasonInfo(rakssid, honorId, rank, honor)
    local player = PlayerManager:getPlayerByRakssid(rakssid)
    if not player then
        return
    end
    local params = {
        honorId = honorId,
        rank = rank,
        honor = honor
    }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendLuaCommonData(rakssid, "LastSeasonInfo", data)
end

--发送职业奖池的数据
function GamePacketSender:sendJobsUpdateData(rakssid, data)
    local player = PlayerManager:getPlayerByRakssid(rakssid)
    if not player then
        return
    end
    PacketSender:sendLuaCommonData(rakssid, "jobListUpdate", data)
end

--发送更新职业选择界面的数据(职业id,次数,)
function GamePacketSender:sendUpdateJobChoiceUIData(rakssid, data)
    local player = PlayerManager:getPlayerByRakssid(rakssid)
    if not player then
        return
    end
    PacketSender:sendLuaCommonData(rakssid, "UpdateJobs", data)
end


--从奖池随机出来的职业id传给客户端抽取界面
function GamePacketSender:sendSynJobsIdData(rakssid, id)
    local player = PlayerManager:getPlayerByRakssid(rakssid)
    if not player then
        return
    end
    local params = {
        id = id,
    }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendLuaCommonData(rakssid, "synJobId", data)
end


--发送当前选择的职业id
function GamePacketSender:sendCurJobIdData(rakssid, id)
    local player = PlayerManager:getPlayerByRakssid(rakssid)
    if not player then
        return
    end
    local params = {
        id = id,
    }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendLuaCommonData(rakssid, "CurJobId", data)
end

--打开界面
function GamePacketSender:sendOpenUIByType(rakssid, type)
    local params = {
        type = type,
    }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendLuaCommonData(rakssid, "OpenUIData", data)
end

function GamePacketSender:sendUsePropData(rakssid, id, num)
    local player = PlayerManager:getPlayerByRakssid(rakssid)
    if not player then
        return
    end
    local params = {
        propId = id,
        num = num
    }
    local data = DataBuilder.new():fromTable(params):getData()
    PacketSender:sendLuaCommonData(rakssid, "sendUsePropData", data)
end

return GamePacketSender