---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaolai.
--- DateTime: 2019/6/20 11:32
---

BoneMealConfig = {}
BoneMealConfig.flower = {}
BoneMealConfig.ordinaryWeights = {}
BoneMealConfig.ordinaryFlowers = {}

BoneMealConfig.ORDINARY_WEIGHTS_GROUP = 2000

function BoneMealConfig:init(config)
    local allWeights = 0
    for i, k in pairs(config) do
        local item = {}
        item.id = tonumber(k.id)
        item.blockId = tonumber(k.blockId)
        item.blockMeta = tonumber(k.blockMeta)
        item.weights = tonumber(k.weights)
        self.flower[i] = item

        allWeights = allWeights + item.weights
        table.insert(self.ordinaryWeights, item.weights)
        table.insert(self.ordinaryFlowers, item)
    end

    for k,v in pairs(self.ordinaryWeights) do
        self.ordinaryWeights[k] = v / allWeights
    end

    self:initRandomSeed()
end

function BoneMealConfig:initRandomSeed()
    LotteryUtil:initRandomSeed(BoneMealConfig.ORDINARY_WEIGHTS_GROUP, self.ordinaryWeights)
end

function BoneMealConfig:getFlowerBlockIDById(id)
    for i, k in pairs(self.flower) do
        if k.id == id then
            return k.blockId
        end
    end
    return
end

function BoneMealConfig:getFlowerBlockMetaById(id)
    for i, k in pairs(self.flower) do
        if k.id == id then
            return k.blockMeta
        end
    end
    return 0
end



return BoneMealConfig