---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/12/11 12:09
---

ChristmasNpcConfig = {}
ChristmasNpcConfig.christmas = {}

function ChristmasNpcConfig:init(config)
    for i, v in pairs(config) do
        local item = {}
        item.id = tonumber(v.id)
        item.headInfo = tostring(v.headInfo)
        item.actor = tostring(v.actor)
        item.actorBody = tostring(v.actorBody)
        item.actorBodyId = tonumber(v.actorBodyId)
        local actorPos = StringUtil.split(tostring(v.actorPos), "#")
        item.actorPos = VectorUtil.newVector3(actorPos[1], actorPos[2], actorPos[3])
        item.yaw = tonumber(v.yaw)
        item.type = tonumber(v.type)
        item.entityId = tonumber(0)
        self.christmas[item.id] = item
        self:onCreate(item)
    end
end

function ChristmasNpcConfig:onCreate(item)
    if GameMatch:checkIfChristmasFinish() then
        local entityId = EngineWorld:addSessionNpc(item.actorPos, item.yaw, item.type, item.actor, function(entity)
            entity:setNameLang(item.headInfo or "")
            entity:setActorBody(item.actorBody or "body")
            entity:setActorBodyId(item.actorBodyId or "")
        end)
        HostApi.log("ChristmasNpcConfig:onCreate " .. entityId)
        item.entityId = entityId
    end
end

function ChristmasNpcConfig:onDestroy()
    EngineWorld:removeEntity(self.entityId)
end

function ChristmasNpcConfig:getNpcIdByEntityId(player, entityId)
    for i, v in pairs(self.christmas) do
        if v.entityId == entityId and v.id == 4801 then
            local data = {}
            data.index = ChristmasConfig.Type.BuyType
            GamePacketSender:sendChristUseBoxItem(player.rakssid, data)
            if player.enableIndie then
                GameAnalytics:design(player.userId, 0, { "g1048common_click_indie", Define.ClickType.TYPE9})
            else
                GameAnalytics:design(player.userId, 0, { "g1048common_click", Define.ClickType.TYPE9})
            end

        end
        if v.entityId == entityId and v.id == 4802 then
            local time_remaining = player:checkCanGetRewardTime()
            if time_remaining == 0 then
                local data = {}
                data.entityId = v.entityId
                data.headInfo = v.headInfo
                GamePacketSender:sendChristmasReward(player.rakssid, data)
                if player.enableIndie then
                    GameAnalytics:design(player.userId, 0, { "g1048common_click_indie", Define.ClickType.TYPE10})
                else
                    GameAnalytics:design(player.userId, 0, { "g1048common_click", Define.ClickType.TYPE10})
                end
            end
        end
    end

end


return ChristmasNpcConfig