---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaolai.
--- DateTime: 2019/5/31 20:07
---

TreeSectionConfig = {}
TreeSectionConfig.tree = {}

function TreeSectionConfig:init(config)
    for i, v in pairs(config) do
        local item = {}
        item.id = tonumber(v.id)
        item.blockId = tonumber(v.blockId)
        item.blockMeta = tonumber(v.blockMeta)
        item.schematic = tostring(v.schematic)
        item.times = tonumber(v.times)
        self.tree[i] = item
    end
end

function TreeSectionConfig:getSchematicByBlockMeta(blockMeta)
    for i, k in pairs(self.tree) do
        if k.blockMeta == blockMeta then
            return k.schematic
        end
    end
    return
end

function TreeSectionConfig:getTimeByBlockMeta(blockMeta)
    for i, k in pairs(self.tree) do
        if k.blockMeta == blockMeta then
            return k.times or 10
        end
    end
    return 10
end

function TreeSectionConfig:theSchematicReplaceBlock(rakssid, blockMeta, vec3)
    local master = PlayerManager:getPlayerByRakssid(rakssid)
    if not master then
        return
    end
    local schematic = self:getSchematicByBlockMeta(blockMeta)
    if not schematic then
        return
    end
    local masterManorInfo = GameMatch:getUserManorInfo(master.userId)
    if not masterManorInfo then
        return
    end
    EngineWorld:setBlockToAir(vec3)
    masterManorInfo:recordBlock(vec3, 0, 0)
    LuaTimer:scheduleTimer(function(userId)
        local newVec3 = VectorUtil.newVector3i(vec3.x - 2, vec3.y, vec3.z - 2)
        local player = PlayerManager:getPlayerByUserId(userId)
        if not player then
            return
        end
        EngineWorld:createSchematic(schematic, newVec3, false, false, false, player.rakssid)
        player.taskController:packingProgressData(player, Define.TaskType.plante_tree, GameMatch.gameType, BlockID.SAPLING, 1, blockMeta)
    end, 1000, 1, master.userId)
end

return TreeSectionConfig