---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/8/8 16:40
---
GameConfig = {}

--GameConfig.initPos

function GameConfig:init(config)
    GameConfig:parseGameConfig(config)

    MonsterConfig:init(FileUtil.getConfigFromCsv("setting/Monster.csv"))
    --TODO
end

function GameConfig:parseGameConfig(config)
    GameConfig.initPos = VectorUtil.newVector3(config.initPos[1].x, config.initPos[1].y, config.initPos[1].z)
end

return GameConfig