---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/10/28 15:46
---
ThrowSkill = class("ThrowSkill", BaseSkill)

function ThrowSkill:onSkillStart(ticks)
    self.hasDamage = false
    self.hurterId = 0
    self:doThrow()
end

function ThrowSkill:doThrow()
    local player = self:checkThrower()
    if not player then
        return
    end

    self.hurterId = player:getFirstChildrenEntityId()
    local hurter = PlayerManager:getPlayerByEntityId(self.hurterId)
    if hurter == nil then
        hurter = ActorManager:getActor(self.hurterId)
        self.skillStage = Define.SkillStage.SkillEnd
    else
        --解绑
        player:unbindAllEntity()
        hurter.throwSkillUid = self.uuid --记录被作用的技能uid
        HostApi.doThrow(hurter:getEntityId(), hurter:getPosition(),
                player.entityPlayerMP.rotationYaw, self.config.rotationPitch, self.config.flySpeed, self.config.flyTime)
        self.skillStage = Define.SkillStage.DoDamage
    end
end

function ThrowSkill:onDoDamage(ticks)
    local player = self:checkThrower()
    if not player then
        return
    end
    local hurter = PlayerManager:getPlayerByEntityId(self.hurterId)
    if not hurter then
        return
    end
    if hurter:isFlyingByPulled() and hurter:isEntityAlive() then
        return
    end

    --伤害计算(落地)
    self:doDamage(nil)

    self.skillStage = Define.SkillStage.SkillEnd
end

function ThrowSkill:doDamage(entity)
    if self.hasDamage then
        self.skillStage = Define.SkillStage.SkillEnd
        return
    end
    self.hasDamage = true
    local attacker = PlayerManager:getPlayerByUserId(self.userId)
    if not attacker then
        return
    end

    local hurter = PlayerManager:getPlayerByEntityId(self.hurterId)

    if entity == nil then
        if hurter then
            entity = Utility.getPulledCollisionEntity(hurter, attacker)
        end
    end

    --对碰撞目标造成伤害
    if entity then
        local entityId = entity:hashCode()
        local player = PlayerManager:getPlayerByEntityId(entityId)
        if player then
            player:bePlayerAttacked(attacker, Define.HurtType.Attack, false, self.skillId)
        end

        local monster = MonsterManager:getMonster(entityId)
        if monster then
            monster:onPlayerAttack(attacker, self.skillId)
        end

        local actor = ActorManager:getActor(entityId)
        if actor then
            actor:onActorHurt(attacker.property:getAttack(self.skillId))
        end
    end

    --对抓取者造成伤害
    if hurter then
        hurter:bePlayerAttacked(attacker, Define.HurtType.Skill, true, self.skillId)
    end
end

return ThrowSkill