---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/27 14:20
---

AnimalActorConfig = {}
AnimalActorConfig.animalActor = {}

function AnimalActorConfig:init(config)
    self:initActor(config)
end

function AnimalActorConfig:initActor(config)
    for id, animal in pairs(config) do
        local item = {}
        item.id = id
        item.name = animal.name
        item.actor = animal.actor
        table.insert(self.animalActor, item)
    end
end

function AnimalActorConfig:randomActor()
    local actors = {}
    actors = self.animalActor
    math.randomseed(os.clock() * 1000000)
    local index = math.random(1,#actors)
    local m = actors[index].actor
    return m
end