---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/12/4 11:20
---

AreaOfEliminateConfig = {}
AreaOfEliminateConfig.AreaOfEliminate = {}

function AreaOfEliminateConfig:init(config)
    self:initAreaOfEliminate(config)
end

function AreaOfEliminateConfig:initAreaOfEliminate(AreaOfEliminate)
    for i, v in pairs(AreaOfEliminate) do
        local areaofeliminate = {}
        areaofeliminate.MinX = math.min(tonumber(v.X1), tonumber(v.X2))
        areaofeliminate.MaxX = math.max(tonumber(v.X1), tonumber(v.X2))
        areaofeliminate.MinY = math.min(tonumber(v.Y1), tonumber(v.Y2))
        areaofeliminate.MaxY = math.max(tonumber(v.Y1), tonumber(v.Y2))
        areaofeliminate.MinZ = math.min(tonumber(v.Z1), tonumber(v.Z2))
        areaofeliminate.MaxZ = math.max(tonumber(v.Z1), tonumber(v.Z2))
        self.AreaOfEliminate[tonumber(i)] = areaofeliminate
    end
end

function AreaOfEliminateConfig:destoryAreaOfEliminate()
    for i, vec3 in pairs(self.AreaOfEliminate) do
        for X = vec3.MinX, vec3.MaxX do
            for Y = vec3.MinY, vec3.MaxY do
                for Z = vec3.MinZ, vec3.MaxZ do
                    EngineWorld:setBlockToAir(VectorUtil.newVector3i(X, Y, Z))
                end
            end
        end
    end
end

return AreaOfEliminateConfig