---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/5 15:08
---
require "config.ShopGoodsConfig"

ShopConfig = {}

ShopConfig.Shop = {}

function ShopConfig:init(shop)
    for groupId, group in pairs(shop) do
        local goodsGroup = {}
        goodsGroup.type = group.type
        goodsGroup.icon = group.icon
        goodsGroup.name = group.name
        self.Shop[groupId] = goodsGroup
    end
end

function ShopConfig:prepareShop()
    for groupId, group in pairs(self.Shop) do
        EngineWorld:addGoodsGroupToShop(group.type, group.icon, group.name)
        local goods = ShopGoodsConfig.goods
        for id, good in pairs(goods) do
            local type = tonumber(group.type)
            if type == good.BindShopId then
                EngineWorld:addGoodsToShop(group.type, self.newGoods(good))
            end

        end
    end
end

function ShopConfig.newGoods(item)
    local goods = Goods.new()
    goods.itemId = item.GoodsId
    goods.itemNum = 1
    goods.coinId = item.CoinId
    goods.blockymodsPrice = item.BlockymodsPrice
    goods.blockmanPrice = item.BlockmanPrice
    goods.limit = item.Limit
    goods.desc = item.GoodsDesc
    return goods
end

return ShopConfig