---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaolai.
--- DateTime: 2018/11/5 15:08
---

Messages = {}

function Messages:gamename()
    return TextFormat:getTipType(155)
end

function Messages:gameOverHint(seconds)
    return 28, tostring(seconds)
end

function Messages:gameResetTimeHint()
    return 29
end

function Messages:becomeRole(role)
    return 45, self:getRoleName(role)
end

function Messages:getRoleName(role)
    if role == GamePlayer.ROLE_HIDE then
        return TextFormat.colorGreen .. "[" .. TextFormat:getTipType(156) .. "]"
    elseif role == GamePlayer.ROLE_SEEK then
        return TextFormat.colorRed .. "[" .. TextFormat:getTipType(157) .. "]"
    else
        return TextFormat.colorGreen .. "[" .. TextFormat:getTipType(156) .. "]"
    end
end

function Messages:assignRoleTimeHint(seconds)
    return 49, tostring(seconds)
end

function Messages:secondAssignRoleTimeHint(seconds)
    return 1038006, tostring(seconds)
end

function Messages:clickDisappearActor()
    return 1038003
end

function Messages:clickSignActor()
    return 1038004
end

function Messages:gameStart()
    return 1038005
end

function Messages:becomeHideHint()
    return 158
end

function Messages:changeAndHideTime(seconds)
    return 159, tostring(seconds)
end

function Messages:changeAndHideHint(seconds)
    return 1038001, tostring(seconds)
end

function Messages:waitChangeAndHideHint(seconds)
    return 1038002, tostring(seconds)
end

function Messages:changeActorByNoStart()
    return 161
end

function Messages:changeActorByNoTimes(times)
    return 162, tostring(times)
end

function Messages:changeActorByNoHide()
    return 163
end

function Messages:msgLastModelName(name)
    return 164, "[" .. TextFormat:getTipType(name) .. "]"
end

function Messages:findFalse()
    return 1038011
end

function Messages:findTrue()
    return 1038008
end

function Messages:finded()
    return 20003
end

function Messages:lastHide(num)
    return 20004, tonumber(num)
end

function Messages:findFalseLast45Second()
    return 20050
end

function Messages:last45Second(seconds)
    return 1038007, tostring(seconds)
end

function Messages:msgWaitMatching()
    return 1038010
end

function Messages:msgDontBuyGoodsByNoRole()
    return 1038009
end

return Messages