---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2019/10/16 17:48
---

BlockConfig = {}
BlockConfig.block = {}
BlockConfig.BlockId = {
        RedBlock = 1431,
        YellowBlock = 1432,
        BlueBlock = 1433,
        GreenBlock = 1434,
        ColorBlock = 1435,
        HollowBlock = 1436
}

function BlockConfig:init(config)
    for i, v in pairs(config) do
        local item = {}
        item.id = tonumber(v.id)
        item.type = tonumber(v.type)
        item.poolId = StringUtil.split(v.poolId, "#")
        item.blockId = v.blockId
        self.block[item.blockId] = item
    end
end

function BlockConfig:getBlockById(id)
    return self.block[tostring(id + 1000)]
end

return BlockConfig