---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/9/25 15:00
---

require "event.TNTRainEvent"
require "event.ArrowRainEvent"
require "event.SnowRainEvent"
require "event.WaterRainEvent"
require "event.TransferEvent"
require "event.InterchangeEvent"
require "event.FrozenEvent"
require "event.HidingEvent"
require "event.BloodReturnEvent"
require "event.QuicklyBuildEvent"
require "event.AttackPropertyEvent"
require "event.ThunderEvent"
require "event.IslandFrozenEvent"
require "event.EnderDragonEvent"
require "event.RefreshBoxEvent"

EventConfig = {}
EventConfig.Events = {}
EventConfig.EventType = {
    TNTRain = 1,
    ArrowRain = 2,
    SnowRain = 3,
    WaterRain = 4,
    Transfer = 5,
    Interchange = 6,
    Frozen = 7,
    Hiding = 8,
    BloodReturn = 9,
    QuicklyBuild = 10,
    AttackProperty = 11,
    Thunder = 12,
    IslandFrozen = 13,
    EnderDragon = 14,
    RefreshBox = 15
}
EventConfig.EventMapping = {
    [EventConfig.EventType.TNTRain] = TNTRainEvent,
    [EventConfig.EventType.ArrowRain] = ArrowRainEvent,
    [EventConfig.EventType.SnowRain] = SnowRainEvent,
    [EventConfig.EventType.WaterRain] = WaterRainEvent,
    [EventConfig.EventType.Transfer] = TransferEvent,
    [EventConfig.EventType.Interchange] = InterchangeEvent,
    [EventConfig.EventType.Frozen] = FrozenEvent,
    [EventConfig.EventType.Hiding] = HidingEvent,
    [EventConfig.EventType.BloodReturn] = BloodReturnEvent,
    [EventConfig.EventType.QuicklyBuild] = QuicklyBuildEvent,
    [EventConfig.EventType.AttackProperty] = AttackPropertyEvent,
    [EventConfig.EventType.Thunder] = ThunderEvent,
    [EventConfig.EventType.IslandFrozen] = IslandFrozenEvent,
    [EventConfig.EventType.EnderDragon] = EnderDragonEvent,
    [EventConfig.EventType.RefreshBox] = RefreshBoxEvent,
}

function EventConfig:init(config)
    for _, event in pairs(config) do
        local item = {}
        item.id = event.id
        item.type = tonumber(event.type)
        item.param1 = event.param1
        item.param2 = event.param2
        item.param3 = event.param3
        item.time = tonumber(event.time)
        local class = self.EventMapping[item.type]
        if class ~= nil then
            self.Events[item.id] = class.new(item)
        end
        if item.type == self.EventType.EnderDragon then
            self.enderDragon = item.id
        end
    end
end

function EventConfig:onTriggered(id, player)
    local event = self.Events[tostring(id)]
    if not event then
        return
    end
    event:onTriggered(player)
end

function EventConfig:getEventByType(type)
    for _, event in pairs(self.Events) do
        if type == event.config.type then
            return event
        end
    end
    return nil
end