---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2019/9/25 11:24
---
--职业配置
require "manager.JobPoolManager"

JobConfig = {}
JobConfig.JobList = {}

JobStatus = {
    HAVE = 1, --拥有状态
    NO_HAVE = 2     --未拥有状态
}

function JobConfig:init(configs)
    print("JobConfig:init(configs)")
    for _, config in pairs(configs) do
        local item = {}
        item.id = tonumber(config.id)
        item.name = config.name
        item.quality = tonumber(config.quality)
        item.type = tonumber(config.type)
        item.initializeItem = config.initializeItem
        item.num = config.num
        item.sort = tonumber(config.sort)
        item.weight = tonumber(config.weight)
        item.weight2 = tonumber(config.weight2)
        item.poolId = tonumber(config.poolId)
        item.times = 0
        if tonumber(config.type) == 1 then
            item.status = JobStatus.HAVE
        else
            item.status = JobStatus.NO_HAVE
        end
        item.isOpen = false
        self.JobList[item.id] = item
        JobPoolManager:addJobToPools(item)
    end
end

function JobConfig:getJobById(id)
    local result = self.JobList[tonumber(id)]
    if result ~= nil then
        return result
    end
    return nil
end

function JobConfig:getNameById(id)
    local result = self.JobList[tonumber(id)]
    if result ~= nil then
        return result.name
    end
    return nil
end

function JobConfig:getJobTypeById(id)
    local result = self.JobList[tonumber(id)]
    if result ~= nil then
        return result.type
    end
    return nil
end

--得到默认的职业
function JobConfig:getDefaultJob()
    for i, item in pairs(self.JobList) do
        if item.type == Define.JobType.DefaultJob then
            return item.id
        end
    end
end

function JobConfig:getJobList()
    local result = TableUtil.copyTable(self.JobList)
    return result
end

return JobConfig