---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/10/17 12:04
---

SkillEffectConfig = {}
SkillEffectConfig.Effects = {}

function SkillEffectConfig:init(config)
    for _, effect in pairs(config) do
        local item = {}
        item.id = effect.id
        item.skillId = effect.skill
        item.param = effect.param
        item.value = effect.value
        self.Effects[item.skillId] = item
    end
end

function SkillEffectConfig:getSkillEffect(skillId)
    return self.Effects[tostring(skillId)]
end