---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/5/29 13:28
---
GameStore = {}

local StoreLimitRecord = {}

local function init()
    CommonDataEvents:registerCallBack("BuyGoods", function(userId, goodsId)
        GameStore:onPlayerBuyGoods(userId, goodsId, true)
    end)
end

init()

---回滚订单，补钱！！！！
local function rollBackOrder(player, goods)
    local currency = StoreConfig:getCurrencyConfig(goods.CurrencyId)
    if not currency then
        return
    end
    if currency.ItemId > 0 then
        player:addItem(currency.ItemId, goods.Price)
    end
end

---检查玩家背包是否有比goods更高级或平级的道具
local function checkHasHighLevelGoods(player, goods)
    if goods.LevelGroup == "#" then
        return false
    end
    local inv = player:getInventory()
    if goods.Type == GoodsType.Item then
        for index = 1, 36 do
            local info = inv:getItemStackInfo(index - 1)
            if info.id ~= 0 then
                local _goods = StoreConfig:getGoodsByItemId(info.id)
                if _goods and _goods.LevelGroup == goods.LevelGroup and _goods.Level >= goods.Level then
                    return true
                end
            end
        end
    end
    if goods.Type == GoodsType.Armor then
        for index = 101, 104 do
            local info = inv:getItemStackInfo(index - 1)
            if info.id ~= 0 then
                local _goods = StoreConfig:getGoodsByItemId(info.id)
                if _goods and _goods.LevelGroup == goods.LevelGroup and _goods.Level >= goods.Level then
                    return true
                end
            end
        end
    end
    if goods.Type == GoodsType.Upgrade then
        local team = GameMatch.Teams[player:getTeamId()]
        if not team or not team.info then
            return true
        end
        if tonumber(team.info:getValue(goods.ItemId)) >= goods.Level then
            return true
        end
    end
    return false
end

local function onBuyGoodsSuccess(player, goods)
    local count = GoodsStorePrivilege:onBuyGoods(player, goods)
    if goods.Type == GoodsType.Item then
        if goods.Level == 1 then
            player:addInitItems(goods.ItemId)
        end
        player:tryAddItem(goods.ItemId, count, 0, TableUtil.copyTable(goods.EnchantList))
    elseif goods.Type == GoodsType.Armor then
        player:tryAddItem(goods.ItemId, count, 0, TableUtil.copyTable(goods.EnchantList))
    elseif goods.Type == GoodsType.Upgrade then
        local success = GameGains:onPlayerUpgrade(player, goods.ItemId, goods.Level)
        if not success then
            rollBackOrder(player, goods)
        end
    elseif goods.Type == GoodsType.Privilege then
        Privilege.addPrivilegeTime(player, goods.ItemId)
        local currency = StoreConfig:getCurrencyConfig(goods.CurrencyId)
        if currency and currency.RealId == Define.Money.KEY then
            ReportUtil.reportPlayerCostKey(player, goods.Price, "key_BuyPrivilege", goods.Id)
        end
    elseif goods.Type == GoodsType.Key then
        player:addYaoShi(count)
    elseif goods.Type == GoodsType.Horn then
        player:addHorn(count)
    elseif goods.Type == GoodsType.Ticket then
        player:addTicket(count)
    end
    LuaTimer:schedule(function()
        CommonPacketSender:sendBuyGoodsSuccess(player.rakssid, goods.Id)
    end, 100)
end

function GameStore:checkCanBuyGoods(player, goods, needMoney, callback)
    if goods.Price < 0 then
        callback(false)
        return
    end
    if player:isDead() then
        return
    end
    if goods.Type == GoodsType.Item then
        local inv = player:getInventory()
        if not inv then
            callback(false)
            return
        end
        if not inv:isCanAddItem(goods.ItemId, 0, goods.Count) then
            ---背包放不下
            callback(false)
            return
        end
    end
    if goods.Type == GoodsType.Item or goods.Type == GoodsType.Armor or goods.Type == GoodsType.Upgrade then
        if checkHasHighLevelGoods(player, goods) then
            ---已经拥有相同或更高等级的道具了
            callback(false)
            return
        end
    end
    ---判断钱够不够
    local currency = StoreConfig:getCurrencyConfig(goods.CurrencyId)
    if not currency then
        callback(false)
        return
    end
    if goods.LimitCount ~= -1 and needMoney then
        ---限购功能(默认认为扣款成功)
        local record = StoreLimitRecord[tostring(player.userId)] or {}
        StoreLimitRecord[tostring(player.userId)] = record
        local limit = record[tostring(goods.Id)] or goods.LimitCount
        if limit == 0 then
            return false
        end
        record[tostring(goods.Id)] = limit - 1
    end
    if currency.ItemId > 0 then
        local inv = player:getInventory()
        if inv:getItemNum(currency.ItemId) < goods.Price and needMoney then
            callback(false)
            return
        end
        ---扣钱给商品
        if needMoney then
            player:removeItem(currency.ItemId, goods.Price)
        end
        callback(true)
    else
        if not MoneyUtil:checkHasMoney(player, currency.RealId, goods.Price) and needMoney then
            callback(false)
            return
        end
        ---扣钱给商品
        if needMoney then
            MoneyUtil:consumeMoney(player, goods.Id, currency.RealId, goods.Price, function()
                callback(true)
            end)
        else
            callback(true)
        end
    end
end

function GameStore:onPlayerBuyGoods(userId, goodsId, needMoney)
    local player = PlayerManager:getPlayerByUserId(userId)
    if not player then
        return false
    end
    local goods = StoreConfig:getGoodsById(goodsId)
    if not goods then
        ---没找到商品信息
        return false
    end
    local isSuccess = false
    self:checkCanBuyGoods(player, goods, needMoney, function(canBuy)
        if canBuy then
            onBuyGoodsSuccess(player, goods)
            isSuccess = true
        end
    end)
    return isSuccess
end

function GameStore:onPlayerLotteryReplace(userId, goodsId)
    local player = PlayerManager:getPlayerByUserId(userId)
    if not player then
        return false
    end
    local goods = StoreConfig:getGoodsById(goodsId)
    if not goods then
        return false
    end
    onBuyGoodsSuccess(player, goods)
end

