---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/8/9 18:07
---
GameMatch = {}
GameMatch.Status = Define.GameStatus.GameWaitPlayer
GameMatch.gameType = "g1056"

function GameMatch:init()
    GameTimeTask:start()
end

return GameMatch