---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/8/8 16:16
---
package.path = package.path ..';..\\?.lua';

require "BaseHeader"
require "Header"

local ScriptMain = {}

function ScriptMain:init()
    BaseMain:setGameType(GameMatch.gameType)
    ScriptMain:initListener()
    GameMatch:init()
    DBManager:setGameType("g1057")
    DBManager:addMustLoadSubKey(DbUtil.HALL_INFO)
    HostApi.setBreakBlockSoon(false)
    ServerHelper.putIntPrefs("SpeedAddMax", 10000)
    ServerHelper.putBoolPrefs("SendSystemsChat", false)
    ServerHelper.putBoolPrefs("IsBlockmanCollision", false)
    PlayerManager.IsMessages = false
    --TODO

    --LogUtil.setDebug(true)
end

function ScriptMain:initListener()
    GameListener:init()
    PlayerListener:init()
    EntityListener:init()
    --TODO
end

ScriptMain:init()