---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/5 15:18
---

package.path = package.path ..';..\\?.lua';

require "Match"
require "task.GameTimeTask"
require "listener.GameListener"
require "listener.PlayerListener"
require "listener.BlockListener"
require "listener.RankListener"
require "listener.LogicListener"
require "listener.DBDataListener"

ScriptMain = {}

function ScriptMain.init()
    HostApi.log("ScriptMain.init")
    GameListener:init()
    PlayerListener:init()
    BlockListener:init()
    RankListener:init()
    LogicListener:init()
    DBDataListener:init()
    BaseMain:setGameType(GameMatch.gameType)
    RewardManager:setGameType("g1037")
    HostApi.setNeedFoodStats(false)
    HostApi.setFoodHeal(false)
    HostApi.setGunFireIsNeedBullet(false)
    DBManager:addMustLoadSubKey(2)
end

ScriptMain:init()