---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/6/24 0024 14:42
---
WorldTimeManager = {}
WorldTimeManager.Changing = false
WorldTimeManager.WorldTimer = os.time()
WorldTimeManager.ChangeTimer = 0
WorldTimeManager.ChangeCount = 0 --改变次数
--WorldTimeManager.DayCount = 0 --过了多少天

function WorldTimeManager:onTick()
    if self.Changing then
        if os.time() - self.ChangeTimer > GameConfig.WorldInfo.ChangeTime then
            self.Changing = false
            self.WorldTimer = os.time()
            self.ChangeTimer = 0
        end
    else
        local duration = 0
        local endTime = 0
        if EngineWorld:isNight() then
            duration = GameConfig.WorldInfo.NightTime
            endTime = 6000
        else
            duration = GameConfig.WorldInfo.DayTime
            endTime = 18000
        end

        if os.time() - self.WorldTimer > duration then
            self.Changing = true
            self.WorldTimer = 0
            self.ChangeTimer = os.time()
            local ticks = GameConfig.WorldInfo.ChangeTime * 20
            local speed = NumberUtil.getIntPart(12000 / ticks)
            EngineWorld:setQuickWorldTime(ticks, speed, endTime)
            ActorManager:dayAlternatesWithNight(EngineWorld:isNight())

            self.ChangeCount = self.ChangeCount + 1
            if self.ChangeCount % 2 == 0 then
                --self.DayCount = self.DayCount + 1
                for i, vPlayer in pairs(PlayerManager:getPlayers()) do
                    vPlayer.surviveDays = vPlayer.surviveDays + 1
                    vPlayer:updateSurviveDiary()
                end
            end
        end
    end
end

return WorldTimeManager