---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2018/12/5 0005 9:41
---

local ICommonTask = class("CommonTask", ITask)

local function checkMinors()
    local hour = tonumber(os.date("%H"))
    if hour >= 8 and hour < 22 then
        return
    end
    ---每日22点到次日8点，不能给未成年人提供游戏
    local players = PlayerManager:getPlayers()
    for _, player in pairs(players) do
        if player.gameTimeToday >= 0 then
            HostApi.sendGameover(player.rakssid, 167, GameOverCode.GameOver)
        end
    end
end

function ICommonTask:onTick(ticks)
    GameServer:onTick()
    DBManager:onTick(ticks)
    UserExpManager:tryCalculationExp()
    UserExpManager:trySaveExpResult()
    SeasonManager:trySaveHonorResult()
    ReportManager:tryReportGameData()
    GameAnalyticsCache:trySendEvents()
    SumRechargeHelper:trySaveSumRechargeData(ticks)
    ExchangeHelper:updatePlayerGameTime()
    checkMinors()
    if Platform.isWindow() and HU then
        HU.Update()
    end
end

function ICommonTask:onCreate()
    local delay = 100
    local MillsTask = ITask.new(99998, delay)
    function MillsTask:onTick(ticks)
        LuaTimer:onTick(delay)
        RespawnHelper.tryPlayerRespawn(delay)
    end
    MillsTask:start()
end

CommonTask = ICommonTask.new(99999)

return CommonTask