---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/8/14 12:07
---
require "data.GameBasement"

GameTeam = class()

GameTeam.ID = 0
GameTeam.name = "Red"
GameTeam.PreparePos = {}
GameTeam.RebirthPos = {}
GameTeam.Yaw = {}
GameTeam.curPlayers = 0
GameTeam.color = TextFormat.colorRed

function GameTeam:ctor(config)
    self.ID = config.ID
    self.name = config.Name
    self.PreparePos = config.PreparePos
    self.RebirthPos = config.RebirthPos
    self.Yaw = config.Yaw
    self.color = config.Color
    self.basement = nil
end

function GameTeam:addPlayer()
    self.curPlayers = self.curPlayers + 1
end

function GameTeam:setBasement(basement)
    self.basement = basement
end

function GameTeam:getDisplayName()
    return self.color .. self.name
end

function GameTeam:onPlayerQuit()
    self.curPlayers = self.curPlayers - 1
    if self.basement then
        self.basement:onPlayerQuit()
    end
end

function GameTeam:isDeath()
    if self.curPlayers <= 0 then
        return true
    end
    if self.basement == nil then
        return true
    end
    if self.basement:isDead() then
        return true
    end
    return false
end

return GameTeam