---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/5 16:07
---

Messages = {}

function Messages:gamename()
    return TextFormat:getTipType(155)
end

function Messages:gameOverHint(seconds)
    return 28, tostring(seconds)
end

function Messages:becomeRole(role)
    return 45, self:getRoleName(role)
end

function Messages:getRoleName(role)
    if role == GamePlayer.ROLE_HIDE then
        return TextFormat.colorGreen .. "[" .. TextFormat:getTipType(156) .. "]"
    elseif role == GamePlayer.ROLE_SEEK then
        return TextFormat.colorRed .. "[" .. TextFormat:getTipType(157) .. "]"
    else
        return TextFormat.colorGreen .. "[" .. TextFormat:getTipType(156) .. "]"
    end
end

function Messages:assignRoleTimeHint(seconds)
    return 49, tostring(seconds)
end

function Messages:becomeHideHint(seconds)
    return 1039001, tostring(seconds)

end

function Messages:becomeSeekHint()
    return 1039004
end

function Messages:changeAndHideHint(seconds)
    return 159, tostring(seconds)
end

function Messages:waitChangeAndHideHint(seconds)
    return 160, tostring(seconds)
end

function Messages:changeActorByNoStart()
    return 161
end

function Messages:changeActorByNoTimes(times)
    return 162, tostring(times)
end

function Messages:changeActorByNoHide()
    return 163
end

function Messages:msgLastModelName(name)
    return 164, "[" .. TextFormat:getTipType(name) .. "]"
end

function Messages:findTrue(hide, seek)
    return 1039005, TextFormat.colorGreen .. "[" .. TextFormat:getTipType(hide) .. "]" .. TextFormat.argsSplit ..
            TextFormat.colorRed .. "[" .. TextFormat:getTipType(seek) .. "]"
end

function Messages:finded()
    return 20003
end

function Messages:lastHide(num)
    return 20004, tonumber(num)
end

function Messages:findFalseLast45Second()
    return 20050
end

function Messages:last45Second()
    return 1039003
end

function Messages:goStartGame()
    return 1039002
end

function Messages:msgDontBuyGoodsByWrongRole()
    return 1039006
end

return Messages