---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Yanzhuolin.
--- DateTime: 2019/10/24 11:40
---

GameTower = class("GameTower", BaseTower)

function GameTower:ctor(pos, config, userId, facePos, processId)
    self.processId = processId
    self.seed = tostring(os.time()):reverse():sub(1, 6)
    self:setRandom(self.seed)
    self:onCreate(pos, config, userId, facePos)
    ManagerPacketSender:sendTowerCreate(self.entityId, pos, config, userId, self.seed)

    local process = ProcessManager:getProcessByProcessId(self.processId)
    if process then
        process.bulletCountPerSecond = process.bulletCountPerSecond + self.config.bulletCountPerSecond
    end
end

function GameTower:attack(targets, ejectionsCount)
    self.super.attack(self, targets, ejectionsCount)
    local process = ProcessManager:getProcessByProcessId(self.processId)
    if process and process.needSyn then
        --同步逻辑
        local targetIds = {}
        for _, target in pairs(targets) do
            table.insert(targetIds, target.entityId)
        end
        local builder = DataBuilder.new()
        builder:addParam("towerId", self.entityId)
        builder:addParam("targetIds", table.concat(targetIds, ","))
        process:broadCastPacket("TowerAttack", builder:getListData())
    end
end

function GameTower:ejectionsAttack(target, preTarget, ejectionsCount, hadAttackList)
    self.super.ejectionsAttack(self, target, preTarget, ejectionsCount, hadAttackList)
    local process = ProcessManager:getProcessByProcessId(self.processId)
    if process and process.needSyn then
        --同步逻辑
        local builder = DataBuilder.new()
        builder:addParam("towerId", self.entityId)
        builder:addParam("targetId", target.entityId)
        builder:addParam("preTargetId", preTarget.entityId)
        process:broadCastPacket("TowerEjections", builder:getListData())
    end
end

function GameTower:onSell(userId)
    if self.entityId == 0 or self.userId ~= tostring(userId) then
        return
    end

    local player = PlayerManager:getPlayerByUserId(self.userId)
    player.Wallet:addMoney(Define.Money.GameGold, self.config.SellPrice)
    HostApi.sendPlaySound(player.rakssid, self.config.SellSound)
    local process = ProcessManager:getProcessByProcessId(player.processId)
    ReportUtil.reportPlayerSellTower(player, self.config.Id, process.checkPointConfig.id, process.roundNum)
    self:onDie()
end

function GameTower:onDie()
    local player = PlayerManager:getPlayerByUserId(self.userId)
    if player then
        ---TODO 后续需要检查一下逻辑 onDestroy-->resetGrid-->onDie @yanzhuolin
        local formulaList = player.formulaList["Start" .. self.config.StarLevel] or {}
        for key, v in pairs(formulaList) do
            if self.entityId == v.entityId then
                table.remove(formulaList, key)
                break
            end
        end
    end
    ManagerPacketSender:sendTowerDead(self.entityId, self.userId)
    self.super.onDie(self)
    local process = ProcessManager:getProcessByProcessId(self.processId)
    if process then
        process.bulletCountPerSecond = process.bulletCountPerSecond - self.config.bulletCountPerSecond
    end
end

function GameTower:setLocked(userId, isLocked)
    if self.entityId == 0 or tostring(self.userId) ~= tostring(userId) then
        return
    end
    local player = PlayerManager:getPlayerByUserId(self.userId)
    if not player or isLocked == self.isLocked then
        return
    end
    self.isLocked = isLocked
    if player.formulaList["Start" .. self.config.StarLevel] == nil then
        player.formulaList["Start" .. self.config.StarLevel] = {}
    end
    if isLocked then
        for i, v in pairs(player.formulaList["Start" .. self.config.StarLevel]) do
            if self.entityId == v.entityId then
                table.remove(player.formulaList["Start" .. self.config.StarLevel], i)
                ReportUtil.reportPlayerLockTower(player, self.config.Id)
                break
            end
        end
    else
        ReportUtil.reportPlayerUnlockTower(player, self.config.Id)
        table.insert(player.formulaList["Start" .. self.config.StarLevel], self)
        player:checkTowerFormulaByStarLevel(self.config.StarLevel)
    end
end

function GameTower:syncTowerToAudience(player)
    ManagerPacketSender:syncExistingTower(player.rakssid, self.entityId, self.pos, self.config, self.userId, self.seed)
end