---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Yanzhuolin.
--- DateTime: 2019/4/15 14:51
---

GameSignIn = {}
GameSignIn.Status = {
    UN_RECEIVED = 0,
    ABLE_RECEIVED = 1,
    HAVE_RECEIVED = 2
}

function GameSignIn:initSignInData(player)
    if player.signIn_dayKey == 0 then
        --mean Available for collection
        return
    end
    --change to next SignIn
    local todayKey = DateUtil.getYearDay()
    if todayKey ~= player.signIn_dayKey then
        local nextConfig = SignInConfig:getNextSignInConfig(player.signIn_id)
        if not nextConfig then
            return
        end
        player.signIn_id = nextConfig.Id
        player.signIn_dayKey = 0
    end
end

function GameSignIn:sendToClient(player)
    local curId, status = self:getSignInStatus(player)
    local config = SignInConfig:getConfigById(curId)
    if not config then
        return
    end
    local data = {}
    data.StartOrder = config.ShowFrom
    data.NowOrder = config.Order
    data.Status = status
    if status == self.Status.ABLE_RECEIVED then
        GamePacketSender:sendPixelGunSignInData(player.rakssid, json.encode(data))
    end
end

function GameSignIn:getSignInStatus(player)
    if player.signIn_dayKey == 0 then
        return player.signIn_id, self.Status.ABLE_RECEIVED
    end

    local todayId = DateUtil.getYearDay()
    if todayId == player.signIn_dayKey then
        return player.signIn_id, self.Status.HAVE_RECEIVED
    end
    return player.signIn_id, self.Status.UN_RECEIVED
end

function GameSignIn:receiveSignInReward(player, id)
    local curId, status = self:getSignInStatus(player)
    if id ~= curId then
        return
    end
    if status ~= self.Status.ABLE_RECEIVED then
        return
    end
    local config = SignInConfig:getConfigById(id)
    if not config then
        return
    end
    ReportUtil:reportSignIn(player, id)
    local reward = RewardConfig:getRewardById(config.RewardId)
    local rewardId = GameReward:onPlayerGetReward(player, reward)
    if rewardId then
        player.signIn_dayKey = DateUtil.getYearDay()
        GamePacketSender:sendPixelGunRewardResult(player.rakssid, rewardId)
    end
end

return GameSignIn