---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/1/10 0010 17:52
---
require "skill.BaseSkill"

LandmineSkill = class("LandmineSkill", BaseSkill)
LandmineSkill.AttributeType = {
    AddArea = "6101",
    Duration = "6102",
    Damage = "6103"
}

function LandmineSkill:onInitAttributeFinish()
    self.isBoom = false
    self.entityId = 0
    local area = self:getAttributeById(LandmineSkill.AttributeType.AddArea) / 2
    self.length = self.length + area
    self.width = self.width + area
    self.height = self.height + area
    self.duration = self.duration + self:getAttributeById(LandmineSkill.AttributeType.Duration)
    self.damage = self.damage + self:getAttributeById(LandmineSkill.AttributeType.Damage)
end

function LandmineSkill:createSkillEffect(name, time)
    self.entityId = EngineWorld:addEntityItem(self.itemId, 0, 0, self.duration, self.initPos)
end

function LandmineSkill:onPlayerEffected(player)
    local creator = self:getCreator()
    if not creator then
        return
    end
    player.onSkillDamageUid = creator.userId
    local damage = player:subDefense(self.damage)
    player:subHealth(damage)
    player.onSkillDamageUid = 0
    if self.isBoom == false then
        self:onLandmineBoom(player)
    end
end

function LandmineSkill:onLandmineBoom(player)
    self.isBoom = true
    EngineWorld:addSimpleEffect("explosion.effect", self.initPos, player:getYaw(), 1000)
    self:onRemove()
end

function LandmineSkill:onDestroy()
    if self.entityId ~= 0 then
        EngineWorld:removeEntity(self.entityId)
        self.entityId = 0
    end
end

return LandmineSkill