---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaojianglaile.
--- DateTime: 2020/4/8 15:07
---
local BtTrees = {}

local BtTreeHelper = {}
function BtTreeHelper.callFunction(name, treeId)
    local tree = BtTrees[tostring(treeId)]
    if treeId == tree.watchTreeId then
        print(name, treeId)
    end
    if not tree then
        LogUtil.log(string.format("[BtTree] call function failed, tree is nil. function name=%s, treeId=%d", name, treeId), LogUtil.LogLevel.Error)
        return 0
    end
    local func = tree[name]
    if type(func) ~= "function" then
        LogUtil.log(string.format("[BtTree] call function failed, function is not exist. function name=%s, treeId=%d", name, treeId), LogUtil.LogLevel.Error)
        return 0
    end
    local result = func(tree)
    if result == nil then
        result = Define.BtStatus.FAILURE
        LogUtil.log(string.format("[BtTree] call function failed, result is nil. value name=%s, treeId=%d", name, treeId), LogUtil.LogLevel.Error)
    end
    return result
end

function BtTreeHelper.callValue(name, treeId)
    local tree = BtTrees[tostring(treeId)]
    if treeId == tree.watchTreeId then
        print(name, treeId)
    end
    if not tree then
        LogUtil.log(string.format("[BtTree] call value failed, tree is nil. value name=%s, treeId=%d", name, treeId), LogUtil.LogLevel.Error)
        return 0
    end
    local value = tree[name]
    if value == nil then
        LogUtil.log(string.format("[BtTree] call value failed, value is not exist. value name=%s, treeId=%d", name, treeId), LogUtil.LogLevel.Error)
        return 0
    end
    return value
end

BaseBtTree = class("BaseBtTree", EventObservable)

function BaseBtTree:ctor()

end

---初始化行为树
---@param btTreeName string 行为数名称
---@param updateInterval number 行为数执行时间间隔
function BaseBtTree:initBtTree(btTreeName, updateInterval)
    if #btTreeName == 0 then
        return
    end
    updateInterval = updateInterval or 0.5
    self:removeBtTree()
    self.treeId = BtTreeController.Instance():addBtTree(btTreeName, BtTreeHelper, updateInterval)
    BtTrees[tostring(self.treeId)] = self
end

---删除行为树
function BaseBtTree:removeBtTree()
    if self.treeId and self.treeId ~= 0 then
        BtTreeController.Instance():removeBtTree(self.treeId)
        BtTrees[tostring(self.treeId)] = nil
    end
end