---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaolai.
--- DateTime: 2019/7/1 15:09
---

ProductResourceConfig = {}
ProductResourceConfig.items = {}


function ProductResourceConfig:init(config)
    self:initProductResource(config)
end

function ProductResourceConfig:initProductResource(config)
    for k, v in pairs(config) do
        local item = {}
        item.id = tonumber(v.id)
        item.itemIdList = {}
        local itemIdList = StringUtil.split(tostring(v.itemIdList), "#")
        if itemIdList then
            for i = 1, #itemIdList do
                table.insert(item.itemIdList, tonumber(itemIdList[i]))
            end
        end

        item.lifeList = {}
        local lifeList = StringUtil.split(tostring(v.lifeList), "#")
        if lifeList then
            for i = 1, #lifeList do
                table.insert(item.lifeList, tonumber(lifeList[i]))
            end
        end

        item.timeList = {}
        local timeList = StringUtil.split(tostring(v.timeList), "#")
        if timeList then
            for i = 1, #timeList do
                table.insert(item.timeList, tonumber(timeList[i]))
            end
        end

        item.numList = {}
        local numList = StringUtil.split(tostring(v.numList), "#")
        if numList then
            for i = 1, #numList do
                table.insert(item.numList, tonumber(numList[i]))
            end
        end

        item.outputList = {}
        local outputList = StringUtil.split(tostring(v.outputList), "#")
        if outputList then
            for i = 1, #outputList do
                table.insert(item.outputList, tonumber(outputList[i]))
            end
        end

        item.maxNumList = {}
        local maxNumList = StringUtil.split(tostring(v.maxNumList), "#")
        if maxNumList then
            for i = 1, #maxNumList do
                table.insert(item.maxNumList, tonumber(maxNumList[i]))
            end
        end

        item.highestNum = tonumber(v.highestNum)

        self.items[item.id] = item
    end

    table.sort(self.items, function(a, b)
        return a.id < b.id
    end)
end

function ProductResourceConfig:getItem(id)
    local  info = {}
    for k, v in pairs(self.items) do
        if v.id == id then
            for i = 1, #v.itemIdList do
                local data = {}
                data.itemId = v.itemIdList[i]
                data.life = v.lifeList[i]
                data.time = v.timeList[i]
                data.num = v.numList[i]
                table.insert(info, data)
            end
        end
    end

    return info
end

function ProductResourceConfig:getItemIdAndOutput(Id)
    local  info = {}
    for k, v in pairs(self.items) do
        if v.id == Id then
            for i = 1, #v.outputList do
                local data = {}
                data.itemId = v.itemIdList[i]
                data.num = v.outputList[i]
                table.insert(info, data)
            end
        end
    end
    return info
end

function ProductResourceConfig:getHighestNumById(Id)
    for k, v in pairs(self.items) do
        if v.id == Id then
            --print("000 getHighestNumById " .. " level is " .. Id .. " hightnum is " .. v.highestNum)
           return v.highestNum
        end
    end
    return 1000
end

function ProductResourceConfig:getLimitNumByRatio(id , itemId)
    local MaxNum = 0
    local CurNum = 0
    local limitNum = 0
    for k, v in pairs(self.items) do
        if v.id == id then
            for i = 1, #v.maxNumList do
                if itemId == v.itemIdList[i] then
                    CurNum = v.maxNumList[i]
                end
                MaxNum = MaxNum + v.maxNumList[i]
            end
        end
    end
    if MaxNum > 0 then
        limitNum = math.ceil((CurNum / MaxNum) * ProductResourceConfig:getHighestNumById(id))
    end
    --print("111getLimitNumByRatio " .. "level is " .. id .. " limitnum " .. limitNum)
    return limitNum
end



return ProductResourceConfig