---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/1/12 0012 13:05
---
require "property.BaseProperty"

AddJumpProperty = class("AddJumpProperty", BaseProperty)

function AddJumpProperty:onPlayerEquip(player)
    player:addEffect(PotionID.JUMP, self.config.duration, self.config.value)
end

function AddJumpProperty:onPlayerUnload(player)
    player:removeEffect(PotionID.JUMP)
end

return AddJumpProperty