---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/1/12 0012 13:00
---
require "property.BaseProperty"

FireProperty = class("FireProperty", BaseProperty)

function FireProperty:onPlayerUsed(player, target, damage)
    target:setOnFire(self.config.duration)
    target.onFireDamageUid = player.userId
end

return FireProperty