---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/10/9 16:05
---
GamePacketHandler = {}

function GamePacketHandler:init()
    C2SAdDisplay:registerCallBack(self.onReportAdDisplay)
end

function GamePacketHandler.onReportAdDisplay(userId, data)
    local player = PlayerManager:getPlayerByUserId(userId)
    if player then
        ReportUtil:reportAdDisplay(player, "AdDisplay1")
    end
    --print("||||||||||||||||||||||||||||||||||")
end

return GamePacketHandler