---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 98632.
--- DateTime: 2019/8/20 14:50
---
---
---


GamePacketSender = {}

function GamePacketSender:sendAppShopVideoData(rakssid, data)
    PacketSender:sendServerCommonData(rakssid, "AppShopData", "VideoAd_HASHall", data)
end

return GamePacketSender