---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/9/8 16:46
---
BanCureBuff = class("BanCureBuff", BaseBuff)

function BanCureBuff:onCreate()
    local player = PlayerManager:getPlayerByUserId(self.ownerId)
    player.banCureBuff = true
end

function BanCureBuff:onTimesUp()
    local player = PlayerManager:getPlayerByUserId(self.ownerId)
    player.banCureBuff = false
end

return BanCureBuff