---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/7/15 15:50
---

require "settlement.SettlementBase"
require "config.GameConfig"

ChickenSettlement = class("ChickenSettlement", SettlementBase)
--  第一个参数 参与排序的玩家  第二个是延时时间 第三个参数表示游戏开始时间
function ChickenSettlement:SendSettlementResult(player, rank, time, isWin)
    if isWin then
        player.outCome = GameResult.WIN
    else
        player.outCome = GameResult.LOSE
    end

    local players = {}
    table.insert(players, player)
    LuaTimer:schedule(function()
        self:doReward(players, 0, rank)
        self:doReport(players)
    end, time * 1000)
end

function ChickenSettlement:doGameReward(players, rank)
    local data = {}
    local player = players[1]
    local image = "set:pixelgungameresult.json image:rank" .. (player.honorId + 1)
    data = {
        Rank = rank,
        Total = GameMatch.Process.playerTotalNum,
        Honor = image,
        Name = player.name,
        Kill = tostring(player.kills),
        Win = (rank == 1)
    }

    local reward_list = {}
    reward_list = self:getPlayerRewardData(player, rank, rank == 1)
    data.LoginNum = tostring(player.gold)
    data.Gold = tostring(reward_list.gold)
    data.Key = tostring(reward_list.key)
    data.Exp = tostring(reward_list.exp)
    data.HonorNum = tostring(reward_list.honor)
    data.Show_Ad = (player.advert_record.GameAdTimes < GameConfig.maxGameAdTimes)
    GamePacketSender:sendPixelGunChickenResultData(player.rakssid, json.encode(data))
    player:showLvUpReward()
end

function ChickenSettlement:getPlayerRewardData(player, rank, isWin)
    local data = {}
    local reward
    reward = AwardConfig:getLoseByRank(rank)
    local c_reward = player:getRewardInfo(reward, isWin)
        data.exp = c_reward.exp
        data.gold = c_reward.money
        data.key = c_reward.yaoshi
        data.honor = c_reward.integral
    return data
end