---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/9/19 15:11
---

GameGunsForgeNpc = class()

function GameGunsForgeNpc:ctor(config)
    self.vec3 = VectorUtil.newVector3(config.x, config.y, config.z)
    self.yaw = config.yaw
    self.name = config.name
    self.actor = config.actor
    self:onCreate()
end

function GameGunsForgeNpc:onCreate()
    local entityId = EngineWorld:addSessionNpc(self.vec3, self.yaw, 6, self.actor, function(entity)
        entity:setNameLang(self.name or "")
        entity:setEffectName("flag_halo_1.effect")
    end)
    self.entityId = entityId
end

return GameGunsForgeNpc