---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/8/9 18:10
---
local CGameTimeTask = class("GameTimeTask", ITask)

function CGameTimeTask:onCreate()
end

function CGameTimeTask:onTick(ticks)
    ProcessManager:onTick(ticks)
    HallManager:tryQueueEnterRoom()
    --TODO
end


function CGameTimeTask:Stop()
    SecTimer.stopTimer(self.timer)
end

GameTimeTask = CGameTimeTask.new(1)

return GameTimeTask