---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/3/19 0019 15:08
---
GameAnalyticsCache = {}
GameAnalyticsCache.ClientInfoCaches = {}
GameAnalyticsCache.EventCaches = {}

function GameAnalyticsCache:addClientInfo(userId, clientInfo)
    local info = {}
    local success = true
    local function getDefaultInfo()
        return {
            device = "unknown",
            user_id = tostring(userId),
            os_version = "android 4.4.4",
            manufacturer = "lenovo",
            platform = "android",
            session_num = 1,
            version_code = "1",
            package_name = "com.sandboxol.blockymods",
        }
    end
    if #clientInfo == 0 then
        info = getDefaultInfo()
    else
        HostApi.log("[ClientInfo][" .. tostring(userId) .. "]:" .. clientInfo)
        success, info = pcall(json.decode, clientInfo)
        if not success then
            info = getDefaultInfo()
        end
    end
    info.v = 2
    info.sdk_version = "rest api v2"
    local uuid = require "base.util.uuid"
    uuid.randomseed(os.time())
    info.session_id = uuid()
    info.custom_01 = GameAnalytics.Custom01
    info.custom_02 = GameAnalytics.Custom02
    self.ClientInfoCaches[tostring(userId)] = info
    GameAnalytics:sessionStart(userId)
end

function GameAnalyticsCache:getClientInfo(userId)
    return self.ClientInfoCaches[tostring(userId)]
end

function GameAnalyticsCache:removeCache(userId)
    self:forceSendEvents(userId)
    self.ClientInfoCaches[tostring(userId)] = nil
    self.EventCaches[tostring(userId)] = nil
end

function GameAnalyticsCache:addEventCache(userId, event)
    local info = self.ClientInfoCaches[tostring(userId)]
    if not info then
        return
    end
    for key, value in pairs(info) do
        event[key] = value
    end
    local cache = self.EventCaches[tostring(userId)]
    if not cache then
        cache = {}
        cache.time = os.time()
        cache.events = {}
        self.EventCaches[tostring(userId)] = cache
    end
    event.client_ts = GameAnalytics:getClientTs()
    table.insert(cache.events, event)
end

function GameAnalyticsCache:trySendEvents()
    local curTime = os.time()
    for userId, cache in pairs(self.EventCaches) do
        if curTime - cache.time >= 120 or #cache.events >= 20 then
            GameAnalytics:sendEvents(userId, cache.events)
            cache.time = curTime
            cache.events = {}
        end
    end
end

function GameAnalyticsCache:forceSendEvents(userId)
    local cache = self.EventCaches[tostring(userId)]
    if not cache then
        return
    end
    GameAnalytics:sendEvents(userId, cache.events)
    cache.events = {}
end

return GameAnalyticsCache