---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/3/19 0019 9:56
---
GameAnalytics = {}
GameAnalytics.Enable = false
GameAnalytics.OffsetTs = 0
GameAnalytics.Custom01 = "G1"
GameAnalytics.Custom02 = "Test"
GameAnalytics.RetryTimes = 3

local function getCoinName(coinId)
    coinId = coinId or 0
    if coinId == 1 then
        return "Cube"
    end
    if coinId == 2 then
        return "Gold"
    end
    if coinId == 3 then
        return "Money"
    end
    if coinId == 4 then
        return "GameCustom"
    end
    return "NoDefine"
end

function GameAnalytics:init(enable, serverTs, custom1, custom2)
    self.Enable = enable
    self.OffsetTs = os.time() - tonumber(tostring(serverTs))
    self.Custom01 = custom1
    self.Custom02 = custom2
end

function GameAnalytics:isEnable()
    return self.Enable
end

function GameAnalytics:getClientTs()
    return os.time() - self.OffsetTs
end

function GameAnalytics:sendEvents(userId, events)
    if #events == 0 then
        return
    end
    local player = PlayerManager:getPlayerByUserId(userId)
    if not player then
        return
    end
    GameAnalyticsRequest.asyncEvents(player.rakssid, json.encode(events), GameAnalytics.RetryTimes)
end

---As session is the concept of a user spending a period of time focused on a game.
---The user event acts like a session start. It should always be the
---first event in the first batch sent to the collectors and added each time a session starts.
---@param userId number userId [player userId]
function GameAnalytics:sessionStart(userId)
    if not GameAnalytics:isEnable() then
        return
    end
    GameAnalyticsCache:addEventCache(userId, {
        category = "user"
    })
end

---Whenever a session is determined to be over the code should always attempt
---to add a session end event and submit all pending events immediately.
---Only one session end event per session should be activated.
---@param userId number userId [player userId]
---@param length number length [player game time, eg: 120 (second)]
function GameAnalytics:sessionEnd(userId, length)
    if not GameAnalytics:isEnable() then
        return
    end
    GameAnalyticsCache:addEventCache(userId, {
        category = "session_end",
        length = length
    })
end

---Resource events are for tracking the flow of virtual currency registering the
---amounts users are spending (sink) and receiving (source) for a specified virtual currency.
---@param userId number userId [player userId]
---@param action string eventId [event id, eg: BuyGun]
---@param itemId string_or_number itemId [item id, eg: 103]
---@param coinId number itemId [coinId, eg: 1|2|3|4]
---@param amount number amount [currency amount eg: 100]
---eventId structure
---pattern:^Sink:[A-Za-z]{1,64}:[A-Za-z0-9\\s\\-_\\.\\(\\)\\!\\?]{1,64}:[A-Za-z0-9\\s\\-_\\.\\(\\)\\!\\?]{1,64}$
function GameAnalytics:resourceSink(userId, action, itemId, coinId, amount)
    if not GameAnalytics:isEnable() then
        return
    end
    local coin = getCoinName(coinId) .. ":"
    action = (action or "test") .. ":"
    itemId = itemId or "1"
    local eventId = "Sink:" .. coin .. action .. itemId
    GameAnalyticsCache:addEventCache(userId, {
        category = "resource",
        event_id = eventId,
        amount = amount
    })
end

---Resource events are for tracking the flow of virtual currency registering the
---amounts users are spending (sink) and receiving (source) for a specified virtual currency.
---@param userId number userId [player userId]
---@param action string eventId [event id, eg: BuyGun]
---@param itemId string_or_number itemId [item id, eg: 103]
---@param coinId number itemId [coinId, eg: 1|2|3|4]
---@param amount number amount [currency amount eg: 100]
---eventId structure
---pattern:^Source:[A-Za-z]{1,64}:[A-Za-z0-9\\s\\-_\\.\\(\\)\\!\\?]{1,64}:[A-Za-z0-9\\s\\-_\\.\\(\\)\\!\\?]{1,64}$
function GameAnalytics:resourceSource(userId, action, itemId, coinId, amount)
    if not GameAnalytics:isEnable() then
        return
    end
    local coin = getCoinName(coinId) .. ":"
    action = (action or "test") .. ":"
    itemId = itemId or "1"
    local eventId = "Source:" .. coin .. action .. itemId
    GameAnalyticsCache:addEventCache(userId, {
        category = "resource",
        event_id = eventId,
        amount = amount
    })
end

---Every game is unique! Therefore it varies what information is needed to track
---for each game. Some needed events might not be covered by our other event types
---and the design event is available for creating a custom metric using an event id hierarchy.
---@param userId number userId [player userId]
---@param value number value [Optional value. float]
---@param parts table parts [eg {"BreakBlock", BlockId, ...}]
---eventId structure
---A 1-5 part event id.
---[part1]:[part2]:[part3]:[part4]:[part5]
---pattern:^[A-Za-z0-9\\s\\-_\\.\\(\\)\\!\\?]{1,64}(:[A-Za-z0-9\\s\\-_\\.\\(\\)\\!\\?]{1,64}){0,4}$
function GameAnalytics:design(userId, value, parts)
    if not GameAnalytics:isEnable() then
        return
    end
    value = value or 0
    parts = parts or {}
    local eventId = table.concat(parts, ":")
    if #eventId <= 1 then
        return
    end
    GameAnalyticsCache:addEventCache(userId, {
        category = "design",
        event_id = eventId,
        value = value
    })
end

return GameAnalytics