---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/6/1 13:20
---
DoubleExpPrivilege = {}

function DoubleExpPrivilege:init(config)
    self.id = tonumber(config.Id)
end

function DoubleExpPrivilege:onPlayerBuy(player)

end

function DoubleExpPrivilege:onPlayerReward(player)
    return Privilege.checkHavePrivilege(player, self.id)
end