---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Yanzhuolin.
--- DateTime: 2019/10/25 18:02
---
GameWallet = class("GameWallet", BaseWallet)

function GameWallet:setMoneyCount(coinId, count)
    self.MoneyCache[coinId] = count
    self:updateWallet(coinId)
end

function GameWallet:costMoney(coinId, count)
    if coinId == 1 then

    elseif coinId == 2 then

    elseif coinId == 3 then

    elseif coinId > 3 then
        local nowCount = self:getMoneyByCoinId(coinId)
        if nowCount == 9999999999 then
            nowCount = 0
        end
        if nowCount - count >= 0 then
            self:setMoneyCount(coinId, nowCount - count)
            return true
        end
    end
    return false
end

function GameWallet:addMoney(coinId, count)
    if coinId <= 3 then
        return false
    end
    self.MoneyCache[coinId] = self.MoneyCache[coinId] or 0
    local nowCount = self:getMoneyByCoinId(coinId)
    if nowCount == 9999999999 then
        nowCount = 0
    end
    self:setMoneyCount(coinId, nowCount + count)
    return true
end

function GameWallet:updateWallet(coinId)
    local builder = DataBuilder.new()
    builder:addParam("coinId", coinId)
    builder:addParam("count", self:getMoneyByCoinId(coinId))
    PacketSender:sendLuaCommonData(self.rakssid, "UpdateWallet", builder:getListData())
end

function GameWallet:initGameMoney()
    self:setMoneyCount(Define.Money.GameGold, 0)
    return true
end

