---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/9/17 9:47
---

FlipBackConfig = {}
FlipBackConfig.back = {}

function FlipBackConfig:initConfig(config)
    for i, v in pairs(config) do
        local item = {}
        item.id = tonumber(v.id)
        local x = tonumber(v.pos[1])
        local y = tonumber(v.pos[2])
        local z = tonumber(v.pos[3])
        item.pos = VectorUtil.newVector3(x , y , z)
        self.back[item.id] = item
    end
end






return FlipBackConfig