---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaolai.
--- DateTime: 2019/6/17 12:25
---

IslandAreaConfig = {}
IslandAreaConfig.areas = {}

function IslandAreaConfig:init(config)
    for i, v in pairs(config) do
        local item = {}
        item.id = tonumber(v.id)
        item.area = tostring(v.area)
        item.radius = tonumber(v.radius)
        item.price = tonumber(v.price)
        item.tip = tostring(v.tip)
        self.areas[i] = item
    end
end

function IslandAreaConfig:getIdByArea(area)
    for i, k in pairs(self.areas) do
        if k.area == area then
            return k.id
        end
    end
    return
end

return IslandAreaConfig