---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/9/17 0017 15:34
---
local PayType = {
    Diamonds = 1,
    Golds = 2,
    Currency = 3,
}

local PayLockCache = {}

PayHelper = {}

local function pay(userId, type, request)
    WebService:Pay(userId, request.uniqueId, type, request.price, function(data)
        local key = tostring(request.userId) .. tostring(request.uniqueId)
        PayLockCache[key] = nil
        if not data then
            if request.failedCallback then
                request.failedCallback()
            end
            return
        end
        local player = PlayerManager:getPlayerByUserId(request.userId)
        if not player then
            ---支付成功后，玩家已退出游戏，回滚订单，不需要处理回调
            EngineUtil.disposePlatformOrder(request.userId, data.orderId, false)
            if request.failedCallback then
                request.failedCallback()
            end
            return
        end
        local wallet = player.entityPlayerMP:getWallet()
        wallet.m_diamondBlues = data.diamonds
        wallet.m_diamondGolds = data.gDiamonds
        wallet:setGolds(data.golds)
        PacketSender:sendInitMoney(player.rakssid, data.diamonds, data.gDiamonds, data.golds)
        if not request.subKey then
            ---没有绑定数据存储subKey的一律自动消耗订单
            local consume = request.successCallback(player) ---回调处理，可设置返回值，返回false代表处理(添加物品等)失败，回滚订单，默认是true
            if consume == nil then
                consume = true
            end
            EngineUtil.disposePlatformOrder(request.userId, data.orderId, consume)
            return
        end
        local consume = request.successCallback(player) ---回调处理，可设置返回值，返回false代表处理(添加物品等)失败，回滚订单，默认是true
        if consume == nil then
            consume = true
        end
        if not consume then
            ---回调处理失败，回滚订单
            EngineUtil.disposePlatformOrder(request.userId, data.orderId, false)
        else
            ---保存至缓存，等待数据存储成功后再消耗订单，存储失败会回滚订单
            OrderManager.pushOrderCache({
                userId = tostring(request.userId),
                subKey = tostring(request.subKey),
                orderId = data.orderId
            })
        end
    end)
end

---支付魔方/钻石方法
---@userId 玩家Id
---@uniqueId 商品Id
---@diamonds 魔方/钻石数量
---@successCallback 支付成功回调函数
---@failedCallback 支付失败回调函数
---@subKey 绑定的数据存储subKey，设置后会自动检测数据存储成功后消耗订单
function PayHelper.payDiamonds(userId, uniqueId, diamonds, successCallback, failedCallback, subKey)
    local player = PlayerManager:getPlayerByUserId(userId)
    if not player then
        return
    end
    if player.isKickOut then
        return
    end
    if player:getDiamond() < diamonds then
        return
    end
    local request = {
        userId = userId,
        uniqueId = uniqueId,
        price = diamonds,
        subKey = subKey,
        successCallback = successCallback,
        failedCallback = failedCallback
    }
    pay(userId, PayType.Diamonds, request)
end

---支付魔方/钻石方法(同步方法，带事务机制，购买同一种商品会锁住该商品，等待http返回后才可以再次购买该商品)
---@userId 玩家Id
---@uniqueId 商品Id
---@diamonds 魔方/钻石数量
---@successCallback 支付成功回调函数
---@failedCallback 支付失败回调函数
---@subKey 绑定的数据存储subKey，设置后会自动检测数据存储成功后消耗订单
function PayHelper.payDiamondsSync(userId, uniqueId, diamonds, successCallback, failedCallback, subKey)
    local key = tostring(userId) .. tostring(uniqueId)
    if PayLockCache[key] then
        return
    end
    PayLockCache[key] = true
    PayHelper.payDiamonds(userId, uniqueId, diamonds, successCallback, failedCallback, subKey)
end

---支付金币方法
---@userId 玩家Id
---@uniqueId 商品Id
---@golds 金币数量
---@successCallback 支付成功回调函数
---@failedCallback 支付失败回调函数
---@subKey 绑定的数据存储subKey，设置后会自动检测数据存储成功后消耗订单
function PayHelper.payGolds(userId, uniqueId, golds, successCallback, failedCallback, subKey)
    local player = PlayerManager:getPlayerByUserId(userId)
    if not player then
        return
    end
    if player.isKickOut then
        return
    end
    if player:getGold() < golds then
        return
    end
    local request = {
        userId = userId,
        uniqueId = uniqueId,
        price = golds,
        subKey = subKey,
        successCallback = successCallback,
        failedCallback = failedCallback
    }
    pay(userId, PayType.Golds, request)
end

---支付金币方法(同步方法，带事务机制，购买同一种商品会锁住该商品，等待http返回后才可以再次购买该商品)
---@userId 玩家Id
---@uniqueId 商品Id
---@golds 金币数量
---@successCallback 支付成功回调函数
---@failedCallback 支付失败回调函数
---@subKey 绑定的数据存储subKey，设置后会自动检测数据存储成功后消耗订单
function PayHelper.payGoldsSync(userId, uniqueId, golds, successCallback, failedCallback, subKey)
    local key = tostring(userId) .. tostring(uniqueId)
    if PayLockCache[key] then
        return
    end
    PayLockCache[key] = true
    PayHelper.payGolds(userId, uniqueId, golds, successCallback, failedCallback, subKey)
end

---支付绿钞方法
---@userId 玩家
---@golds 绿钞数量
---@successCallback 支付成功回调函数
function PayHelper.payCurrency(player, price, successCallback)
    if player:getCurrency() < price then
        return
    end
    player:subCurrency(price)
    if successCallback then
        successCallback()
    end
end

function PayHelper.payMoney(player, uniqueId, coinId, price, successCallback, failedCallback, subKey)
    if coinId == PayType.Diamonds then
        PayHelper.payDiamondsSync(player.userId, uniqueId, price, successCallback, failedCallback, subKey)
        return
    end
    if coinId == PayType.Golds then
        PayHelper.payGoldsSync(player.userId, uniqueId, price, successCallback, failedCallback, subKey)
        return
    end
    if coinId == PayType.Currency then
        PayHelper.payCurrency(player, price, successCallback)
        return
    end
end