---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2019/8/16 18:05
---

require "packet.GamePacketSender"

VideoAdHelper = {}

function VideoAdHelper:tryShowSkyRoyaleRespawnVideoAd(player)
    if player.respawnAdTimes < GameConfig.respawnAdMaxTimes then
        local params = {
            isShow = true
        }
        local data = DataBuilder.new():fromTable(params):getData()
        GamePacketSender:sendShowSkyRoyaleRespawnAd(player.rakssid, data)
    end
end

function VideoAdHelper:doRespawnVideoAdReward(player)
    player.respawnAdTimes = player.respawnAdTimes + 1
    RespawnHelper.sendRespawnCountdown(player, 1)
    MsgSender.sendMsg(IMessages:msgRespawn(player:getDisplayName()))
    GameAnalytics:design(player.userId)
    RespawnManager:removeSchedule(player.userId)
    HostApi.broadCastPlayerLifeStatus(player.userId, player.isLife)
end

return VideoAdHelper
