---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/10/8 15:05
---
require "data.Box"

BoxManager = {}
BoxManager.Boxes = {}
BoxManager.Stage = 0

function BoxManager:initBox()
    local config = BoxConfig:getBoxes()
    if config == nil then
        return
    end
    for id, box in pairs(config) do
        self.Boxes[VectorUtil.hashVector3(box.pos)] = Box.new(box)
    end
end

function BoxManager:refreshBoxItem()
    self.Stage = self.Stage + 1
    for id, box in pairs(self.Boxes) do
        box:refreshBoxItem()
    end
end

function BoxManager:setInv(vec3, inv)
    local box = self.Boxes[VectorUtil.hashVector3(vec3)]
    if box == nil then
        return
    end
    box:setInv(inv)
end

return BoxManager