---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/11/1 0001 15:08
---
require "entity.GameMount"
require "entity.GameEnderDragon"
require "entity.GameWithered"

local Mounts = {}

EntityManager = {}

function EntityManager:addMount(entity)
    Mounts[tostring(entity.entityId)] = entity
end

function EntityManager:getMount(entityId)
    return Mounts[tostring(entityId)]
end

function EntityManager:removeMount(entity)
    Mounts[tostring(entity.entityId)] = nil
end

function EntityManager:onTick()
    for _, entity in pairs(Mounts) do
        entity:onTick()
    end
end