---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2020/1/18 11:12
---
EntityRankManager = {}

local titleText = { "rank", "userName", "killNum", "integral", "stage" }
local col_num = 10

--local function createTitle(rakssid, rankId)
--    --WallTextUtil.addWallText(rakssid, "rank_title" .. rankId, tonumber(rankId .. "9991"))
--    --
--    --local start = tonumber(rankId .. "9001")
--    --for i = start, start + #titleText do
--    --    WallTextUtil.addWallText(rakssid, titleText[i - start + 1], i)
--    --end
--end

--刷新倒计时
--local function createUpdateCountdown(rakssid, rankId, countdownTime)
--    WallTextUtil.addWallText(rakssid, "UpdateCountdown", tonumber(rankId .. "9901"))
--    WallTextUtil.addWallText(rakssid, tostring(countdownTime), tonumber(rankId .. "9902"))
--end

local function getCurSeasonRankData(rankId, row, col)
    local infos = SeasonRankManager.curSeasonRankData[rankId]
    if not infos then
        return ""
    end

    --table.sort(info, function(a, b)
    --    return a.rank < b.rank
    --end)

    for _, info in pairs(infos) do
        if info.rank == row then
            local index = titleText[col] or 1
            return info[index] or ""
        end
    end

    return ""
end

--local function createEntityRankById(rakssid, rankId)
--    --createTitle(rakssid, rankId)
--
--    local first = tonumber(rankId .. "0001")
--    local last = tonumber(rankId .. "0050")
--    for i = first, last do
--        local row = i % col_num
--        local col = math.floor((i - rankId * 10000) / col_num) + 1
--        local str = getCurSeasonRankData(rankId, row, col)
--        if str ~= "" then
--            WallTextUtil.addWallText(rakssid, str, i)
--        end
--    end
--end

local function createEntityRankById(rakssid, rankId)
    local infos = SeasonRankManager.curSeasonRankData[rankId]
    if not infos then
        return
    end

    for _, info in pairs(infos) do
        WallTextUtil.addRowWallText(rakssid, rankId, info, titleText)
    end
end

function EntityRankManager:createEntityRank(rakssid)
    local player = PlayerManager:getPlayerByRakssid(rakssid)
    if not player then
        return
    end

    EntityRankManager:deleteEntityRank(rakssid)

    createEntityRankById(rakssid, 1)
    createEntityRankById(rakssid, 2)
    createEntityRankById(rakssid, 3)
    createEntityRankById(rakssid, 4)

    --LogUtil.log("EntityRankManager:createEntityRank " .. tostring(rakssid))
end

function EntityRankManager:deleteEntityRank(rakssid)
    PacketSender:sendLuaCommonData(rakssid, "DeleteAllWallText", "")
end

function EntityRankManager:updateEntityRank(lv)
    for _, vPlayer in pairs(PlayerManager:getPlayers()) do
        createEntityRankById(vPlayer.rakssid, lv)
    end
end

function EntityRankManager:delayCreateEntityRank(rakssid, delayTime)
    --LuaTimer:scheduleTimer(function()
    --    EntityRankManager:createEntityRank(rakssid)
    --end, delayTime, 1)

    EntityRankManager:createEntityRank(rakssid)
end

function EntityRankManager:onTick(ticks)
    if ticks % (1 * GameMatch.tickPerSecond) ~= 0 then
        return
    end

    local countdownTime = SeasonRankManager:getCountdownTime()
    for _, vPlayer in pairs(PlayerManager:getPlayers()) do
        EntityRankManager:updateEntityRankCountdown(vPlayer.rakssid, countdownTime)
    end
end

function EntityRankManager:updateEntityRankCountdown(rakssid, countdownTime)
    --createUpdateCountdown(rakssid, 1, countdownTime)
    --createUpdateCountdown(rakssid, 2, countdownTime)
    --createUpdateCountdown(rakssid, 3, countdownTime)
    --createUpdateCountdown(rakssid, 4, countdownTime)

    GamePacketSender:SendEntityRankCountdown(rakssid, countdownTime)
end

--function EntityRankManager:updateEntityRank(lv)
--    --LogUtil.log("EntityRankManager:updateEntityRank " .. lv)
--
--    for _, vPlayer in pairs(PlayerManager:getPlayers()) do
--        createEntityRankById(vPlayer.rakssid, lv)
--    end
--end

return EntityRankManager