---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2020/1/8 18:06
---
MemoryLeakDetector = {}

local detectorSize = 10000
local logTable = {}
local debug = true

function MemoryLeakDetector:doDetector(data, info)
    if not debug then
        return
    end

    if type(data) ~= "table" then
        return
    end

    if logTable[info] then
        return
    end

    local size = TableUtil.getTableSize(data)
    if size > detectorSize then
        LogUtil.log(info .. " size:" .. tostring(size), LogUtil.LogLevel.Error)
        logTable[info] = true
    end
end

function MemoryLeakDetector:onTick(ticks)
    if ticks % (5 * GameMatch.tickPerSecond) ~= 0 then
        return
    end

    --LogUtil.log("MemoryLeakDetector:onTick")

    MemoryLeakDetector:doDetector(MonsterManager.Monsters, "MonsterManager.Monsters")
    MemoryLeakDetector:doDetector(TeamManager.teams, "TeamManager.teams")

    MemoryLeakDetector:doDetector(LSRankManager.Ranks, "LSRankManager.Ranks")

    MemoryLeakDetector:doDetector(PlayerManager.Players, "PlayerManager.Players")
    MemoryLeakDetector:doDetector(LuaTimer:getTaskList(), "LuaTimer TaskList")
end

return MemoryLeakDetector