---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/9/19 19:59
---
ForgeProbabilityConfig = {}
ForgeProbabilityConfig.probabilitys = {}

function ForgeProbabilityConfig:init(probabilitys)
    self:initForgeProbability(probabilitys)
end

function ForgeProbabilityConfig:initForgeProbability(probabilitys)
    for _, pro in pairs(probabilitys) do
        local item = {}
        item.id = pro.id
        item.gunId = pro.gunId
        item.moneyType = tonumber(pro.moneyType)
        item.type = tonumber(pro.type)
        item.value = tonumber(pro.value)
        item.weight = tonumber(pro.weight)
        self.probabilitys[#self.probabilitys + 1] = item
    end
end

function ForgeProbabilityConfig:getForgeProbability(id)
    for _, pro in pairs(self.probabilitys) do
        if pro.id == id then
            return pro
        end
    end
    return nil
end

function ForgeProbabilityConfig:getProbability()
    return self.probabilitys
end

return ForgeProbabilityConfig