---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/9/10 17:49
---
GunsConfig = {}
GunsConfig.guns = {}

function GunsConfig:init(guns)
    self:initGuns(guns)
end

function GunsConfig:initGuns(guns)
    for id, gun in pairs(guns) do
        local item = {}
        item.gunId = id
        item.itemId = tonumber(gun.itemId)
        item.name = gun.name
        item.image = gun.image
        item.desc = gun.desc
        item.type = tonumber(gun.type)
        item.forgeType = tonumber(gun.forgeType)
        item.attack = tonumber(gun.attack)
        item.range = tonumber(gun.range)
        item.speed = tonumber(gun.speed)
        item.bulletId = tonumber(gun.bulletId)
        item.maxBullet = tonumber(gun.maxBullet)
        item.recoil = tonumber(gun.recoil)
        item.sniperDistance = tonumber(gun.sniperDistance)
        item.bulletPerShoot = tonumber(gun.bulletPerShoot)
        item.bulletOffset = tonumber(gun.bulletOffset)
        item.mouseSensitivity = tonumber(gun.mouseSensitivity)
        item.price = tonumber(gun.price)
        item.maxValue = tonumber(gun.maxValue)
        self.guns[id] = item
    end
    self:prepareGuns()
end

function GunsConfig:prepareGuns()
    for i, gun in pairs(self.guns) do
        HostApi.setGunSetting(GunsConfig.newGunSetting(gun))
    end
end

function GunsConfig.newGunSetting(item)
    local setting = GunPluginSetting.new()
    setting.gunId = item.itemId
    setting.gunType = item.type
    setting.maxBulletNum = item.maxBullet
    setting.damage = item.attack
    setting.recoil = item.recoil
    setting.bulletId = item.bulletId
    setting.shootRange = item.range
    setting.cdTime = item.speed
    setting.sniperDistance = item.sniperDistance
    setting.bulletPerShoot = item.bulletPerShoot
    setting.bulletOffset = item.bulletOffset
    setting.mouseSensitivity = item.mouseSensitivity
    return setting
end

function GunsConfig:getGuns()
    return self.guns
end

function GunsConfig:getGunById(gunId)
    for i, gun in pairs(self.guns) do
        if gun.gunId == gunId then
            return gun
        end
    end
end

function GunsConfig:getGunDescById(gunId)
    for i, gun in pairs(self.guns) do
        if gun.gunId == gunId then
            return gun.desc
        end
    end
end

return GunsConfig