---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/30 14:49
---
SprayPaintConfig = {}
SprayPaintConfig.sprayPaint = {}

function SprayPaintConfig:init(sprayPaint)
    self:initSprayPaint(sprayPaint)
end

function SprayPaintConfig:initSprayPaint(sprayPaints)
    for i, sprayPaint in pairs(sprayPaints) do
        local item = {}
        item.sprayPaintId = sprayPaint.sprayPaintId
        item.itemId = tonumber(sprayPaint.itemId)
        item.initialItemId = tonumber(sprayPaint.initialItemId)
        item.name = sprayPaint.name
        item.image = sprayPaint.image
        item.desc = sprayPaint.desc
        item.type = tonumber(sprayPaint.type)
        item.attack = tonumber(sprayPaint.attack)
        item.range = tonumber(sprayPaint.range)
        item.speed = tonumber(sprayPaint.speed)
        item.bulletId = tonumber(sprayPaint.bulletId)
        item.maxBullet = tonumber(sprayPaint.maxBullet)
        item.recoil = tonumber(sprayPaint.recoil)
        item.sniperDistance = tonumber(sprayPaint.sniperDistance)
        item.bulletPerShoot = tonumber(sprayPaint.bulletPerShoot)
        item.bulletOffset = tonumber(sprayPaint.bulletOffset)
        item.mouseSensitivity = tonumber(sprayPaint.mouseSensitivity)
        item.price = tonumber(sprayPaint.price)
        table.insert(self.sprayPaint, item)
    end
    self:prepareGuns()
end

function SprayPaintConfig:prepareGuns()
    for _, gun in pairs(self.sprayPaint) do
        HostApi.setGunSetting(self:newGunSetting(gun))
    end
end

function SprayPaintConfig:newGunSetting(item)
    local setting = GunPluginSetting.new()
    setting.gunId = item.itemId
    setting.gunType = item.type
    setting.maxBulletNum = item.maxBullet
    setting.damage = item.attack
    setting.recoil = item.recoil
    setting.bulletId = item.bulletId
    setting.shootRange = item.range
    setting.cdTime = item.speed
    setting.sniperDistance = item.sniperDistance
    setting.bulletPerShoot = item.bulletPerShoot
    setting.bulletOffset = item.bulletOffset
    setting.mouseSensitivity = item.mouseSensitivity
    return setting
end

function SprayPaintConfig:getSprayPaintById(id)
    for i, v in pairs(self.sprayPaint) do
        if id == v.sprayPaintId then
            return v
        end
    end
end

function SprayPaintConfig:getSprayPaintByItemId(itemId)
    for i, v in pairs(self.sprayPaint) do
        if itemId == v.itemId then
            return v
        end
    end
end

function SprayPaintConfig:getSprayPaintByInitialItemId(itemId)
    for i, v in pairs(self.sprayPaint) do
        if itemId == v.initialItemId then
            return v
        end
    end
end

function SprayPaintConfig:getSameGanByInitialItemId(initialItemId)
    local SP = {}
    for i, v in pairs(self.sprayPaint) do
        if initialItemId == v.initialItemId then
            table.insert(SP, v)
        end
    end
    return SP
end

return SprayPaintConfig