---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaolai.
--- DateTime: 2019/8/28 14:04
---

SkyBlockReceiveTaskRewardEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("SkyBlockReceiveTask", SkyBlockReceiveTaskRewardEvent)

PlayerSellItemEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("SellItemEvent", PlayerSellItemEvent)

PlayerSkyBlocShopOperateEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("SkyBlocShopOperate", PlayerSkyBlocShopOperateEvent)

SkyBlockDareTaskOperateEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("DareTaskOperate", SkyBlockDareTaskOperateEvent)

PlayerCancelGuideArrowEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("CancelGuideArrow", PlayerCancelGuideArrowEvent)

PlayerBuyMoneyEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("BuyMoney", PlayerBuyMoneyEvent)

PlayerBuyChirstmasGiftEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("BuyChirstmasGift", PlayerBuyChirstmasGiftEvent)

PlayerGetGiftNumEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("GetGiftNum", PlayerGetGiftNumEvent)

PlayerOpenGiftEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("OpenGift", PlayerOpenGiftEvent)

PlayerCommonClickEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("SkyBlockCommonClick", PlayerCommonClickEvent)

SkyBlockRedSwitchClickEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("SkyBlockRedSwitchClick", SkyBlockRedSwitchClickEvent)

SkyBlockRedRichBtnClickEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("SkyBlockRedRichBtnClick", SkyBlockRedRichBtnClickEvent)