---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2019/6/6 15:37
---
Define = {}
Define.Money = {
    DIAMOND = 1,
    GOLD = 2,
    MONEY = 3,
    CHIP = 4,
    KEY = 5,
    VIRUSCRYSTAL = 6,
    LIFECRYSTAL = 7,
}

Define.BuyChest = "BuyChest"
--Define.mainBGM = 10018 --行尸走肉背景音乐
Define.maxLoopCount = 10
Define.BuyGoods = "BuyGoods"
Define.BuySupplyBox = "BuySupplyBox"

Define.RefreshType = {
    TypeDefault = 0,
    TypeSpecial = 1,
    TypeBoss = 2
}

Define.RewardType = {
    VIP = 7,
    Item = 11
}

Define.TargetType = {
    TargetMonster = 0,
    TargetPlayer = 1
}

Define.PlayerDamageType = {
    CloseDamage = 0,
    RemoteDamage = 1
}

Define.BossType = {
    Boss = 1,
    Dead = 0
}

Define.SupplyBox = {
    TiroBox = 1,
    DailyBox = 2,
    RandomBox = 3,
    VipBox = 4
}

Define.SupplyBoxStatus = {
    CanReceive = 1,
    UnReceive = 2,
    CanBuy = 3,
    UnBuy = 4
}

return Define