---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wu.
--- DateTime: 2019/6/5 14:53
---
MaterialConfig = {}
MaterialConfig.Materials = {}

function MaterialConfig:init(config)
    for _, material in pairs(config) do
        local data = {}
        data.Id = tonumber(material.Id)
        data.ItemId = tonumber(material.ItemId)
        data.Count = tonumber(material.Count)
        self.Materials[data.Id] = data
        --print(json.encode(data))
    end
end

function MaterialConfig:getMaterialById(Id)
    return self.Materials[tonumber(Id)]
end


return MaterialConfig
