---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/6/6 10:23
---
MonsterRegionConfig = {}

MonsterRegionConfig.MonsterRegionData = {} --刷怪区域配置

function MonsterRegionConfig:init(config)
    self:initMonsterRegion(config)
end

function MonsterRegionConfig:initMonsterRegion(config)
    --HostApi.log("MonsterRegionConfig:initMonsterRegion")

    for _, vData in pairs(config) do
        local data = {}
        data.regionId = tonumber(vData.regionId) or 0
        data.strRegionArea = vData.regionId
        data.tbRegionArea = self:parseRegionArea(vData.regionArea)
        data.defaultMonsterGroup = tonumber(vData.defaultMonsterGroup) or 0
        data.maxMonsterCount = tonumber(vData.maxMonsterCount) or 0
        data.minMonsterCount = tonumber(vData.minMonsterCount) or 0
        data.defaultRefreshIntervalSec, data.defaultRefreshIntervalNum = MonsterRegionConfig:parseRefreshInterval(vData.defaultRefreshInterval)
        data.checkInterval = tonumber(vData.checkInterval) or 0
        data.specialMonsterGroup = tonumber(vData.specialMonsterGroup) or 0
        data.specialMonsterCount = MonsterRegionConfig:parseSpecialMonsterCount(vData.specialMonsterCount)
        data.bossMonsterGroup = tonumber(vData.bossMonsterGroup) or 0
        data.specialRefreshIntervalSec, data.specialRefreshIntervalNum = MonsterRegionConfig:parseRefreshInterval(vData.specialRefreshInterval)

        data.refreshPos = {} --怪物刷怪点
        data.refreshPos[Define.RefreshType.TypeDefault] = {} --普通怪物刷怪点
        data.refreshPos[Define.RefreshType.TypeSpecial] = {} --尸潮怪物刷怪点

        data.hasCorpseTide = false --是否有尸潮
        self.MonsterRegionData[data.strRegionArea] = data --regionId为key
    end
end

function MonsterRegionConfig:parseSpecialMonsterCount(specialMonsterCount)
    return StringUtil.split(specialMonsterCount, "#")
end

function MonsterRegionConfig:parseRefreshInterval(refreshInterval)
    local c_refreshInterval = StringUtil.split(refreshInterval, "#")
    return c_refreshInterval[1], c_refreshInterval[2]
end

function MonsterRegionConfig:parseRegionArea(regionArea)
    local result = {}

    local c_regionArea = StringUtil.split(regionArea, ",")
    for _, area in pairs(c_regionArea) do
        local c_area = StringUtil.split(area, "#")
        local a_area = {}
        a_area.x = tonumber(c_area[1]) or 0
        a_area.y = tonumber(c_area[2]) or 0
        a_area.z = tonumber(c_area[3]) or 0
        result[#result + 1] = a_area
    end
    return result
end

function MonsterRegionConfig:InitRefreshMonsterPos(config)
    for _, vMonsterRegionData in pairs(MonsterRegionConfig.MonsterRegionData) do
        MonsterRegionConfig:initRegionArea(vMonsterRegionData, config)
    end
end

function MonsterRegionConfig:posInArea(vData, position)
    local pos = VectorUtil.newVector3(position.x, position.y, position.z)
    return pos.x > vData.tbRegionArea[1].x and pos.x < vData.tbRegionArea[2].x
            and pos.y > vData.tbRegionArea[1].y and pos.y < vData.tbRegionArea[2].y
            and pos.z > vData.tbRegionArea[1].z and pos.z < vData.tbRegionArea[2].z
end

function MonsterRegionConfig:initRegionArea(vMonsterRegionData, config)
    for _, position in pairs(config) do
        if tonumber(position.areaId) == vMonsterRegionData.regionId then
            local pos = VectorUtil.newVector3(position.x, position.y, position.z)
            --local ret, newPos = ToolUtil:getStandPos(pos)
            --if ret then
            --    pos = newPos
            --end
            pos = VectorUtil.add3(pos, VectorUtil.newVector3(0.5, 0, 0.5))
            if tonumber(position.blockId) == MonsterRuleConfig.defaultMonsterBlockId then
                table.insert(self.MonsterRegionData[vMonsterRegionData.strRegionArea].refreshPos[Define.RefreshType.TypeDefault], pos)
                --print(string.format("refreshPos[Define.RefreshType.TypeDefault] %d %d %d", pos.x, pos.y, pos.z))
            elseif tonumber(position.blockId) == MonsterRuleConfig.specialMonsterBlockId then
                table.insert(self.MonsterRegionData[vMonsterRegionData.strRegionArea].refreshPos[Define.RefreshType.TypeSpecial], pos)
                --print(string.format("refreshPos[Define.RefreshType.TypeSpecial] %d %d %d", pos.x, pos.y, pos.z))
            end
        end
    end
end

return MonsterRegionConfig