---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/7/4 16:43
---
MusicBoxConfig = {}

MusicBoxConfig.MusicBoxConfigMap = {}

function MusicBoxConfig:init(config)
    for _, vConfig in pairs(config) do
        local data = {}
        data.itemId = tonumber(vConfig.itemId)
        data.musicId = tonumber(vConfig.musicId)
        data.effectRange = tonumber(vConfig.effectRange)
        data.liveTime = tonumber(vConfig.liveTime)
        self.MusicBoxConfigMap[data.itemId] = data
        --HostApi.log(string.format("MusicBoxConfig:init %d %d %d %d",
        --        data.itemId, data.musicId, data.effectRange, data.liveTime))
    end
end

function MusicBoxConfig:getMusicBoxConfig(itemId)
    --HostApi.log("MusicBoxConfig:getMusicBoxConfig " .. itemId)
    return self.MusicBoxConfigMap[itemId]
end

return MusicBoxConfig