---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/6/28 11:58
---
RobotConfig = {}

RobotConfig.RobotConfigMap = {}

RobotConfig.totalWeight = 0 --总权重

function RobotConfig:init(config)
    for _, vConfig in pairs(config) do
        local data = {}
        data.i_robotId = tonumber(vConfig.i_robotId) or 0
        data.s_name = vConfig.s_name or ""
        data.s_aiFile = vConfig.s_aiFile or ""
        data.s_actor = vConfig.s_actor or ""
        data.hp = tonumber(vConfig.hp) or 0
        data.attack = tonumber(vConfig.i_attack) or 0
        data.i_defense = tonumber(vConfig.i_defense) or 0
        data.attackDistance = tonumber(vConfig.attackDistance) or 0
        data.attackCd = tonumber(vConfig.attackCd) or 0
        data.attackCount = tonumber(vConfig.attackCount) or 0
        data.moveSpeed = tonumber(vConfig.moveSpeed) or 0
        data.refreshRadius = tonumber(vConfig.refreshRadius) or 0
        data.patrolDistance = tonumber(vConfig.patrolDistance) or 0
        data.dropItem = StringUtil.split(vConfig.dropItem, "#")
        data.dropsProbability = StringUtil.split(vConfig.dropsProbability, "#")
        data.keepTime = tonumber(vConfig.keepTime) or 0
        data.i_weight = tonumber(vConfig.i_weight) or 0
        self.totalWeight = self.totalWeight + data.i_weight
        self.RobotConfigMap[data.i_robotId] = data
        --HostApi.log(string.format("RobotConfig:init %d %s %d %d",
        --        data.i_robotId, data.s_name, data.i_attack, data.i_defense))
    end

    RobotConfig:prepareMonster()
end

function RobotConfig:prepareMonster()
    for _, data in pairs(self.RobotConfigMap) do
        local monster = MonsterSetting.new()
        monster.monsterId = data.i_robotId
        monster.monsterBtTree = data.s_aiFile
        monster.monsterType = 2
        monster.isAutoAttack = 1
        monster.attackDistance = data.attackDistance
        monster.attackCd = data.attackCd
        monster.attackCount = data.attackCount
        monster.moveSpeed = data.moveSpeed
        monster.attackType = 0
        monster.patrolDistance = data.patrolDistance
        monster.skillId = 0
        monster.skillCd = 0
        monster.chaseRange = 0
        HostApi.addMonsterSetting(monster)
    end
end

--随机一个机器人
function RobotConfig:randRobot()
    if self.totalWeight <= 0 then
        return nil
    end

    local iRand = math.random(self.totalWeight)
    local iWeight = 0
    for _, vConfig in pairs(self.RobotConfigMap) do
        iWeight = iWeight + vConfig.i_weight
        if iWeight >= iRand then
            return vConfig
        end
    end
    return nil
end

return RobotConfig