---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wu.
--- DateTime: 2019/6/17 15:29
---

TitleConfig = {}
TitleConfig.Titles = {}
TitleConfig.TitlesType = {}

function TitleConfig:init(config)
    for _, title in pairs(config) do
        local data = {}
        data.Id = tonumber(title.Id)
        data.Type = tonumber(title.Type)
        data.Condition = tonumber(title.Condition)
        data.Weight = tonumber(title.Weight)
        data.Name = title.Name
        self.Titles[data.Id] = data
    end
end

function TitleConfig:initType(config)
    for _, titleType in pairs(config) do
        local data = {}
        data.Id = tonumber(titleType.Id)
        data.Type = tonumber(titleType.Type)
        data.Weight = tonumber(titleType.Weight)
        data.Name = titleType.Name
        data.MonsterIds = StringUtil.split(titleType.MonsterIds,"#")
        self.TitlesType[data.Id] = data
    end
end

function TitleConfig:getTitleById(Id)
    return self.Titles[tonumber(Id)]
end

function TitleConfig:getTitleTypeById(Id)
    return self.TitlesType[tonumber(Id)]
end

return TitleConfig
