---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/9/25 17:47
---

require "event.BaseEvent"

local Skill

ArrowRainEvent = class("ArrowRainEvent", BaseEvent)

function ArrowRainEvent:onTriggered(player)
    Skill = SkillConfig:getSkill(tonumber(self.config.param3))
    if not Skill then
        return
    end
    local pos = self:randomPos(tonumber(self.config.param1), self.config.param2)
    if pos ~= nil then
        --MsgSender.sendTopTipsToTarget(0, 5, Messages:msgArrowRain(player.name))
        for index, vec in pairs(pos) do
            self.island = IslandConfig:inWhichIsland(VectorUtil.newVector3(vec.x, vec.y - 20, vec.z))
        end
        MsgSender.sendCenterTipsToTarget(player.rakssid, 5, Messages:msgArrowRainToOwn(self.island))
        GameMatch:lookingPlayer(5, self.island, Messages:msgArrowRain(GameMatch:nameAndTeamId(player), self.island))
        self:doEffect(pos, player.userId)
    end
end

local function createArrow(position, userId)
    local player = PlayerManager:getPlayerByUserId(userId)
    if not player then
        return
    end
    EngineWorld:addSkillThrowable(player, function(entity)
        entity:setHeadingFromThrower(player.entityPlayerMP, player:getPitch(), player:getYaw(), 0, 2, 0)
        entity:setSkillId(Skill.id)
        entity:setSkillDuration(Skill.duration)
        entity:setReleaseDistance(Skill.distance)
        entity:setMoveSpeed(Skill.moveSpeed)
        entity:setDropSpeed(Skill.dropSpeed)
        entity:setAtlasName(Skill.atlasName)
        entity:setItemIconName(Skill.iconName)
        entity:setItemSkillId(Skill.itemId)
        entity:setEffectName(Skill.effectName)
        entity:setPositionAndRotation(position, player:getPitch(), player:getYaw())
    end)
end

function ArrowRainEvent:doEffect(pos, userId)
    local count = tonumber(self.config.param1)
    local duration = tonumber(self.config.time) * 1000
    local totalTime = 0
    local subTime = duration / count
    local curTime = 0
    LuaTimer:scheduleTimer(function(userId)
        local removes = 0
        curTime = curTime + 1000
        for index, vec in pairs(pos) do
            createArrow(vec, userId)
            totalTime = totalTime + subTime
            if totalTime >= curTime then
                removes = index
                break
            end
        end
        while removes > 0 do
            removes = removes - 1
            table.remove(pos, 1)
        end
    end, 1000, tonumber(self.config.time), userId)
end

return ArrowRainEvent