---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/9/25 17:49
---

require "event.BaseEvent"
require "data.Area"

BloodReturnEvent = class("BloodReturnEvent", BaseEvent)

function BloodReturnEvent:onTriggered(player)
    MsgSender.sendCenterTipsToTarget(player.rakssid, 5, Messages:msgGoldApple())
    local pos = player:getPosition()
    --player.bloodReturn = {}
    --if self.bloodReturnTimer ~= 0 then
    --    LuaTimer:cancel(player.bloodReturnTimer)
    --    self.bloodReturnTimer = 0
    --end
    --if self.bloodFreshTimer ~= 0 then
    --    LuaTimer:cancel(player.bloodFreshTimer)
    --    self.bloodFreshTimer = 0
    --end
    player:resetBloodReturn(false)

    player.bloodReturn = Area.new(pos, tonumber(self.config.param3))
    player.bloodReturn:setBloodReturn(self.config.param1, tonumber(self.config.param2))
    player.entityPlayerMP:appleFresh(-1)
    EngineWorld:addSimpleEffect("148_aixin.effect", VectorUtil.newVector3(pos.x, pos.y + 0.5, pos.z),
            0, self.config.time * 1000, 0, 0.4)
    player.bloodReturnTimer = LuaTimer:schedule(function (userId)
        local c_player = PlayerManager:getPlayerByUserId(userId)
        if c_player == nil then
            return
        end
        c_player.bloodReturnTimer = 0
        c_player.bloodReturn = {}
    end, self.config.time * 1000, nil, player.userId)

    local bloodValue = StringUtil.split(self.config.param1, "#")
    local apple = tonumber(bloodValue[1])
    local freshTime = tonumber(self.config.param2) - 3
    if freshTime > 0 then
        player.bloodFreshTimer = LuaTimer:schedule(function(appleValue, userId)
            local c_player = PlayerManager:getPlayerByUserId(userId)
            if c_player == nil then
                return
            end
            if c_player.entityPlayerMP ~= nil and c_player.maxApple - appleValue == 0 then
                c_player.entityPlayerMP:appleFresh(3)
            end
        end, freshTime * 1000, nil, apple, player.userId)
    end
end

return BloodReturnEvent