---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/9/25 17:49
---

require "event.BaseEvent"

FrozenEvent = class("FrozenEvent", BaseEvent)

function FrozenEvent:onTriggered(player)
    local targetId = GameMatch:randomPlayer(player:getTeamId())
    local target = PlayerManager:getPlayerByRakssid(targetId)
    if target == nil then
        return
    end
    MsgSender.sendCenterTipsToTarget(player.rakssid, 5, Messages:msgFrozen())
    MsgSender.sendBottomTipsToTarget(target.rakssid, 5, Messages:msgBeFrozen())
    target:setOnFrozen(self.config.time * 1000)
end

return FrozenEvent