---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/9/25 17:49
---

require "event.BaseEvent"

QuicklyBuildEvent = class("QuicklyBuildEvent", BaseEvent)

function QuicklyBuildEvent:onTriggered(player)
    PacketSender:getSender():sendChangeQuicklyBuildBlockStatus(player.rakssid, true, true)
    MsgSender.sendCenterTipsToTarget(player.rakssid, 5, Messages:msgQuicklyBuild())
    if self.config.time ~= -1 then
        LuaTimer:schedule(function (userId)
            local player = PlayerManager:getPlayerByUserId(userId)
            if player == nil then
                return
            end
            PacketSender:getSender():sendChangeQuicklyBuildBlockStatus(player.rakssid, false, false)
        end, self.config.time * 1000, nil, player.userId)
    end
end

return QuicklyBuildEvent