---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/9/25 17:48
---

require "event.BaseEvent"

SnowRainEvent = class("SnowRainEvent", BaseEvent)

function SnowRainEvent:onTriggered(player)
    local pos = self:randomPos(tonumber(self.config.param1), self.config.param2)
    if pos ~= nil then
        MsgSender.sendTopTipsToTarget(0, 5, Messages:msgSnowRain(player.name))
        self:doEffect(pos)
    end
end

function SnowRainEvent:doEffect(pos)
    local time = 0
    local interval = math.ceil(tonumber(self.config.time) / tonumber(self.config.param1))
    for _, vec in pairs(pos) do
        local v3i = VectorUtil.toBlockVector3(vec.x, vec.y, vec.z)
        time = time + interval
    end
end

return SnowRainEvent