---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/9/25 17:47
---

require "event.BaseEvent"

TNTRainEvent = class("TNTRainEvent", BaseEvent)

function TNTRainEvent:onTriggered(player)
    local pos = self:randomPos(tonumber(self.config.param1), self.config.param2)
    if pos ~= nil then
        if player ~= nil then
            --MsgSender.sendTopTipsToTarget(0, 5, Messages:msgTntRain(player.name))
            for index, vec in pairs(pos) do
                self.island = IslandConfig:inWhichIsland(VectorUtil.newVector3(vec.x, vec.y - 20, vec.z))
            end
            MsgSender.sendCenterTipsToTarget(player.rakssid, 5, Messages:msgTntRainToOwn(self.island))
            GameMatch:lookingPlayer(5, self.island, Messages:msgTntRain(GameMatch:nameAndTeamId(player), self.island))
        end
        self:doEffect(pos)
    end
end

local function createTNT(position)
    local pos = VectorUtil.toBlockVector3(position.x, position.y, position.z)
    EngineWorld:setBlock(pos, BlockID.TNT)
    EngineWorld:getWorld():fireTNT(pos)
end

function TNTRainEvent:doEffect(pos)
    local count = tonumber(self.config.param1)
    local duration = tonumber(self.config.time) * 1000
    local totalTime = 0
    local subTime = duration / count
    local curTime = 0
    LuaTimer:scheduleTimer(function()
        local removes = 0
        curTime = curTime + 1000
        for index, vec in pairs(pos) do
            createTNT(vec)
            totalTime = totalTime + subTime
            if totalTime >= curTime then
                removes = index
                break
            end
        end
        while removes > 0 do
            removes = removes - 1
            table.remove(pos, 1)
        end
    end, 1000, tonumber(self.config.time))
end

return TNTRainEvent