---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/9/25 17:48
---

require "event.BaseEvent"

WaterRainEvent = class("WaterRainEvent", BaseEvent)

function WaterRainEvent:onTriggered(player)
    local pos = self:randomPos(tonumber(self.config.param1), self.config.param2)
    if pos ~= nil then
        --MsgSender.sendTopTipsToTarget(0, 5, Messages:msgWaterRain(player.name))
        for index, vec in pairs(pos) do
            self.island = IslandConfig:inWhichIsland(VectorUtil.newVector3(vec.x, vec.y - 20, vec.z))
        end
        MsgSender.sendCenterTipsToTarget(player.rakssid, 5, Messages:msgWaterRainToOwn(self.island))
        GameMatch:lookingPlayer(5, self.island, Messages:msgWaterRain(GameMatch:nameAndTeamId(player), self.island))
        self:doEffect(pos)
    end
end

function WaterRainEvent:doEffect(pos)
    for _, vec in pairs(pos) do
        local v3i = VectorUtil.newVector3i(vec.x, vec.y, vec.z)
        EngineWorld:setBlock(v3i, BlockID.WATER_MOVING)
        LuaTimer:schedule(function(position)
            local vec3i = VectorUtil.newVector3i(position.x, position.y, position.z)
            EngineWorld:setBlock(vec3i, 0, 0, 3, true)
        end, tonumber(self.config.time) * 1000, nil, v3i)
    end
end

return WaterRainEvent