---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/7/22 0022 10:05
---
PlayerStartGameEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("StartGame", PlayerStartGameEvent)

PlayerSelectJobEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("SelectJobId", PlayerSelectJobEvent)

--刷新职业奖池事件
PlayerRefreshJobListInfoEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("RefreshJobListInfo", PlayerRefreshJobListInfoEvent)


--从奖池里随机职业的给玩家  ExtractRandomJobId
--玩家抽取职业的事件
PlayerExtractJobEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("ExtractRandomJobId", PlayerExtractJobEvent)