---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/9/9 9:31
---
MonsterType = {
    ServerMonster = 0,
    IronGolem = 1, ---铁傀儡
    SnowBallInsect = 2  ---囊虫
}

MonsterManager = {}

local Monsters = {}

LuaTimer:scheduleTimer(function()
    for _, monster in pairs(Monsters) do
        monster:onUpdate()
    end
end, 100)

function MonsterManager:createMonster(position, type, ...)
    local config = MonsterConfig:getConfigByType(type)
    if self:getMonsterNumByType(type) < config.maxNum then
        if type == MonsterType.ServerMonster then
            ServerMonster.new(position, "boy.actor", {}, ...)
            return true
        elseif type == MonsterType.IronGolem then
            IronGolem.new(position, config.actor, config, ...)
            return true
        elseif type == MonsterType.SnowBallInsect then
            SnowBallInsect.new(position, config.actor, config, ...)
            return true
        end
    end

    return false
end

function MonsterManager:addMonster(monster)
    Monsters[tostring(monster.entityId)] = monster
end

function MonsterManager:removeMonster(monster)
    Monsters[tostring(monster.entityId)] = nil
end

function MonsterManager:getMonster(entityId)
    return Monsters[tostring(entityId)]
end

function MonsterManager:getMonsterNumByType(type)
    local num = 0
    for _, monster in pairs(Monsters) do
        if type == monster.type then
            num = num + 1
        end
    end
    return num
end

function MonsterManager:clearMonster()
    local monsters = {}
    for _, monster in pairs(Monsters) do
        table.insert(monsters, monster)
    end
    for _, monster in pairs(monsters) do
        monster:setDead()
    end
    Monsters = {}
end