---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 98632.
--- DateTime: 2019/8/20 17:32
---

Define={}

Define.AdType = {
    Money = 102501,
    Building = 102502,
    AppShop = 102503,
    Lottery = 102504
}

Define.ItemIdAd =
{
    ItemID=10000
}
return Define