---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 98632.
--- DateTime: 2019/10/12 19:40
---

LSRankManager = {}

LSRankManager.Ranks = {}

function LSRankManager:addPlayerRank(player)

    self:removeExitPlayer()
    local flag = true
    player.property.fame = FameConfig:getNameByKill(player.property.kill)
    for i, Value in pairs(self.Ranks) do
        if Value.userId == player.userId then
            Value:setName(player.name)
            if player.property.isConcealPower then
                Value:setMuscle(0)
            else
                Value:setMuscle(player.property.muscleMass)
            end
            Value:setFame(player.property.fame)
            Value:setKill(player.property.kill)
            local advanced = AdvancedConfig:getAdvancedConfig(player.property.advancedLevel)
            if advanced and player.property.isConcealPower == false then
                Value:setStage(advanced.gradeId)
            else
                Value:setStage(0)
            end
            flag = false
            break
        end
    end

    local advanced = AdvancedConfig:getAdvancedConfig(player.property.advancedLevel)
    local gradeId = 0
    if advanced and player.property.isConcealPower == false then
        gradeId = advanced.gradeId
    end
    local oneRank = LSPlayerRank.new(player.userId, player.name, player.property.muscleMass, player.property.fame, player.property.kill, gradeId)
    if flag then
        table.insert(self.Ranks, oneRank)
    end

    self:sortPlayerRank()

    for _, Value in pairs(self.Ranks) do
        self:senderOnePlayerRank(Value)
    end

end

function LSRankManager:removePlayerRank(userId)
    for i, Value in pairs(self.Ranks) do
        if Value.userId == userId then
            table.remove(self.Ranks, i)
            break
        end
    end

    self:removeExitPlayer()

    self:sortPlayerRank()

    for _, Value in pairs(self.Ranks) do
        self:senderOnePlayerRank(Value)
    end

end

function LSRankManager:updatePlayerRank(player)

    player.property.fame = FameConfig:getNameByKill(player.property.kill)

    for i, Value in pairs(self.Ranks) do
        if Value.userId == player.userId then
            Value:setName(player.name)
            if player.property.isConcealPower then
                Value:setMuscle(0)
            else
                Value:setMuscle(player.property.muscleMass)
            end
            --Value:setMuscle(player.property.muscleMass)
            Value:setFame(player.property.fame)
            Value:setKill(player.property.kill)
            local advanced = AdvancedConfig:getAdvancedConfig(player.property.advancedLevel)
            if advanced and player.property.isConcealPower == false then
                Value:setStage(advanced.gradeId)
            else
                Value:setStage(0)
            end
            break
        end
    end

    self:removeExitPlayer()

    self:sortPlayerRank()

    for _, Value in pairs(self.Ranks) do
        self:senderOnePlayerRank(Value)
    end

end

function LSRankManager:senderOnePlayerRank(oneRank)

    local data = {
        rank = oneRank.rank,
        name = oneRank.name,
        muscle = oneRank.muscle,
        fame = oneRank.fame,
        kill = oneRank.kill,
        stage = oneRank.stage
    }

    local player = PlayerManager:getPlayerByUserId(oneRank.userId)
    if player then
        GamePacketSender:SendLiftingSimulatorMeRank(player.rakssid, json.encode(data))
    end

end

function LSRankManager:senderAllRankToOnePlayer(player)
    local tempRanks = {}

    for _, Value in pairs(self.Ranks) do
        local data = {
            rank = Value.rank,
            name = Value.name,
            muscle = Value.muscle,
            fame = Value.fame,
            kill = Value.kill,
            stage = Value.stage
        }
        table.insert(tempRanks, data)
    end

    GamePacketSender:SendLiftingSimulatorAllOtherRank(player.rakssid, json.encode(tempRanks))

end

function LSRankManager:senderAllPlayerRank()

    local tempRanks = {}

    for _, Value in pairs(self.Ranks) do
        local data = {
            rank = Value.rank,
            name = Value.name,
            muscle = Value.muscle,
            fame = Value.fame,
            kill = Value.kill,
            stage = Value.stage
        }
        table.insert(tempRanks, data)
    end

    for _, Value in pairs(self.Ranks) do
        local player = PlayerManager:getPlayerByUserId(Value.userId)
        if player then
            GamePacketSender:SendLiftingSimulatorAllOtherRank(player.rakssid, json.encode(tempRanks))
        end
    end


end

function LSRankManager:sortPlayerRank()
    table.sort(self.Ranks, function(a, b)
        if a.muscle ~= b.muscle then
            return a.muscle > b.muscle
        end
        if a.kill ~= b.kill then
            return a.kill > b.kill
        end
        if a.stage ~= b.stage then
            return a.stage > b.stage
        end
        return false
    end)

    local rankNum = 1
    for i, Value in pairs(self.Ranks) do
        if i ~= 1 then
            if self.Ranks[i - 1].muscle ~= Value.muscle or self.Ranks[i - 1].kill ~= Value.kill or self.Ranks[i - 1].stage ~= Value.stage then
                rankNum = rankNum + 1
            end
        end
        Value:setRank(rankNum)
    end
end

--删除掉线玩家
function LSRankManager:removeExitPlayer()
    local i = 1
    while (i <= #self.Ranks) do
        local player = PlayerManager:getPlayerByUserId(self.Ranks[i].userId)
        if player then
            i = i + 1
        else
            table.remove(self.Ranks, i)
        end
    end
end

return LSRankManager

