---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/7/5 16:53
---
ToolUtil = {}

--获得一个可站立的位置
function ToolUtil:getStandPos(pos)
    local posVector3 = VectorUtil.newVector3i(pos.x, pos.y, pos.z)

    local loopCount = (1 + 5)

    while(EngineWorld:getBlockId(posVector3) ~= 0)
    do
        posVector3.y = posVector3.y + 1
        if loopCount >= Define.maxLoopCount then
            return false, VectorUtil.toVector3(posVector3)
        end
        loopCount = loopCount + 1
    end

    return true, VectorUtil.toVector3(posVector3)
end

return ToolUtil