---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/1/8 0008 10:27
---
DbUtil = {}
DbUtil.GAME_DATA = 1

DbUtil.FIRST_DATA_KEY = DbUtil.GAME_DATA
DbUtil.LAST_DATA_KEY = DbUtil.GAME_DATA

DBManager:addMustLoadSubKey(DbUtil.GAME_DATA)

function DbUtil:getPlayerData(player)
    DBManager:getPlayerData(player.userId, DbUtil.GAME_DATA)
end

function DbUtil:onPlayerGetDataFinish(player, data, subKey)
    HostApi.log("DbUtil:onPlayerGetDataFinish(player, data, subKey)")
    if subKey == DbUtil.GAME_DATA then
        player:initGameDataFromDB(data)
    end
    if DbUtil:IsGetAllDataFinished(player) then
        --判断全部数据是否初始化好
        player.cur_jobId = player.lastJobId
        player.GameJob:init()
        player.GameJobPond:init()
        player:nextGameUseProp()
        GameMatch:setName()
    end
end

function DbUtil:savePlayerData(player, immediate)
    if player == nil then
        return
    end
    DbUtil:SavePlayerGameData(player, immediate)
end

function DbUtil:SavePlayerGameData(player, immediate)
    if not DbUtil:CanSavePlayerData(player, DbUtil.GAME_DATA) then
        return
    end
    local data = {}
    data.lastJobId = player.lastJobId or 0
    data.jobs_data = player.jobs_data or {}
    data.init_prop = player.init_prop or {}
    DBManager:savePlayerData(player.userId, DbUtil.GAME_DATA, data, immediate)
end

function DbUtil:CanSavePlayerData(player, subKey)
    return DBManager:isLoadDataFinished(player.userId, subKey)
end

function DbUtil:IsGetAllDataFinished(player)
    for key = DbUtil.FIRST_DATA_KEY, DbUtil.LAST_DATA_KEY do
        if not DbUtil:CanSavePlayerData(player, key) then
            return false
        end
    end
    return true
end

return DbUtil