---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/10/14 0014 15:23
---
IEntity = class("IEntity", BaseBtTree)

function IEntity:ctor(entity, type, properties)
    self.type = type
    self.entityId = entity:hashCode()
    self.entity = DynamicCast.dynamicCastEntity(type, entity)
    self.properties = properties
    self:onCreate()
end

function IEntity:onCreate()

end

function IEntity:onRemove()
    self.entity = nil
    self:onDestroy()
    self:removeBtTree()
end

function IEntity:onDestroy()

end

return IEntity