---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/11/28 15:33
---
ClientConfig = {}

function ClientConfig:loadClientConfig()
    local config = FileUtil.getConfigFromYml("setting/ClientConfig.yml")
    ClientConfig.boyFreeSkinId = tonumber(config.boyFreeSkinId) or 1
    ClientConfig.girlFreeSkinId = tonumber(config.girlFreeSkinId) or 2
    ClientConfig.adjustCoe = tonumber(config.adjustCoe) or 1 --攻击调节系数
    ClientConfig.grabCoe1 = tonumber(config.grabCoe1) or 1 --抓取缩放系数1
    ClientConfig.grabCoe2 = tonumber(config.grabCoe2) or 1 --抓取缩放系数2
    ClientConfig.maxScale = tonumber(config.maxScale) or 90 --最大缩放值

    --LogUtil.log(inspect.inspect(config))
end

return ClientConfig