---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 98632.
--- DateTime: 2019/10/21 15:26
---

FameConfig = {}

FameConfig.settings = {}

function FameConfig:init(config)
    for _, vConfig in pairs(config) do
        local data = {}
        data.id = tonumber(vConfig.n_id) or 0 --Id
        data.name = vConfig.s_name or "" --名称
        data.desc = vConfig.s_desc or "" --
        data.kill = tonumber(vConfig.n_kill) or 0 --杀人数
        data.color = vConfig.s_color or "" --称号颜色
        table.insert(FameConfig.settings, data)
    end
end

function FameConfig:getFameConfig(Id)
    for _, v in pairs(FameConfig.settings) do
        if v.id == Id then
            return v
        end
    end
    return nil
end

function FameConfig:getNameByKill(kill)

    local name = ""
    table.sort(FameConfig.settings,function(a,b)
        return a.id<b.id
    end)

    for _, Value in pairs(FameConfig.settings) do

        if Value.kill<=kill then
            name = Value.name
        end
    end
    return name
end

function FameConfig:getColorByKill(kill)

    local color = ""
    table.sort(FameConfig.settings,function(a,b)
        return a.id<b.id
    end)

    for _, Value in pairs(FameConfig.settings) do

        if Value.kill<=kill then
            color = Value.color
        end
    end

    return color
end

return FameConfig
