---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/7/18 0018 19:48
---
GamePacketSender = {}

function GamePacketSender:sendTycoonVideoData(rakssid, data)
    PacketSender:sendServerCommonData(rakssid, "TycoonData", "VideoAd", data)
end

function GamePacketSender:sendAppShopVideoData(rakssid, data)
    PacketSender:sendServerCommonData(rakssid, "AppShopData", "VideoAd", data)
end

return GamePacketSender