---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/6/10 20:55
---
BaseUtil = {}

function BaseUtil:incNumber(num, value)
    num = num + value
    return num
end

function BaseUtil:isTableHave(tb, value)
    if tb == nil then
        return false
    end

    for _, val in pairs(tb) do
        if val == value then
            return true
        end
    end

    return false
end

return BaseUtil