---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/1/14 0014 16:15
---
EngineUtil = {}

local function sendEnterOtherGame(rakssid, gameType, targetId, mapId)
    local player = PlayerManager:getPlayerByRakssid(rakssid)
    if not player then
        return
    end
    if DBManager:hasDataSaving(player.userId) then
        LuaTimer:schedule(function()
            sendEnterOtherGame(rakssid, gameType, targetId, mapId)
        end, 500)
        return
    end
    HostApi.sendEnterOtherGame(rakssid, gameType, targetId, mapId)
end

function EngineUtil.sendEnterOtherGame(rakssid, gameType, targetId, mapId)
    local player = PlayerManager:getPlayerByRakssid(rakssid)
    if not player then
        return
    end
    DBManager:callSavePlayerData(player)
    mapId = mapId or ""
    sendEnterOtherGame(rakssid, gameType, targetId, mapId)
end

function EngineUtil.disposePlatformOrder(userId, orderId, isConsume)
    HostApi.platformOrderDispose(userId, WebService.ServerHttpHost, orderId, isConsume or false)
end

return EngineUtil