---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/12/24 17:25
---

GameTeam = class()
GameTeam.teamId = 0
GameTeam.teamName = ""
GameTeam.kills = 0
GameTeam.curPlayerCount = 0
GameTeam.teamPlayers = {}

function GameTeam:ctor(teamConfig)
    self.teamId = teamConfig.teamId
    self.teamName = teamConfig.teamName
    self.nameColor = teamConfig.nameColor
    self.kills = 0
    self.curPlayerCount = 0
    self.teamPlayers = {}
end

function GameTeam:addPlayer(player)
    local id = player:getEntityId()
    if id ~= nil then
        table.insert(self.teamPlayers, player)
        self.curPlayerCount = self.curPlayerCount + 1
    end
end

function GameTeam:subPlayer(player)
    local id = player:getEntityId()
    if id ~= nil then
        for i, v in pairs(self.teamPlayers) do
            table.remove(self.teamPlayers, i)
        end
        self.curPlayerCount = self.curPlayerCount - 1
    end
end

function GameTeam:addTeamKill()
    self.kills = self.kills + 1
end

function GameTeam:getTeamId()
    return self.teamId
end

function GameTeam:getTeamName()
    return self.nameColor .. "[" .. self.teamName .. "]"
end

function GameTeam:getPlayerNum()
    return self.curPlayerCount
end