---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/7/8 18:15
---
require "config.GunConfig"
require "data.SupplyPoint"

WeaponSupply = class("WeaponSupply", SupplyPoint)

function WeaponSupply:ctor(config, gunId, num)
    self.id = config.id
    self.position = config.pos
    self.entityId = 0
    self.gunId = gunId
    self.inWarning = false
    self.isWaitting = false
    self:randomSupply()
    self.bulletNum = num
    self.banPlayer = 0
    self.banTimer = 0
end

function WeaponSupply:randomSupply()
    local gun = GunConfig:getGunByItemId(self.gunId)
    if gun == nil then
        return
    end
    local effect = WeaponSupplyConfig:getEffectByQuality(gun.quality)
    local entityId = EngineWorld:addActorNpc(self.position, 0, gun.actor, function(entity)
        entity:setHeadName(gun.headName or "")
        entity:setSkillName("idle")
        entity:setHaloEffectName(effect or "")
        entity:setCanCollided(false)
    end)
    self.entityId = entityId
    SupplyManager:onAddWeaponSupply(self)
    self:initArea(0.8)
end

function WeaponSupply:onReceiver(player)
    local gun = GunConfig:getGunByItemId(self.gunId)
    if gun == nil then
        return
    end
    if self.banPlayer == player.userId then
        return
    end
    for type, equip_gun in pairs(player.equip_guns) do
        if tonumber(type) == gun.gunType then
            local equipGun = GunConfig:getGunByItemId(equip_gun.ItemId)
            if gun.quality > equipGun.quality then
                break
            end
            local bg = WeaponSupplyConfig:getImageByQuality(gun.quality)
            GamePacketSender:sendPixelGunChangeWeapon(player.rakssid, gun.image, bg, GameConfig.changeWeaponTime * 1000)
            self.pickingPlayer = player.userId
            self.isWaitting = true
            return
        end
    end
    self:onPlayerReceive(player.userId)
end

function WeaponSupply:onRemove()
    if self.entityId ~= 0 then
        SupplyManager:onRemoveWeaponSupply(self)
        EngineWorld:removeEntity(self.entityId)
        self.entityId = 0
    end
end

function WeaponSupply:onPlayerMove(player, x, y, z)
    if self:inArea(x, y, z) then
        if not self.isWaitting then
            self:onReceiver(player)
        end
    elseif self.pickingPlayer and self.pickingPlayer == player.userId then
        GamePacketSender:sendPixelGunChangeWeapon(player.rakssid, "", "", 0)
        self.isWaitting = false
        self.pickingPlayer = nil
    end
end

function WeaponSupply:getDistance(x, y, z)
    local pos = VectorUtil.newVector3(x, y, z)
    local distance = math.sqrt(MathUtil:distanceSquare3d(pos, self.position))
    return distance
end

function WeaponSupply:setWarning(player)
    self.inWarning = true
    GamePacketSender:sendPixelGunShowChickenWarning(player.rakssid, self.position, 3)
end

function WeaponSupply:onPlayerReceive(userId)
    local player = PlayerManager:getPlayerByUserId(userId)
    local item = {
        gun = self.gunId,
        bullet = self.bulletNum
    }
    self:onRemove()
    GamePacketSender:sendPixelGunHideChickenWarning(player.rakssid, 3)
    SupplyUtil:onPlayerPickup(SupplyUtil.TYPE.Gun, item, player)
end

function WeaponSupply:setBan(userId)
    self.banPlayer = userId
    self.banTimer = LuaTimer:schedule(function(userId)
        if self.banPlayer == userId then
            self.banPlayer = 0
            self.banTimer = 0
        end
    end, 1000, nil, userId)
end