---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaolai.
--- DateTime: 2019/8/28 14:04
---
PlayerClickBuyUpdateEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("ClickBuyUpdate", PlayerClickBuyUpdateEvent)

PlayerWatchAdUpdateInfoEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("WatchAdUpdateInfo", PlayerWatchAdUpdateInfoEvent)

PlayerSkyBlocShopOperateEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("SkyBlocShopOperate", PlayerSkyBlocShopOperateEvent)

SkyBlockReceiveTaskRewardEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("SkyBlockReceiveTask", SkyBlockReceiveTaskRewardEvent)

PlayerSellItemEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("SellItemEvent", PlayerSellItemEvent)

PlayerClickResourceIslandEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("ClickResourceIsland", PlayerClickResourceIslandEvent)

SkyBlockDareTaskOperateEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("DareTaskOperate", SkyBlockDareTaskOperateEvent)

PlayerBuyMoneyEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("BuyMoney", PlayerBuyMoneyEvent)

PlayerBuyChirstmasGiftEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("BuyChirstmasGift", PlayerBuyChirstmasGiftEvent)

PlayerGetGiftNumEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("GetGiftNum", PlayerGetGiftNumEvent)

PlayerOpenGiftEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("OpenGift", PlayerOpenGiftEvent)

PlayerCommonClickEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("SkyBlockCommonClick", PlayerCommonClickEvent)

SkyBlockRedSwitchClickEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("SkyBlockRedSwitchClick", SkyBlockRedSwitchClickEvent)

SkyBlockRedRichBtnClickEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("SkyBlockRedRichBtnClick", SkyBlockRedRichBtnClickEvent)