---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/9/20 11:05
---
DbUtil = {}
DbUtil.ACTORS_TAG = 1
DbUtil.MONEY_TAG = 2

DBManager:addMustLoadSubKey(DbUtil.ACTORS_TAG)
DBManager:addMustLoadSubKey(DbUtil.MONEY_TAG)

function DbUtil:getPlayerData(player, subkey)
    DBManager:getPlayerData(player.userId, subkey)
end

function DbUtil:savePlayerData(player, immediate)
    if player == nil then
        return
    end
    local actors_data = {}
    actors_data.actors = player.actors
    actors_data.lotteryTimes = player.lotteryTimes
    actors_data.LastLoginDay = player.LastLoginDay
    DBManager:savePlayerData(player.userId, DbUtil.ACTORS_TAG, actors_data, immediate)

    local money_data = {}
    money_data.money = player.money
    money_data.lookAdTime = player.lookAdTime or 0
    DBManager:savePlayerData(player.userId, DbUtil.MONEY_TAG, money_data, immediate)
end

function DbUtil:getDBDataRequire(player,subkey)
    DBManager:getPlayerData(player.userId, subkey)
end

return DbUtil