---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2019/8/16 10:45
---
---
GamePacketSender = {}

function GamePacketSender:sendHungryGameShowRespawnAd(rakssid,data)
    PacketSender:sendServerCommonData(rakssid, "TipDialogData", "HungryGameRespawnAd", data)
end

return GamePacketSender