---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2018/10/23 0023 12:15
---
XRailRouteConfig = {}
XRailRouteConfig.RailRoutes = {}

function XRailRouteConfig:OnInit(routes)
   self:initRoutes(routes)
end

function XRailRouteConfig:initRoutes(routes)
    for _, route in pairs(routes) do
        local item = {}
        item.ID = route.ID
        item.StartPos = XTools:CastToVector(route.StartX, route.StartY, route.StartZ)
        item.EndPos = XTools:CastToVector(route.EndX, route.EndY, route.EndZ)
        table.insert(self.RailRoutes, item)
    end
end

function XRailRouteConfig:getRouteConfig(id)
    for _, route in pairs(self.RailRoutes) do
        if route.ID == id then
             return route
        end
    end
end

return XRailRouteConfig