---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/12/19 14:53
---
require "util.RandomUtil"

RewardConfig = {}
RewardConfig.Rewards = {}

function RewardConfig:initConfig(configs)
    for _, config in pairs(configs) do
        local item = {
            Id = tonumber(config.Id) or 0,
            Name = config.Name or "",
            Image = config.Image or "",
            RewardId = tonumber(config.RewardId) or 0,
            RewardType = tonumber(config.RewardType) or 0,
            Count = tonumber(config.Count) or 0,
            Pool = tonumber(config.Pool) or 0,
            Weight = tonumber(config.Weight) or 0
        }

        self.Rewards[item.Id] = item
    end

end

function RewardConfig:getRewardById(id)
    return self.Rewards[id]
end

function RewardConfig:getRewardByIds(ids)
    local rewards = {}
    ids = StringUtil.split(ids, "#")
    for _, id in pairs(ids) do
        local reward = RewardConfig:getRewardById(tonumber(id))
        if reward ~= nil then
            table.insert(rewards, reward)
        end
    end
    return rewards
end

function RewardConfig:getRewardByPool(poolId)
    local pool = {}
    for _, reward in pairs(self.Rewards) do
        if reward.Pool == poolId then
            local item = {
                id = reward.Id,
                weight = reward.Weight
            }
            table.insert(pool, item)
        end
    end

    if not pool then
        return nil
    end

    local result = RandomUtil:randomItemByWeight(1, pool, false)
    if not result then
        return nil
    end
    return self.Rewards[result[1].id]
end

return RewardConfig
