---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaolai.
--- DateTime: 2018/11/12 17:03
---

ChangePriceConfig = {}
ChangePriceConfig.Price = {}

function ChangePriceConfig:init(config)
    for time, v in pairs(config) do
        self.Price[time] = tonumber(v.price)
    end
end

function ChangePriceConfig:getPriceByTime(time)
    return self.Price[tostring(time)]
end

return ChangePriceConfig