---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaolai.
--- DateTime: 2018/11/27 15:46
---

ClickChangePriceConfig = {}
ClickChangePriceConfig.Price = {}

function ClickChangePriceConfig:init(config)
    for time, v in pairs(config) do
        self.Price[time] = tonumber(v.price)
    end
end

function ClickChangePriceConfig:getPriceByTime(time)
    return self.Price[tostring(time)]
end

return ClickChangePriceConfig