---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/10/22 16:28
---

require "skill.BaseSkill"

HidingSkill = class("HidingSkill", BaseSkill)

function HidingSkill:onPlayerEffected(player)
    player:addEffect(PotionID.INVISIBILITY, self.duration, 1)
    player.isHiding = true
    player.HidingSkillTimer = LuaTimer:schedule(function (userId)
        local pPlayer = PlayerManager:getPlayerByUserId(userId)
        if pPlayer == nil then
            return
        end
        pPlayer.isHiding = false
        pPlayer.HidingSkillTimer = 0
    end, self.duration * 1000, nil, player.userId)
end

function HidingSkill:doAction()
    local players = self:getEffectPlayers()
    for _, player in pairs(players) do
        self:onPlayerEffected(player)
    end
end

return HidingSkill