---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 98632.
--- DateTime: 2019/10/20 9:17
---

ShopListener= {}

function ShopListener:init()
    C2SShopButtonClick:registerCallBack(self.onShopButtonClick)
end

function ShopListener.onShopButtonClick(userId,data)
    local player  = PlayerManager:getPlayerByUserId(userId)
    ShopManager:onButtonClick(player,data)
end

return ShopListener

