---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/12/19 11:17
---

require "Match"

DBDataListener = {}

function DBDataListener:init()
    BaseListener.registerCallBack(GetDataFromDBEvent, self.onGetDataFromDB)
    DBManager:setPlayerDBSaveFunction(function(player, immediate)
        DBUtil:savePlayerData(player, immediate)
    end)
end

function DBDataListener.onGetDataFromDB(player, role, data)
    player:initDataFromDB(data)
end

return DBDataListener