---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Yanzhuolin.
--- DateTime: 2019/4/15 14:51
---

GameSignIn = {}
GameSignIn.Status = {
    UN_RECEIVED = 0,
    ABLE_RECEIVED = 1,
    HAVE_RECEIVED = 2
}

GameSignIn.month = 12
GameSignIn.day = 31

function GameSignIn:initSignInData(player)
    self:checkIsInitData(player)
    if player.signIn_dayKey == "0" then
        --mean Available for collection
        return
    end
    --change to next SignIn
    local todayKey = DateUtil.getDate()
    if todayKey ~= player.signIn_dayKey then
        local nextConfig = SignInConfig:getNextSignInConfig(player.signIn_id)
        if not nextConfig then
            return
        end
        player.signIn_id = nextConfig.Id
        player.signIn_dayKey = "0"
    end
end

function GameSignIn:checkIsInitData(player)
    if player.signIn_start ~= GameConfig.signInStartTime or player.signIn_end ~= GameConfig.signInEndTime then
        self:reSetSignData(player)
    end
end

function GameSignIn:reSetSignData(player)
    print("reSetSignData userId == "..tostring(player.userId))
    player.signIn_id = 1
    player.signIn_dayKey = "0"
    player.signIn_start = GameConfig.signInStartTime
    player.signIn_end = GameConfig.signInEndTime
end

function GameSignIn:isInTheTime()
    local startTimeString = StringUtil.split(GameConfig.signInStartTime, "-")
    if not GameSignIn:dateIsNormal(startTimeString) then
        return false
    end
    local curStartTime = os.time({day = startTimeString[3], month = startTimeString[2], year = startTimeString[1], hour=0, min=0, sec=1})
    print("curStartTime == "..curStartTime)

    local endTimeString = StringUtil.split(GameConfig.signInEndTime, "-")
    if not GameSignIn:dateIsNormal(startTimeString) then
        return false
    end
    local curEndTime = os.time({day = endTimeString[3], month = endTimeString[2], year = endTimeString[1], hour=23, min=59, sec=59})
    print("curEndTime == "..curEndTime)
    local curTime = os.time()
    if curStartTime <= curTime and curEndTime >= curTime then
        return true
    end
    return false
end

function GameSignIn:dateIsNormal(timeString)
    if not timeString[1] or tonumber(timeString[1]) < 0 then
        return false
    end

    if not timeString[2] or tonumber(timeString[2]) > GameSignIn.month or tonumber(timeString[2]) < 0 then
        return false
    end

    if not timeString[3] or tonumber(timeString[3]) > GameSignIn.day or tonumber(timeString[3]) < 0 then
        return false
    end

    return true
end

function GameSignIn:sendToClient(player)
    local curId, status = self:getSignInStatus(player)
    local config = SignInConfig:getConfigById(curId)
    print("sendToClient  userId== "..tostring(player.userId))
    if not config then
        return
    end
    local data = {}
    data.NowOrder = config.Day
    data.Status = status
    data.IsShow = true
    data.IconShow = true 
    if status ~= self.Status.ABLE_RECEIVED or self:isInTheTime() == false then
        data.IsShow = false
        if data.NowOrder >= #SignInConfig.List or self:isInTheTime() == false then
            data.IconShow = false
        end
    end
    GamePacketSender:sendSkyBlockSignInData(player.rakssid, json.encode(data))
end

function GameSignIn:getSignInStatus(player)
    if player.signIn_dayKey == "0" then
        return player.signIn_id, self.Status.ABLE_RECEIVED
    end

    local todayId = DateUtil.getDate()
    if todayId == player.signIn_dayKey then
        return player.signIn_id, self.Status.HAVE_RECEIVED
    end
    return player.signIn_id, self.Status.UN_RECEIVED
end

function GameSignIn:receiveSignInReward(player, id)
    local curId, status = self:getSignInStatus(player)
    if id ~= curId then
        return
    end
    if status ~= self.Status.ABLE_RECEIVED then
        return
    end
    local config = SignInConfig:getConfigById(id)
    if not config then
        return
    end
   --ReportUtil:reportSignIn(player, id)
    --local reward = RewardConfig:getRewardById(config.RewardId)
    local rewardId = self:onPlayerGetReward(player, config)
    if rewardId then
        player.signIn_dayKey = DateUtil.getDate()
        GamePacketSender:sendSkyBlockRewardResult(player.rakssid, rewardId)
        self:sendToClient(player)
    end
end

function GameSignIn:onPlayerGetReward(player, reward)
    if not reward then
        return nil
    end
    if reward.RewardType == Define.TaskRewardType.item then
        player:addItem(reward.RewardId, reward.Num, reward.Meta, false, maxMeta)
    end
    if reward.RewardType == Define.TaskRewardType.money then
        local money = player.money + reward.Num
        player:setCurrency(money)
    end
    return reward.Id
end

return GameSignIn