---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/12/19 11:18
---

DBUtil = {}

function DBUtil:getPlayerData(player)
    DBManager:getPlayerData(player.userId, 2)
end

function DBUtil:savePlayerData(player, immediate)
    if player == nil then
        return
    end
    local data = {}
    data.money = player.hallMoney
    DBManager:savePlayerData(player.userId, 2, data, immediate)
end