---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2020/1/17 18:17
---
WallTextUtil = {}

function WallTextUtil.addWallText(rakssid, text, index)
    --local setting = WallTextConfig:getWallTextConfig(index)
    --if not setting then
    --    return
    --end
    --
    --local pos = VectorUtil.newVector3(setting.pos[1], setting.pos[2], setting.pos[3])
    ----WallTextUtil.deleteWallText(rakssid, index)
    --HostApi.addWallText(rakssid, setting.type, setting.timeLeft, text, pos, setting.scale, setting.yaw, setting.pitch,
    --        { setting.color[1], setting.color[2], setting.color[3], setting.color[4] })

    GamePacketSender:SendAddWallText(rakssid, text, index)
end

function WallTextUtil.addRowWallText(rakssid, rankId, info, titleText)
    local row = info.rank
    local first = tonumber(rankId .. "000" .. row)
    local last = tonumber(rankId .. "004" .. row)

    local combineData = {}

    local col = 1
    for i = first, last, 10 do
        local key = titleText[col]
        if key and info[key] then
            if key == "userName" then
                info[key] = Utility.toAbbreviateString(tostring(info[key]))
            end
            table.insert(combineData, info[key] .. "," .. i)
        end
        col = col + 1
    end

    PacketSender:sendLuaCommonData(rakssid, "AddRowWallText", table.concat(combineData, "&"))
end

--function WallTextUtil.deleteWallText(rakssid, index)
--    local setting = WallTextConfig:getWallTextConfig(index)
--    if not setting then
--        return
--    end
--
--    local pos = VectorUtil.newVector3(setting.pos[1], setting.pos[2], setting.pos[3])
--    HostApi.deleteWallText(rakssid, pos)
--end

--function WallTextUtil.deleteAllWallText(rakssid)
--    for _, setting in pairs(WallTextConfig.settings) do
--        local pos = VectorUtil.newVector3(setting.pos[1], setting.pos[2], setting.pos[3])
--        HostApi.deleteWallText(rakssid, pos)
--    end
--end

return WallTextUtil