---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2020/1/10 15:02
---
GameState = class("GameState")

function GameState:enter()
    self.GameStatus = Define.GameStatus.Unknown
end

function GameState:update()
    --TODO
end

function GameState:leave()
    --TODO
end

function GameState:onPlayerReady(player)
    --TODO
end

return GameState