---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/9/20 11:05
---
local function LogShareDataKey(player)
    if DbUtil.CanSavePlayerData(player, DbUtil.TAG_SHAREDATA) then
        if player.money and player.exp and player.level and player.area and player.off_lineTime and player.other_unlockTime then

            HostApi.log("SavePlayerShareData userId: " .. tostring(player.userId) .. " money: " .. player.money .. " exp: " .. player.exp .. " level: " .. player.level
                    .. " area: " .. player.area .. " off_lineTime: " .. player.off_lineTime .. " other_unlockTime: " .. player.other_unlockTime)
        end

        if player.products then
            for _, npc in pairs(player.products) do
                if npc.Id and npc.level and npc.Time then
                    HostApi.log("SavePlayerShareData product: npcId: " .. npc.Id .. " npcLevel: " .. npc.level .. " npcTime: " .. npc.Time)
                end
            end
        end
    end
end

local function LogBlockKey(player)
    local targetManorInfo = GameMatch:getUserManorInfo(player.userId)
    if targetManorInfo == nil then
        return
    end

    local blockInfo = targetManorInfo.manorBlock
    local updateBlock = targetManorInfo.updateBlock
    local attachUpdateBlock = targetManorInfo.attachUpdateBlock
    local subKeyInfo = {}

    local logManorBlock = {}
    local logUpdataBlock = {}
    local logAttachUpdateBlock = {}

    if updateBlock then
        for _, block in pairs(updateBlock) do
            local key = block.pos.x .. ":" .. block.pos.y .. ":" .. block.pos.z
            local value = block.id .. ":" .. block.meta
            local subKey = player:generateSubKey(key, value)
            if subKey then
                -- HostApi.log("SavePlayerBlockData updateBlock " .. subKey)
                if DbUtil.CanSavePlayerData(player, subKey) and not targetManorInfo.newKeyLock[subKey] then
                    if subKeyInfo[subKey] == nil then
                        subKeyInfo[subKey] = {}
                    end

                    subKeyInfo[subKey][tostring(key)] = tostring(value)

                    if logUpdataBlock[subKey] == nil then
                        logUpdataBlock[subKey] = {}
                    end
                    logUpdataBlock[subKey][tostring(key)] = tostring(value)
                end
            end
        end
    end

    if attachUpdateBlock then
        for _, block in pairs(attachUpdateBlock) do
            local rPos = targetManorInfo:aPosToRPos(block.aPos)
            local key = rPos.x .. ":" .. rPos.y .. ":" .. rPos.z
            local value = block.id .. ":" .. block.meta
            local subKey = player:generateSubKey(key, value)
            if subKey then
                -- HostApi.log("SavePlayerBlockData attachUpdateBlock " .. subKey)
                if DbUtil.CanSavePlayerData(player, subKey) and not targetManorInfo.newKeyLock[subKey] then
                    if subKeyInfo[subKey] == nil then
                        subKeyInfo[subKey] = {}
                    end

                    subKeyInfo[subKey][tostring(key)] = tostring(value)

                    if logAttachUpdateBlock[subKey] == nil then
                        logAttachUpdateBlock[subKey] = {}
                    end
                    logAttachUpdateBlock[subKey][tostring(key)] = tostring(value)
                end
            end
        end
    end

    if blockInfo then
        for key, value in pairs(blockInfo) do
            local subKey = player:generateSubKey(key, value)
            if subKey then
                -- HostApi.log("SavePlayerBlockData blockInfo " .. subKey)
                if DbUtil.CanSavePlayerData(player, subKey) and not targetManorInfo.newKeyLock[subKey] then
                    if subKeyInfo[subKey] == nil then
                        subKeyInfo[subKey] = {}
                    end

                    subKeyInfo[subKey][tostring(key)] = tostring(value)

                    if logManorBlock[subKey] == nil then
                        logManorBlock[subKey] = {}
                    end
                    logManorBlock[subKey][tostring(key)] = tostring(value)
                end
            end
        end
    end

    local countAll = {}
    local countAllStr = "Save BlockData All Data: userId " .. tostring(player.userId)
    for subKey, data in pairs(subKeyInfo) do
        if countAll[subKey] == nil then
            countAll[subKey] = 0
            countAllStr = countAllStr .. " [" .. subKey .. "]: "
        end

        for _, _ in pairs(data) do
            countAll[subKey] = countAll[subKey] + 1
        end

        countAllStr = countAllStr .. tostring(countAll[subKey])

        if targetManorInfo.logBlock[subKey] then
            if countAll[subKey] < targetManorInfo.logBlock[subKey] then
                HostApi.log("[SCRIPT_EXCEPTION] Block may be lost check it !")
                HostApi.log("targetManorInfo status: " .. targetManorInfo.release_status)

                local saveBlockStr = "Save Block Info subKey: " .. tostring(subKey) .. " num: " .. tostring(countAll[subKey])
                for hash, value in pairs(data) do
                    saveBlockStr = saveBlockStr .. " [" .. hash .. ":" .. value .. "]"
                end
                HostApi.log(saveBlockStr)

                local loadBlockStr = "Load Block Info subKey: " .. tostring(subKey) .. " num: " .. tostring(targetManorInfo.logBlock[subKey])
                if targetManorInfo.loadBlockRecord and targetManorInfo.loadBlockRecord[subKey] then
                    for hash, value in pairs(targetManorInfo.loadBlockRecord[subKey]) do
                        loadBlockStr = loadBlockStr .. " [" .. hash .. ":" .. value .. "]"
                    end
                end
                HostApi.log(loadBlockStr)
            end
        end
    end

    HostApi.log(countAllStr)

    local countManorAll = {}
    local countManorAllStr = "Save BlockData Manor Data: userId " .. tostring(player.userId)
    for subKey, data in pairs(logManorBlock) do
        if countManorAll[subKey] == nil then
            countManorAll[subKey] = 0
            countManorAllStr = countManorAllStr .. " [" .. subKey .. "]: "
        end

        for _, _ in pairs(data) do
            countManorAll[subKey] = countManorAll[subKey] + 1
        end

        countManorAllStr = countManorAllStr .. tostring(countManorAll[subKey])
    end

    HostApi.log(countManorAllStr)

    local countUpdateAll = {}
    local countUpdateAllStr = "Save BlockData Update Data: userId " .. tostring(player.userId)
    for subKey, data in pairs(logUpdataBlock) do
        if countUpdateAll[subKey] == nil then
            countUpdateAll[subKey] = 0
            countUpdateAllStr = countUpdateAllStr .. " [" .. subKey .. "]: "
        end

        for _, _ in pairs(data) do
            countUpdateAll[subKey] = countUpdateAll[subKey] + 1
        end

        countUpdateAllStr = countUpdateAllStr .. tostring(countUpdateAll[subKey])
    end

    HostApi.log(countUpdateAllStr)

    local countUpdateAttachAll = {}
    local countUpdateAttachAllStr = "Save BlockData Update Attach Data: userId " .. tostring(player.userId)
    for subKey, data in pairs(logAttachUpdateBlock) do
        if countUpdateAttachAll[subKey] == nil then
            countUpdateAttachAll[subKey] = 0
            countUpdateAttachAllStr = countUpdateAttachAllStr .. " [" .. subKey .. "]: "
        end

        for _, _ in pairs(data) do
            countUpdateAttachAll[subKey] = countUpdateAttachAll[subKey] + 1
        end

        countUpdateAttachAllStr = countUpdateAttachAllStr .. tostring(countUpdateAttachAll[subKey])
    end

    HostApi.log(countUpdateAttachAllStr)
end

---判断当前领地相关的信息是否能保存
local function checkManorAboutDataCanSave(player)
    local manorInfo = GameMatch:getUserManorInfo(player.userId)
    if not manorInfo then
        return nil
    end
    if manorInfo.isNotInPartyCreateOrOver == false then
        HostApi.log("manor cannot save isNotInPartyCreateOrOver " .. tostring(player.userId))
        return nil
    end
    if manorInfo.release_status ~= Define.manorRelese.Not then
        if manorInfo.isInRoomForceRelease == true then
            HostApi.log("manor cannot save isInRoomForceRelease " .. tostring(player.userId))
            return nil
        end
        if player.isReady then
            if player.manorIndex <= 0 then
                HostApi.log("manor cannot save when manor is in release_status and player's manorIndex error userId: " .. tostring(player.userId) .. " " .. player.manorIndex)
                return
            end
            if player.isNotInPartyCreateOrOver then
                if tostring(player.userId) == tostring(player.target_user_id) then
                    HostApi.log("manor cannot save when manor is in release_status check it ManorUserId: "
                            .. tostring(manorInfo.userId) .. " userId: " .. tostring(player.userId) .. " targetUserId: " .. tostring(player.target_user_id))
                else
                    HostApi.log("manor cannot save when manor is in release_status and player may be is visiting other  " .. tostring(player.userId) .. " " .. tostring(player.target_user_id))
                end
            else
                HostApi.log("manor cannot save when manor is in release_status and player is ready and player is in party create or over userId: " .. tostring(player.userId))
            end
        else
            HostApi.log("manor cannot save when manor is in release_status and player is not ready userId: " .. tostring(player.userId))
        end
        return nil
    end
    return manorInfo
end

DbUtil = {}
DbUtil.TAG_PLAYER = "player"
DbUtil.TAG_SHAREDATA = "ShareData"
DbUtil.TAG_MIAN_LINE = "main_line"

DbUtil.TAG_MANOR = "manor"
DbUtil.TAG_BLOCK_PRE = "block"
DbUtil.TAG_CHEST = "chest"
DbUtil.TAG_FURNACE = "furnace"
DbUtil.TAG_SIGN = "sign"
DbUtil.DIALOG_TIPS = "dialogTips"
DbUtil.TAG_ACTOR = "actor"

DBManager:addMustLoadSubKey(DbUtil.TAG_PLAYER)
DBManager:addMustLoadSubKey(DbUtil.TAG_SHAREDATA)
DBManager:addMustLoadSubKey(DbUtil.TAG_MIAN_LINE)
DBManager:addMustLoadSubKey(DbUtil.TAG_MANOR)
DBManager:addMustLoadSubKey(DbUtil.TAG_CHEST)
DBManager:addMustLoadSubKey(DbUtil.TAG_FURNACE)
DBManager:addMustLoadSubKey(DbUtil.TAG_SIGN)
DBManager:addMustLoadSubKey(DbUtil.DIALOG_TIPS)
DBManager:addMustLoadSubKey(DbUtil.TAG_ACTOR)

function DbUtil.getPlayerData(userId, subKey)
    DBManager:getPlayerData(userId, subKey)
end

function DbUtil.initDataFromDB(userId, subKey, data)
    -- DBManager:addCache(userId, subKey, data)
    HostApi.log("initDataFromDB " .. tostring(userId) .. " " .. tostring(subKey))

    if subKey == DbUtil.TAG_PLAYER then
        local player = PlayerManager:getPlayerByUserId(userId)
        if player then
            DBManager:addCache(userId, subKey, data)
            player:initDataFromDB(data)
            GameParty:sendPlayerPartyData(userId)
        end
    end

    if subKey == DbUtil.TAG_MANOR then

        local targetManorInfo = GameMatch:getUserManorInfo(userId)
        if targetManorInfo ~= nil then
            DBManager:addCache(userId, subKey, data)
            targetManorInfo:initManorInfoFromDB(data)
        end
    end

    if string.find(subKey, DbUtil.TAG_BLOCK_PRE) ~= nil then

        local targetManorInfo = GameMatch:getUserManorInfo(userId)
        if targetManorInfo ~= nil then
            DBManager:addCache(userId, subKey, data)
            targetManorInfo:initBlockFromDB(data, subKey)
        end
    end

    if subKey == DbUtil.TAG_MIAN_LINE then
        local player = PlayerManager:getPlayerByUserId(userId)
        if player then
            DBManager:addCache(userId, subKey, data)
            player:initMainLineDataFromDB(data)
            player.taskController:init()
            player:checkAllChangeDataToMember()
        end
    end

    if subKey == DbUtil.TAG_CHEST then

        local targetManorInfo = GameMatch:getUserManorInfo(userId)
        if targetManorInfo ~= nil then
            DBManager:addCache(userId, subKey, data)
            targetManorInfo:initChestDataFromDB(data)
        end
    end

    if subKey == DbUtil.TAG_SHAREDATA then
        local player = PlayerManager:getPlayerByUserId(userId)
        if player then
            DBManager:addCache(userId, subKey, data)
            player:initShareDataFromDB(data)
            player.taskController:init()
            player:checkAllChangeDataToMember()
            GameParty:sendPlayerPartyData(userId)
        end
    end

    if subKey == DbUtil.TAG_FURNACE then

        local targetManorInfo = GameMatch:getUserManorInfo(userId)
        if targetManorInfo ~= nil then
            DBManager:addCache(userId, subKey, data)
            targetManorInfo:initFurnaceDataFromDB(data)
        end
    end

    if subKey == DbUtil.TAG_SIGN then

        local targetManorInfo = GameMatch:getUserManorInfo(userId)
        if targetManorInfo ~= nil then
            DBManager:addCache(userId, subKey, data)
            targetManorInfo:initSignPostTextDataFromDB(data)
        end
    end

    if subKey == DbUtil.DIALOG_TIPS then
        local player = PlayerManager:getPlayerByUserId(userId)
        if player then
            DBManager:addCache(userId, subKey, data)
            player:initDialogTipsDataFromDB(data)
        end
    end

    if subKey == DbUtil.TAG_ACTOR then
        local targetManorInfo = GameMatch:getUserManorInfo(userId)
        if targetManorInfo ~= nil then
            DBManager:addCache(userId, subKey, data)
            targetManorInfo:initActorFromDB(data)
        end
    end
end

function DbUtil.CanSavePlayerData(player, subKey)
    return DBManager:isLoadDataFinished(player.userId, subKey)
end

function DbUtil.savePlayerData(player, immediate)
    if player == nil then
        return
    end
    if not immediate then
        SaveDBTaskQueue.addTask(player, DbUtil.SavePlayerGameData)
        SaveDBTaskQueue.addTask(player, DbUtil.SavePlayerManorData)
        SaveDBTaskQueue.addTask(player, DbUtil.SavePlayerBlockData)
        SaveDBTaskQueue.addTask(player, DbUtil.SavePlayerMainLineData)
        SaveDBTaskQueue.addTask(player, DbUtil.SavePlayerChestData)
        SaveDBTaskQueue.addTask(player, DbUtil.SavePlayerShareData)
        SaveDBTaskQueue.addTask(player, DbUtil.SavePlayerFurnaceData)
        SaveDBTaskQueue.addTask(player, DbUtil.SavePlayerSignPostData)
        SaveDBTaskQueue.addTask(player, DbUtil.SavePlayerDialogTipsData)
        SaveDBTaskQueue.addTask(player, DbUtil.SavePlayerActorData)
        return
    end
    SaveDBTaskQueue.clearTask(player.userId)
    DbUtil.SavePlayerGameData(player, immediate)
    DbUtil.SavePlayerManorData(player, immediate)
    DbUtil.SavePlayerBlockData(player, immediate)
    DbUtil.SavePlayerMainLineData(player, immediate)
    DbUtil.SavePlayerChestData(player, immediate)
    DbUtil.SavePlayerShareData(player, immediate)
    DbUtil.SavePlayerFurnaceData(player, immediate)
    DbUtil.SavePlayerSignPostData(player, immediate)
    DbUtil.SavePlayerDialogTipsData(player, immediate)
    DbUtil.SavePlayerActorData(player, immediate)
    -- log
    --LogShareDataKey(player)
    --player:LogInventoryInfo()
    --LogBlockKey(player)
end

function DbUtil.SavePlayerGameData(player, immediate)
    -- vistor not save
    local targetManorInfo = GameMatch:getUserManorInfo(player.userId)
    if targetManorInfo == nil then
        return
    end

    if not DbUtil.CanSavePlayerData(player, DbUtil.TAG_PLAYER) then
        return
    end

    local data = {}
    if player.respawnPos and
            player.respawnPos.x >= 0 and player.respawnPos.x <= GameConfig.manorMax and
            player.respawnPos.y >= 0 and player.respawnPos.y <= GameConfig.manorMax and
            player.respawnPos.z >= 0 and player.respawnPos.z <= GameConfig.manorMax then
        data.respawnPos = { x = player.respawnPos.x, y = player.respawnPos.y, z = player.respawnPos.z }
    else
        local pos = GameConfig:getOriginPosByManorIndex(player.manorIndex) or GameConfig:getInitPosByManorIndex(player.manorIndex)
        if pos then
            player:moveHome(pos, false)
            data.respawnPos = { x = player.respawnPos.x, y = player.respawnPos.y, z = player.respawnPos.z }
        else
            data.respawnPos = { x = GameConfig.manorMax / 2, y = GameConfig.manorMax, z = GameConfig.manorMax / 2 }
        end
    end
    data.oldExp = player.oldExp
    data.loginData = player.loginData
    data.giveLoveLastNum = player.giveLoveLastNum
    data.bulletin = player.bulletin
    DBManager:savePlayerData(player.userId, DbUtil.TAG_PLAYER, data, immediate)
end

function DbUtil.SavePlayerDialogTipsData(player, immediate)
    -- vistor not save
    if not DbUtil.CanSavePlayerData(player, DbUtil.DIALOG_TIPS) then
        return
    end

    local data = {}
    data.tips = player.tips
    data.tipsUserId = player.tipsUserId
    DBManager:savePlayerData(player.userId, DbUtil.DIALOG_TIPS, data, immediate)
end

function DbUtil.SavePlayerManorData(player, immediate)
    if not DbUtil.CanSavePlayerData(player, DbUtil.TAG_MANOR) then
        return
    end
    -- vistor not save
    local targetManorInfo = checkManorAboutDataCanSave(player)
    if not targetManorInfo then
        return
    end

    local data = {}
    data.treeInfo = targetManorInfo.treeInfo
    data.dirtInfo = targetManorInfo.dirtInfo
    data.cropsInfo = targetManorInfo.cropsInfo

    DBManager:savePlayerData(player.userId, DbUtil.TAG_MANOR, data, immediate)
end

function DbUtil.SavePlayerBlockData(player, immediate)
    local targetManorInfo = checkManorAboutDataCanSave(player)
    if not targetManorInfo then
        return
    end

    local blockInfo = targetManorInfo.manorBlock
    local updateBlock = targetManorInfo.updateBlock
    local attachUpdateBlock = targetManorInfo.attachUpdateBlock
    local subKeyInfo = {}

    if updateBlock then
        for _, block in pairs(updateBlock) do
            local key = block.pos.x .. ":" .. block.pos.y .. ":" .. block.pos.z
            local value = block.id .. ":" .. block.meta
            local subKey = player:generateSubKey(key, value)
            if subKey then
                -- HostApi.log("SavePlayerBlockData updateBlock " .. subKey)
                if DbUtil.CanSavePlayerData(player, subKey) and not targetManorInfo.newKeyLock[subKey] then
                    if subKeyInfo[subKey] == nil then
                        subKeyInfo[subKey] = {}
                    end

                    subKeyInfo[subKey][tostring(key)] = tostring(value)
                end
            end
        end
    end

    if attachUpdateBlock then
        for _, block in pairs(attachUpdateBlock) do
            local rPos = targetManorInfo:aPosToRPos(block.aPos)
            local key = rPos.x .. ":" .. rPos.y .. ":" .. rPos.z
            local value = block.id .. ":" .. block.meta
            local subKey = player:generateSubKey(key, value)
            if subKey then
                -- HostApi.log("SavePlayerBlockData attachUpdateBlock " .. subKey)
                if DbUtil.CanSavePlayerData(player, subKey) and not targetManorInfo.newKeyLock[subKey] then
                    if subKeyInfo[subKey] == nil then
                        subKeyInfo[subKey] = {}
                    end

                    subKeyInfo[subKey][tostring(key)] = tostring(value)
                end
            end
        end
    end

    if blockInfo then
        for key, value in pairs(blockInfo) do
            local subKey = player:generateSubKey(key, value)
            if subKey then
                -- HostApi.log("SavePlayerBlockData blockInfo " .. subKey)
                if DbUtil.CanSavePlayerData(player, subKey) and not targetManorInfo.newKeyLock[subKey] then
                    if subKeyInfo[subKey] == nil then
                        subKeyInfo[subKey] = {}
                    end

                    subKeyInfo[subKey][tostring(key)] = tostring(value)
                end
            end
        end
    end

    local countAll = {}
    for subKey, data in pairs(subKeyInfo) do

        if countAll[subKey] == nil then
            countAll[subKey] = 0
        end

        local dbData = {}
        dbData.block = {}
        for key, value in pairs(data) do
            -- local dataStr = key .. ":" .. value
            -- table.insert(dbData.block, dataStr)
            dbData.block[key] = value
            countAll[subKey] = countAll[subKey] + 1
        end

        if targetManorInfo.logBlock[subKey] then
            if countAll[subKey] < targetManorInfo.logBlock[subKey] then
                HostApi.log("[SCRIPT_EXCEPTION] Block may be lost check it ! will not save this subKey: " .. tostring(player.userId) .. " " .. subKey)
            else
                DBManager:savePlayerData(player.userId, subKey, dbData, immediate)
            end
        else
            DBManager:savePlayerData(player.userId, subKey, dbData, immediate)
        end
        -- DBManager:savePlayerData(player.userId, subKey, dbData, immediate)
    end
end

function DbUtil.SavePlayerMainLineData(player, immediate)
    if not DbUtil.CanSavePlayerData(player, DbUtil.TAG_MIAN_LINE) or not DbUtil.CanSavePlayerData(player, DbUtil.TAG_SHAREDATA) then
        return
    end

    player.taskController:transformToPlayerTaskData(player)
    local data = {}
    data.progressesLevel = player.progressesLevel
    data.mainline_tasks = player.mainline_tasks
    data.dare_tasks = player.dare_tasks
    data.maxDareTimes = player.maxDareTimes
    data.curDareTimes = player.curDareTimes
    data.nextTaskTime = player.nextTaskTime
    data.LastLoginDate = player.LastLoginDate
    data.free_refresh_times = player.free_refresh_times
    data.dareIsUnLock = player.dareIsUnLock
    data.taskIsLandLevel = player.taskIsLandLevel

    DBManager:savePlayerData(player.userId, DbUtil.TAG_MIAN_LINE, data, immediate)
end

function DbUtil.SavePlayerChestData(player, immediate)
    if not DbUtil.CanSavePlayerData(player, DbUtil.TAG_CHEST) then
        return
    end

    local targetManorInfo = GameMatch:getUserManorInfo(player.userId)
    if not targetManorInfo then
        return
    end

    local data = {}
    targetManorInfo:updateAllChestData(player)
    data.chest = targetManorInfo.chest
    data.isInitBox = targetManorInfo.isInitBox
    DBManager:savePlayerData(player.userId, DbUtil.TAG_CHEST, data, immediate)
end

function DbUtil.SavePlayerShareData(player, immediate)
    if not DbUtil.CanSavePlayerData(player, DbUtil.TAG_SHAREDATA) then
        return
    end

    local data = {}
    if player.isLife then
        data.hp = player:getHealth()
        data.maxHp = player:getMaxHealth()
    else
        data.hp = GameConfig.initHP
        data.maxHp = GameConfig.initHP
    end
    data.foodLevel = player.foodLevel
    player:setInventory()
    data.inventory = player.inventory
    data.money = player.money
    data.current_day_money = player.current_day_money
    if data.money < 0 then
        data.money = 0
    end
    data.exp = player.exp
    data.level = player.level
    data.area = player.area
    data.products = player.products
    data.books = player.books
    data.getRewardTick = player.getRewardTick
    data.off_lineTime = player.off_lineTime
    data.privilege = player.privilege
    data.other_unlockTime = player.other_unlockTime
    data.backMiningAreaTime = player.backMiningAreaTime
    data.backProductTime = player.backProductTime
    data.isSky = player.isSky
    data.signIn_dayKey = player.signIn_dayKey
    data.signIn_id = player.signIn_id
    data.signIn_start = player.signIn_start
    data.signIn_end = player.signIn_end
    data.havePriImgList = player.havePriImgList
    data.notShowSwitchRed = player.notShowSwitchRed
    data.notShowRichRed = player.notShowRichRed
    DBManager:savePlayerData(player.userId, DbUtil.TAG_SHAREDATA, data, immediate)
end

function DbUtil.SavePlayerFurnaceData(player, immediate)
    if not DbUtil.CanSavePlayerData(player, DbUtil.TAG_FURNACE) then
        return
    end
    local targetManorInfo = checkManorAboutDataCanSave(player)
    if not targetManorInfo then
        return
    end
    local data = {}
    targetManorInfo:updateAllFurnaceData(player)
    data.furnace = targetManorInfo.furnace
    DBManager:savePlayerData(player.userId, DbUtil.TAG_FURNACE, data, immediate)
end

function DbUtil.SavePlayerSignPostData(player, immediate)
    if not DbUtil.CanSavePlayerData(player, DbUtil.TAG_SIGN) then
        print("SavePlayerSignPostData DBManager.Caches[key] == nil")
        return
    end
    local targetManorInfo = checkManorAboutDataCanSave(player)
    if not targetManorInfo then
        return
    end

    local data = {}
    data.signPost = targetManorInfo.signPost
    DBManager:savePlayerData(player.userId, DbUtil.TAG_SIGN, data, immediate)
end

function DbUtil.SavePlayerActorData(player, immediate)
    if not DbUtil.CanSavePlayerData(player, DbUtil.TAG_ACTOR) then
        print("SavePlayerActorData DBManager.Caches[key] == nil")
        return
    end
    local targetManorInfo = checkManorAboutDataCanSave(player)
    if not targetManorInfo then
        return
    end
    local data = {}
    data.ActorCache = targetManorInfo.ActorCache
    DBManager:savePlayerData(player.userId, DbUtil.TAG_ACTOR, data, immediate)
end

return DbUtil