---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/4/21 11:31
---
local TaskQueue = {}

local function removeTask(userId, func)
    for pos, task in pairs(TaskQueue) do
        if task.userId == userId and task.func == func then
            table.remove(TaskQueue, pos)
            break
        end
    end
end

---服务器防止卡帧延迟保持数据处理队列
SaveDBTaskQueue = {}

---增加一个任务到队列
function SaveDBTaskQueue.addTask(player, func)
    removeTask(player.userId, func)
    table.insert(TaskQueue, { userId = player.userId, func = func })
end

---清除某个玩家的所有任务
---主要用于玩家退出保存所有数据之前清理任务，可减少处理的请求
function SaveDBTaskQueue.clearTask(userId)
    local remove = function()
        for pos, task in pairs(TaskQueue) do
            if task.userId == userId then
                table.remove(TaskQueue, pos)
                return true
            end
        end
        return false
    end
    while remove() do
        LogUtil.log("[SaveDBTaskQueue] clearTask " .. tostring(userId))
    end
end

---延迟更新，做到每一帧处理队列一次
local function delayUpdate()
    LuaTimer:schedule(function()
        SaveDBTaskQueue.onProcess()
    end, 20)
end

---处理队列任务，一次只能处理200毫秒，超过时间延迟到下一次处理
function SaveDBTaskQueue.onProcess()
    if #TaskQueue == 0 then
        delayUpdate()
        return
    end
    local startTime = tonumber(HostApi.curTimeString())
    local currentTime = startTime
    while currentTime - startTime < 200 do  --每次处理时长最大是200毫秒，保证服务器不卡帧
        local task = TaskQueue[1]
        local player = PlayerManager:getPlayerByUserId(task.userId)
        if player then
            task.func(player, true)
        end
        table.remove(TaskQueue, 1)
        if #TaskQueue == 0 then
            break
        end
        currentTime = tonumber(HostApi.curTimeString())
    end
    delayUpdate()
end

SaveDBTaskQueue.onProcess()