---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/11/4 16:20
---
BaseAreaEvent = class()

function BaseAreaEvent:ctor(config)
    self.config = config
    self.eventId = config.eventId
    self.startTime = os.time()
    self.Players = {}
end

function BaseAreaEvent:onStart()
    self.startTime = os.time()
    self:playSound(self.config.eventSound[1])
    Utility.playEffect(self.config.eventEffect[1])
    EngineWorld:stopWorldTime(self.config.serverTime[1])
end

function BaseAreaEvent:enterArea(player)
    if not self.Players[tostring(player.userId)] then
        self.Players[tostring(player.userId)] = player
        self:onEnterArea(player)
        --print("BaseAreaEvent:enterArea " .. tostring(player.userId))
    end
end

function BaseAreaEvent:onEnterArea(player)
    --TODO
end

function BaseAreaEvent:leaveArea(player)
    if self.Players[tostring(player.userId)] then
        self.Players[tostring(player.userId)] = nil
        self:onLeaveArea(player)
        --print("BaseAreaEvent:leaveArea " .. tostring(player.userId))
    end
end

function BaseAreaEvent:onLeaveArea(player)
    --TODO
end

function BaseAreaEvent:onTick(ticks)
    --TODO:禁止玩家进入区域
end

function BaseAreaEvent:randomPos()
    local num = #self.config.areaTeleportPos
    local index = math.random(num)
    local pos = self.config.areaTeleportPos[index]
    --print(string.format("BaseAreaEvent:randomPos %f %f %f", pos.x, pos.y, pos.z))
    return VectorUtil.newVector3(pos.x, pos.y, pos.z)
end

function BaseAreaEvent:playSound(soundId)
    for _, vPlayer in pairs(PlayerManager:getPlayers()) do
        HostApi.sendPlaySound(vPlayer.rakssid, soundId)
    end
end

--function BaseAreaEvent:playEffect(id)
--    local config = EffectConfig:getEffectConfig(id)
--    if config == nil then
--        return
--    end
--    local pos = VectorUtil.newVector3(config.effectPos[1], config.effectPos[2], config.effectPos[3])
--    EngineWorld:addSimpleEffect(config.name, pos, config.effectYaw, config.liveTime, 0, config.scale)
--    --print(string.format("BaseAreaEvent:playEffect liveTime:%d", config.liveTime))
--end

function BaseAreaEvent:onEnd()
    self:playSound(self.config.eventSound[2])
    Utility.playEffect(self.config.eventEffect[2])
    self:doReward()
    EngineWorld:stopWorldTime(self.config.serverTime[2])
end

function BaseAreaEvent:isEnd()
    return self:getLiveTime() >= self.config.eventTime
end

function BaseAreaEvent:doReward()
    --TODO
end

function BaseAreaEvent:getLiveTime()
    local diff = os.time() - self.startTime
    --print("BaseAreaEvent:getLiveTime " .. diff)
    return diff
end

return BaseAreaEvent