---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/4/28 10:53
---
GamePacketSender = {}

function GamePacketSender:sendShowDarkMask(rakssid)
    local data = DataBuilder.new():fromTable({ duration = 2000 }):getData()
    PacketSender:sendLuaCommonData(rakssid, "ShowDarkMask", data)
end