---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/6/29 0029 20:52
---
ArrowRune = class("ArrowRune")

function ArrowRune:ctor(config)
    self.damage = tonumber(config.Value1)
end

function ArrowRune:onAttack(attacker, hurtValue, damageType)
    if not attacker then
        return
    end
    if damageType == "arrow" then
        hurtValue.value = hurtValue.value + self.damage
    end
end
