---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/6/29 0029 20:53
---
KnockBackRune = class("KnockBackRune")

function KnockBackRune:ctor(config)
    self.distance = tonumber(config.Value1)
end

function KnockBackRune:onInit(player)
    player.info:setValue("runeAddKnockBackValue", tonumber(player.info:getValue("runeAddKnockBackValue")) + self.distance)
end
