---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/6/29 0029 20:54
---
MaxHpRune = class("MaxHpRune")

function MaxHpRune:ctor(config)
    self.addHp = tonumber(config.Value1)
end

function MaxHpRune:onInit(player)
    player:changeMaxHealth(player:getMaxHealth() + self.addHp)
end

function MaxHpRune:onRespawn(player)
    player:changeMaxHealth(player:getMaxHealth() + self.addHp)
end
