---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/6/29 0029 20:55
---
MaxHpWithBeginRune = class("MaxHpWitchBeginRune")

function MaxHpWithBeginRune:ctor(config)
    self.addHp = tonumber(config.Value1)
    self.time = tonumber(config.Value2) * 60
    self.isInvalid = false ---是否已经失效了
end

function MaxHpWithBeginRune:onTick(player, ticks)
    if self.isInvalid then
        return
    end
    if self.time >= ticks then
        if player.isRespawn then
            player:changeMaxHealth(player:getMaxHealth() + self.addHp)
        end
    else
        ---符文失效了并且增加过生命值，需要减少玩家的最大生命值
        if not player.isRespawn then
            player:changeMaxHealth(player:getMaxHealth() - self.addHp)
        end
        LuaTimer:schedule(function()
            self.isInvalid = true
        end, 0)
    end
end