---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/6/29 0029 20:54
---
ReduceHurtRune = class("ReduceHurtRune")

function ReduceHurtRune:ctor(config)
    self.defence = tonumber(config.Value1)
end

function ReduceHurtRune:onHurted(hurter, hurtValue)
    hurtValue.value = hurtValue.value - hurtValue.value * self.defence / 10000.00
end
