---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/10/12 0012 10:09
---
EventObservable = class("EventObservable") ---@class EventObservable

function EventObservable:ctor()

end

function EventObservable:registerEvent(event, func)
    Listener.registerCallBack(event, func)
end

function EventObservable:registerDataCallBack(key, callback, processor)
    CommonDataEvents:registerCallBack(key, callback, processor)
end

return EventObservable