---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/5/15 0015 10:47
---
--获取数据库数据
GetDataFromDBEvent = IScriptEvent.new()
--获取数据库数据失败
GetDBDataErrorEvent = IScriptEvent.new()
--保存数据库数据失败
SaveDBDataErrorEvent = IScriptEvent.new()
--观看广告事件
CloseVideoAdTipEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("CloseVideoAdTip", CloseVideoAdTipEvent)
--刷新道具事件，例如购买了超级玩家，需要刷新一下道具
RefreshPropsEvent = IScriptEvent.new()
CommonDataEvents:registerEvent("RefreshProps", RefreshPropsEvent)
--首充领奖之前事件
ReceiveSumRechargeStartEvent = IScriptEvent.new()
--首充领奖时事件
ReceiveSumRechargeEvent = IScriptEvent.new()
--首充领奖之后事件
ReceiveSumRechargeEndEvent = IScriptEvent.new()
--玩家跟随进入观战模式事件
PlayerIntoFollowModeEvent = IScriptEvent.new()
--通用领取奖励事件
CommonReceiveRewardEvent = IScriptEvent.new()