---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/9/20 11:05
---
DbUtil = {}
DbUtil.GAME_DATA = 1
DbUtil.ADVERT_DATA = 2

DbUtil.FIRST_DATA_KEY = DbUtil.GAME_DATA
DbUtil.LAST_DATA_KEY = DbUtil.ADVERT_DATA

DBManager:addMustLoadSubKey(DbUtil.GAME_DATA)
DBManager:addMustLoadSubKey(DbUtil.ADVERT_DATA)

function DbUtil:getPlayerData(player)
    DBManager:getPlayerData(player.userId, DbUtil.GAME_DATA)
    DBManager:getPlayerData(player.userId, DbUtil.ADVERT_DATA)
end

function DbUtil:onPlayerGetDataFinish(player, data, subKey)
    player:initDataFromDB(data, subKey)
    if DbUtil:IsGetAllDataFinished(player) then
        player.cur_jobId = player.lastJobId
        player.GameJob:init()
        player.GameJobPond:init()
        player:nextGameUseProp()
    end
end

function DbUtil:savePlayerData(player, immediate)
    if player == nil then
        return
    end
    DbUtil:SavePlayerGameData(player, immediate)
    DbUtil:SavePlayerAdvertData(player, immediate)
end

function DbUtil:CanSavePlayerData(player, subKey)
    return DBManager:isLoadDataFinished(player.userId, subKey)
end

function DbUtil:SavePlayerGameData(player, immediate)
    if not DbUtil:CanSavePlayerData(player, DbUtil.GAME_DATA) then
        return
    end
    local data = {}
    data.level = player.level
    data.money = player.money
    data.cur_exp = player.cur_exp
    data.jobs_data = player.jobs_data or {}
    data.lastJobId = player.lastJobId or 0
    data.init_prop = player.init_prop or {}
    DBManager:savePlayerData(player.userId, DbUtil.GAME_DATA, data, immediate)
end

function DbUtil:SavePlayerAdvertData(player, immediate)
    if not DbUtil:CanSavePlayerData(player, DbUtil.ADVERT_DATA) then
        return
    end
    local data = {}
    data.advert_record = player.advert_record
    DBManager:savePlayerData(player.userId, DbUtil.ADVERT_DATA, data, immediate)
end

function DbUtil:IsGetAllDataFinished(player)
    for key = DbUtil.FIRST_DATA_KEY, DbUtil.LAST_DATA_KEY do
        if not DbUtil:CanSavePlayerData(player, key) then
            return false
        end
    end
    return true
end

return DbUtil