---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/4/19 0019 15:00
---
EnterRoomManager = {}
EnterRoomManager.Queue = {}

function EnterRoomManager:addEnterRoomQueue(player, gameType, mapId)
    EngineUtil.sendEnterOtherGame(player.rakssid, gameType, player.userId, mapId)
    EnterRoomManager.Queue[tostring(player.userId)] = {
        rakssid = player.rakssid,
        gameType = gameType,
        userId = player.userId,
        mapId = mapId,
        time = os.time()
    }
    MsgSender.sendTopTipsToTarget(player.rakssid, 3600, Messages:msgWaitBackHall())
end

function EnterRoomManager:tryQueueEnterRoom()
    local time = os.time()
    for _, item in pairs(EnterRoomManager.Queue) do
        if time - item.time >= 10 then
            EngineUtil.sendEnterOtherGame(item.rakssid, item.gameType, item.userId, item.mapId)
            item.time = time
        end
    end
end

function EnterRoomManager:onPlayerLogout(player)
    EnterRoomManager.Queue[tostring(player.userId)] = nil
end

return EnterRoomManager