---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/1/10 10:01
---
require "config.TeamConfig"

TeamManager = {}
TeamManager.Teams = {}
TeamManager.Blue = 1
TeamManager.Red = 2

function TeamManager:InitTeams()
    local teams = TeamConfig:getTeams()
    for i, v in pairs(teams) do
        local team = GameTeam.new(v)
        self.Teams[team:getTeamId()] = team
    end
end

function TeamManager:isTie()
    local blue = self.Teams[self.Blue]
    local red = self.Teams[self.Red]
    if red:getPlayerNum() == 0 then
        return false
    end
    if blue:getPlayerNum() == 0 then
        return false
    end
    return blue.kills == red.kills
end

function TeamManager:getWinTeam()
    local blue = self.Teams[self.Blue]
    local red = self.Teams[self.Red]
    if blue:getPlayerNum() == 0 then
        return self.Red
    end
    if red:getPlayerNum() == 0 then
        return self.Blue
    end
    return (blue.kills > red.kills) and self.Blue or self.Red
end

function TeamManager:randomTeam()
    if self.Teams[self.Red]:getPlayerNum() == self.Teams[self.Blue]:getPlayerNum() then
        return self.Red
    elseif self.Teams[self.Red]:getPlayerNum() > self.Teams[self.Blue]:getPlayerNum() then
        return self.Blue
    else
        return self.Red
    end
end

return TeamManager