---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2018/10/24 0024 14:25
---

SkillUtil = {}

function SkillUtil:checkTopAreaIsAir(position)
    local first = VectorUtil.newVector3i(position.x, position.y + 1, position.z)
    local second = VectorUtil.newVector3i(position.x, position.y + 2, position.z)
    if EngineWorld:getBlockId(first) == BlockID.AIR and
            EngineWorld:getBlockId(second) == BlockID.AIR then
        return true, first
    end
    return false, first
end

function SkillUtil:useEnderPearl(position, player)
    local range = 0
    local pos, isAir, tpPos
    pos = VectorUtil.newVector3i(position.x, position.y, position.z)
    isAir, tpPos = SkillUtil:checkTopAreaIsAir(pos)
    if isAir then
        player:teleportPos(tpPos)
        EngineWorld:addSimpleEffect("ender_pearl.effect", VectorUtil.toVector3(tpPos), player:getYaw(), 1000)
        return
    end
    range = 1
    while not isAir and range <= 1 do
        if not isAir then
            pos = VectorUtil.newVector3i(position.x - range, position.y, position.z)
            isAir, tpPos = SkillUtil:checkTopAreaIsAir(pos)
            if isAir then
                player:teleportPos(tpPos)
            end
        end
        if not isAir then
            pos = VectorUtil.newVector3i(position.x + range, position.y, position.z)
            isAir, tpPos = SkillUtil:checkTopAreaIsAir(pos)
            if isAir then
                player:teleportPos(tpPos)
            end
        end
        if not isAir then
            pos = VectorUtil.newVector3i(position.x, position.y, position.z - range)
            isAir, tpPos = SkillUtil:checkTopAreaIsAir(pos)
            if isAir then
                player:teleportPos(tpPos)
            end
        end
        if not isAir then
            pos = VectorUtil.newVector3i(position.x, position.y, position.z + range)
            isAir, tpPos = SkillUtil:checkTopAreaIsAir(pos)
            if isAir then
                player:teleportPos(tpPos)
            end
        end
        if not isAir then
            pos = VectorUtil.newVector3i(position.x + range, position.y, position.z - range)
            isAir, tpPos = SkillUtil:checkTopAreaIsAir(pos)
            if isAir then
                player:teleportPos(tpPos)
            end
        end
        if not isAir then
            pos = VectorUtil.newVector3i(position.x - range, position.y, position.z + range)
            isAir, tpPos = SkillUtil:checkTopAreaIsAir(pos)
            if isAir then
                player:teleportPos(tpPos)
            end
        end
        if not isAir then
            pos = VectorUtil.newVector3i(position.x + range, position.y, position.z + range)
            isAir, tpPos = SkillUtil:checkTopAreaIsAir(pos)
            if isAir then
                player:teleportPos(tpPos)
            end
        end
        if not isAir then
            pos = VectorUtil.newVector3i(position.x - range, position.y, position.z - range)
            isAir, tpPos = SkillUtil:checkTopAreaIsAir(pos)
            if isAir then
                player:teleportPos(tpPos)
            end
        end
        if not isAir then
            range = range + 1
        end
    end
    if not isAir then
        player:teleportPos(tpPos)
    end
    EngineWorld:addSimpleEffect("ender_pearl.effect", VectorUtil.toVector3(tpPos), player:getYaw(), 1000)
end

function SkillUtil:createExplosion(position, player, damage)
    if player:getEntityPlayer() ~= nil then
        local pos = VectorUtil.newVector3(position.x, position.y, position.z)
        EngineWorld:getWorld():createExplosion(player:getEntityPlayer(), player:getEntityPlayer(), pos, damage, false)
        EngineWorld:addSimpleEffect("explosion.effect", pos, player:getYaw(), 1000)
    end
end

function SkillUtil:useFrozenBall(area, c_player, duration)
    local players = PlayerManager:getPlayers()
    for _, player in pairs(players) do
        if player.isLife and player:getTeamId() ~= c_player:getTeamId() then
            if area:inArea(player:getPosition()) then
                player:setOnFrozen(duration)
            end
        end
    end
end

function SkillUtil:useFlareBomb(position, player, damage, duration, itemEntityId)
    if player:getEntityPlayer() ~= nil then
        local pos = VectorUtil.newVector3(position.x, position.y, position.z)
        local entity = EngineWorld:getEntity(itemEntityId)
        if entity then
            EngineWorld:getWorld():newExplosion(entity, player:getEntityPlayer(), pos, damage, true, true, duration, ItemID.FLARE_BOMB)
            EngineWorld:addSimpleEffect("explosion.effect", pos, player:getYaw(), 1000, 0, 1)
        end
    end
end

function SkillUtil:useRescue(position, player, duration)
    if player:getEntityPlayer() ~= nil then
        if player:getEntityPlayer():canPlayerFallEx() then

            GamePacketSender:sendBedWarPlayerMotion(player.rakssid)

            local startPos = VectorUtil.newVector3i(math.floor(position.x - 2), math.floor(position.y - 1), math.floor(position.z - 2))
            local endPos = VectorUtil.newVector3i(math.floor(position.x + 2), math.floor(position.y - 1), math.floor(position.z + 2))
            for x = startPos.x, endPos.x do
                for z = startPos.z, endPos.z do
                    local blockPos = VectorUtil.newVector3i(math.floor(x), startPos.y, math.floor(z))
                    local blockId = EngineWorld:getBlockId(blockPos)

                    if blockId == 0 then
                        EngineWorld:setBlock(blockPos, BlockID.SLIME, 0, 3, true)
                    end
                end
            end

            player:removeItem(ItemID.RESCUE, 1)

            LuaTimer:schedule(function(startX, endX, startPosZ, endZ, Y)
                for x = startX, endX do
                    for z = startPosZ, endZ do
                        local blockPos = VectorUtil.newVector3i(x, Y, z)
                        local blockId = EngineWorld:getBlockId(blockPos)

                        if blockId == BlockID.SLIME then
                            if EngineWorld:isBlockChange(blockPos) then
                                EngineWorld:setBlock(blockPos, 0, 0, 3, true)
                            end
                        end
                    end
                end
            end, tonumber(duration) * 1000, nil, startPos.x, endPos.x, startPos.z, endPos.z, startPos.y)

        else
            MessagesManage:sendSystemTipsToPlayer(player.rakssid, Messages:msgNotUseRescue())
        end
    end
end

function SkillUtil:useWitchPotion(player, area, position)
    local players = PlayerManager:getPlayers()
    local pos = VectorUtil.newVector3(position.x, position.y, position.z)
    for _, c_player in pairs(players) do
        if c_player.isLife then
            if area:inArea(c_player:getPosition()) then
                BuffManager:createBuff(c_player.userId, BuffManager.BuffType.BanCure)
                BuffManager:createBuff(c_player.userId, BuffManager.BuffType.Speed)
            end
        end
    end
    EngineWorld:addSimpleEffect("g1008_zisepingzi.effect", pos, player:getYaw(), 1000, 0, 1)
end

function SkillUtil:useBackHomeReel(player)
    BuffManager:createBuff(player.userId, BuffManager.BuffType.BackHome)
end

function SkillUtil:useSnowBall(position, player, damage, duration, area)
    local pos = VectorUtil.newVector3(position.x, position.y, position.z)
    EngineWorld:addSimpleEffect("explosion.effect", pos, player:getYaw(), duration, 0, 0.5)

    local players = PlayerManager:getPlayers()
    for _, _player in pairs(players) do
        if _player.lifeStatus == true and _player.teamId ~= player.teamId then
            if area:inArea(_player:getPosition()) then
                local yaw = _player:getYaw()
                local x = -math.sin(yaw * MathUtil.DEG2RAD)
                local z = math.cos(yaw * MathUtil.DEG2RAD)
                if _player.entityPlayerMP ~= nil then
                    _player.entityPlayerMP:knockBack(_player.entityPlayerMP, 0.5, x, z)
                end
                local hurtValue = { value = damage }
                if PlayerAttackedEvent:invoke(_player, player, "player", hurtValue) then
                    _player:subHealth(hurtValue.value)
                end
            end
        end
    end

    position.y = math.ceil(position.y)
    if MonsterManager:createMonster(position, MonsterType.SnowBallInsect, player) == false then
        MessagesManage:sendSystemTipsToPlayer(player.rakssid, Messages:msgSummonsNumLimit())
    end
end

return SkillUtil