---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/7/30 21:47
---

MapAreaConfig = {}
MapAreaConfig.Areas = {}

local index = 1

function MapAreaConfig:initMapArea(config)
    for _, area in pairs(config) do
        local item = {}
        item.id = tonumber(area.id)
        local spos = StringUtil.split(area.startPos, "#")
        item.startPos = VectorUtil.newVector3(spos[1], spos[2], spos[3])
        local epos = StringUtil.split(area.endPos, "#")
        item.endPos = VectorUtil.newVector3(epos[1], epos[2], epos[3])
        item.blockId = tonumber(area.blockId)
        item.meta = tonumber(area.meta)
        item.positions = {}
        self.Areas[item.id] = item
    end
    self:findBlockPos()
end

function MapAreaConfig:findBlockPos()
    for id, area in pairs(self.Areas) do
        self:initPosition(area)
    end
    self:outPutFile()
end

function MapAreaConfig:initPosition(area)
    for i = area.startPos.x, area.endPos.x do
        for j = area.startPos.y, area.endPos.y do
            for k = area.startPos.z, area.endPos.z do
                local pos = VectorUtil.newVector3i(i, j, k)
                local blockId = EngineWorld:getBlockId(pos)
                local blockMeta = EngineWorld:getBlockMeta(pos)
                if blockId == area.blockId and blockMeta == area.meta then
                    if pos ~= nil then
                        local item = {}
                        item.pos = VectorUtil.toVector3(pos)
                        item.id = index
                        item.blockId = blockId
                        item.meta = blockMeta
                        table.insert(area.positions, item)
                        index = index + 1
                    end
                end
            end
        end
    end
end

function MapAreaConfig:outPutFile()
    local file = io.open("MapAreaConfigResult.csv", "w")
    if file then
        file:write("id" .. "\t" .. "areaId" .. "\t" .. "x" .. "\t" .. "y" .. "\t" .. "z" .. "\t" .. "blockId" .. "\t" .. "meta" .. "\n")
        file:write("id" .. "\t" .. "areaId" .. "\t" .. "x" .. "\t" .. "y" .. "\t" .. "z" .. "\t" .. "blockId" .. "\t" .. "meta" .. "\n")

        for _, area in pairs(self.Areas) do
            for id, item in pairs(area.positions) do
                file:write(item.id .. "\t")
                file:write(area.id .. "\t")
                file:write(item.pos.x .. "\t")
                file:write(item.pos.y .. "\t")
                file:write(item.pos.z .. "\t")
                file:write(item.blockId .. "\t")
                file:write(item.meta .. "\n")
            end
        end
        file:close()
        print("MapAreaConfigResult.csv created succeed !")
    end
end