---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/6/2 14:21
---
ToolItemGain = {}

function ToolItemGain:init(config)
    self.id = config.Id
    self.name = config.Name
    self.gains = config.Gains
    self.initLv = config.InitLv or 0
end

function ToolItemGain:onPlayerUpgrade(player)
    local team = GameMatch.Teams[player:getTeamId()]
    if not team then
        return
    end

    MessagesManage:sendSystemTipsToTeam(team.id, Messages:msgEnLvUp(player:getTeamColorName()))
    local players = PlayerManager:getPlayers()
    for _, _player in pairs(players) do
        if _player:getTeamId() == team.id then
            if _player.realLife then
                ---更新背包中所有工具的附魔
                local inv = _player:getInventory()
                for index = 0, 35 do
                    local info = inv:getItemStackInfo(index)
                    if info.id ~= 0 then
                        local item = Item.getItemById(info.id)
                        if item then
                            local class = item:getClassName()
                            if class == "ItemPickaxe" or class == "ItemAxe" or class == "ItemShears" then
                                local enchantList = ItemEnchantment:getItemEnchantmentList(inv, index)
                                inv:decrStackSize(index, info.num)
                                _player:tryAddItem(info.id, info.num, 0, enchantList)
                            end
                        end
                    end
                end
            end
        end
    end
end

---当玩家获取到工具，需要检查是否有附魔增益
function ToolItemGain:onPlayerGetTool(player, enchantList)
    local team = GameMatch.Teams[player:getTeamId()]
    if not team or not team.info then
        return enchantList
    end
    enchantList = enchantList or {}
    local level = tonumber(team.info:getValue(self.id))
    local gain = self.gains[level]
    if not gain then
        return enchantList
    end
    for _, enchant in pairs(enchantList) do
        if enchant[1] == gain.EnchantId then
            enchant[2] = math.max(gain.EnchantLv, enchant[2])
            return enchantList
        end
    end
    table.insert(enchantList, { gain.EnchantId, gain.EnchantLv })
    return enchantList
end