---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Yanzhuolin.
--- DateTime: 2019/7/1 22:04
---

local baseActor = require "actor.BaseActor"

MerchantActor = class("MerchantActor", baseActor)

function MerchantActor:ctor(id)
    local config = MerchantConfig:getConfigById(id)
    if not config then
        return {}
    end
    self.merchantPos = config.merchantPos
    self.storeId = config.storeId
    self.monsterId = config.monsterId
    self:createMerchant(config.yaw, config.actor, config.name)
end

function MerchantActor:createMerchant(yaw, actor, name)
    self.super:ctor(VectorUtil.newVector3(self.merchantPos[1], self.merchantPos[2],
            self.merchantPos[3]), yaw, actor or "", name, "", self)
    --HostApi.log(string.format("MerchantActor:createMerchant %s %s %s",
    --        self.merchantPos[1], self.merchantPos[2], self.merchantPos[3]))
end

function MerchantActor:clickedActor(player)
    player.storeEntityId = self.entityId
    GamePacketSender:sendWalkingDeadShowStoreId(player.rakssid, self.storeId)
    player:syncVipInfo()
    --HostApi.log("MerchantActor:clickedActor")
end

function MerchantActor:dayAlternatesWithNight(isDay)
    --转由管理器管理
    --if isDay then
    --    self:createMerchant(self.yaw, self.actorName, self.name)
    --else
    --    self:destroyActor()
    --end
end

function MerchantActor:getGoodsCount(goodsId)
    return 10000
end
