---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 98632.
--- DateTime: 2019/10/20 15:12
---


GameGene = {}

function GameGene:onButtonClick(player, itemId)

    for _, Value in pairs(player.shopGene) do
        if Value.id == itemId then
            if Value.status == Define.ItemBuyStatus.Unlock then
                self:onGeneBuy(player, itemId, true)
            elseif Value.status == Define.ItemBuyStatus.Buy then
                self:onGeneUsed(player, itemId)
            elseif Value.status == Define.ItemBuyStatus.Used then
                self:onGeneUnload(player, itemId)
            end
        end
    end
end

function GameGene:onGeneBuy(player, itemId, needMoney)
    if itemId == 208 then
        return
    end

    local gene = GeneConfig:getGeneById(itemId)
    if gene == nil then
        return
    end
    if not needMoney then
        self:onBuySuccess(player, itemId)
        return
    end
    if gene.moneyType == Define.MoneyType.SLGolds then
        if player.property.gold >= BigNum.new(string.format("%f", gene.price)) then
            player.property:changeGold(-gene.price)
            self:onBuySuccess(player, itemId)
        else
            HostApi.sendCommonTip(player.rakssid, "gold_enough")
        end
    end

    if gene.moneyType == Define.MoneyType.DiamondGolds1 then
        PayHelper.payDiamondsSync(player.userId, gene.id, gene.price, function(player)
            self:onBuySuccess(player, itemId)
        end, nil)

    end

    if gene.moneyType == Define.MoneyType.DiamondGolds2 then
        PayHelper.payDiamondsSync(player.userId, gene.id, gene.price, function(player)
            self:onBuySuccess(player, itemId)
        end, nil)

    end
    ReportUtil.reportGeneBuy(player, itemId)
end

function GameGene:onBuySuccess(player, itemId)

    local data = {}
    local used = true
    local usingGene = GeneConfig:getGeneById(player.property.geneId)
    local gene = GeneConfig:getGeneById(itemId)

    if usingGene == nil then
        usingGene = TokenGeneConfig:getGeneById(player.property.geneId)
    end

    if gene == nil then
        gene = TokenGeneConfig:getGeneById(player.property.geneId)
    end

    if usingGene and gene and usingGene.geneMuscleMass <= gene.geneMuscleMass then

        for _, Value in pairs(player.shopGene) do
            if Value.status == Define.ItemBuyStatus.Used then
                Value.status = Define.ItemBuyStatus.Buy
                table.insert(data, {
                    Id = Value.id,
                    Status = Value.status
                })
            end
        end

        for _, Value in pairs(player.shopGene) do
            if Value.id == itemId then
                Value.status = Define.ItemBuyStatus.Used
                table.insert(data, {
                    Id = Value.id,
                    Status = Value.status
                })
            end
        end

        player.property:changeGene(itemId)

    else
        used = false
        for _, Value in pairs(player.shopGene) do
            if Value.id == itemId then
                Value.status = Define.ItemBuyStatus.Buy
                table.insert(data, {
                    Id = Value.id,
                    Status = Value.status
                })
            end
        end

    end

    for _, Value in pairs(player.shopGene) do
        local gene = GeneConfig:getGeneById(Value.id)
        if gene and gene.unlock == itemId and Value.status == Define.ItemBuyStatus.Lock then
            Value.status = Define.ItemBuyStatus.Unlock
            table.insert(data, {
                Id = Value.id,
                Status = Value.status
            })
        end
    end
    local nextGene = GeneConfig:getNextSortGeneId(gene.id)
    if gene and gene.moneyType == Define.MoneyType.DiamondGolds1 or gene.moneyType == Define.MoneyType.DiamondGolds2 then


        for _, Value in pairs(player.shopGene) do

            local valueGene = GeneConfig:getGeneById(Value.id)
            if valueGene.sortId < gene.sortId and Value.status == Define.ItemBuyStatus.Lock then

                Value.status = Define.ItemBuyStatus.Unlock
                table.insert(data, {
                    Id = Value.id,
                    Status = Value.status
                })
            end
            if Value.id == nextGene.id and Value.status == Define.ItemBuyStatus.Lock then

                Value.status = Define.ItemBuyStatus.Unlock
                table.insert(data, {
                    Id = Value.id,
                    Status = Value.status
                })
            end


        end
    end
    --print("GameGene:onBuySuccess(player, itemId)"..itemId)

    ShopManager:senderGeneInfo(player, data)
    GameGene:shareDataToTokenGene(player, data, used)
    local nextNeedSelect = GeneConfig:getNextNeedSelectById(gene.id)
    if nextNeedSelect then
        GamePacketSender:sendShopItemSelectStatus(player.rakssid, Define.ShopKind.Gene, nextNeedSelect.id)
    end
end

function GameGene:onGeneUsed(player, itemId)

    local data = {}
    for _, Value in pairs(player.shopGene) do
        if Value.status == Define.ItemBuyStatus.Used then
            Value.status = Define.ItemBuyStatus.Buy
            table.insert(data, {
                Id = Value.id,
                Status = Value.status
            })
        end
    end

    for _, Value in pairs(player.shopGene) do
        if Value.id == itemId then
            Value.status = Define.ItemBuyStatus.Used
            table.insert(data, {
                Id = Value.id,
                Status = Value.status
            })
        end
    end
    player.property:changeGene(itemId)
    ShopManager:senderGeneInfo(player, data)
    GameGene:shareDataToTokenGene(player, data, true)

end

function GameGene:onGeneUnload(player, itemId)

end

function GameGene:initGeneItem(player)
    if #player.shopGene ~= 0 then
        self:updateShopGene(player)
        return
    end
    table.sort(GeneConfig.settings, function(a, b)
        return a.id < b.id
    end)

    local itemId = 0
    local i = 1
    for _, Value in pairs(GeneConfig.settings) do
        if i == 1 then
            table.insert(player.shopGene, {
                id = Value.id,
                status = Define.ItemBuyStatus.Used
            })
            itemId = Value.id
        else
            table.insert(player.shopGene, {
                id = Value.id,
                status = Define.ItemBuyStatus.Lock
            })
        end
        i = i + 1
    end

    for _, Value in pairs(player.shopGene) do
        local gene = GeneConfig:getGeneById(Value.id)
        if gene and gene.unlock == itemId and Value.status == Define.ItemBuyStatus.Lock then
            Value.status = Define.ItemBuyStatus.Unlock
        end
    end
    player.property:changeGene(itemId)
end

function GameGene:updateShopGene(player)

    if not player then
        return
    end
    for _, setting in pairs(GeneConfig.settings) do

        local find = false
        for _, Value in pairs(player.shopGene) do
            if Value.id == setting.id then
                find = true
                break
            end
        end

        if find == false then
            local preGene = GeneConfig:getGeneById(setting.unlock)
            if preGene then
                local flag = false
                for _, Value in pairs(player.shopGene) do
                    if Value.id == preGene.id and (Value.status == Define.ItemBuyStatus.Buy or Value.status == Define.ItemBuyStatus.Used) then
                        flag = true
                        break
                    end
                end

                if flag == true then
                    table.insert(player.shopGene, {
                        id = setting.id,
                        status = Define.ItemBuyStatus.Unlock
                    })

                else
                    table.insert(player.shopGene, {
                        id = setting.id,
                        status = Define.ItemBuyStatus.Lock
                    })
                end
            else
                table.insert(player.shopGene, {
                    id = setting.id,
                    status = Define.ItemBuyStatus.Unlock
                })
            end
        end

    end

end

function GameGene:initAdvancedGeneItem(player)

    table.sort(player.shopGene, function(a, b)
        return a.id < b.id
    end)

    local itemId = -1
    local i = 1
    local data = {}
    local flag = false

    for _, Value in pairs(player.shopGene) do
        local config = GeneConfig:getGeneById(Value.id)
        if config then
            if (Value.status == Define.ItemBuyStatus.Buy or Value.status == Define.ItemBuyStatus.Used)
                    and (config.moneyType == Define.MoneyType.DiamondGolds2 or config.moneyType == Define.MoneyType.DiamondGolds1) then
                flag = true
                itemId = Value.id
            end
        end
    end

    if flag == false then

        for _, Value in pairs(player.shopGene) do
            local config = GeneConfig:getGeneById(Value.id)
            if config then
                if i == 1 then
                    Value.status = Define.ItemBuyStatus.Used
                    itemId = Value.id
                    table.insert(data, {
                        Id = Value.id,
                        Status = Value.status
                    })
                elseif Value.status ~= Define.ItemBuyStatus.Lock and config.moneyType ~= Define.MoneyType.DiamondGolds1
                        and config.moneyType ~= Define.MoneyType.DiamondGolds2 then
                    Value.status = Define.ItemBuyStatus.Unlock
                    table.insert(data, {
                        Id = Value.id,
                        Status = Value.status
                    })
                elseif Value.status == Define.ItemBuyStatus.Used and (config.moneyType == Define.MoneyType.DiamondGolds1
                        or config.moneyType == Define.MoneyType.DiamondGolds2) then
                    Value.status = Define.ItemBuyStatus.Buy
                    table.insert(data, {
                        Id = Value.id,
                        Status = Value.status
                    })
                end
            end
            i = i + 1
        end
    else
        for _, Value in pairs(player.shopGene) do
            local config = GeneConfig:getGeneById(Value.id)
            if config then
                if Value.id == itemId then
                    Value.status = Define.ItemBuyStatus.Used
                    table.insert(data, {
                        Id = Value.id,
                        Status = Value.status
                    })
                elseif i == 1 then
                    Value.status = Define.ItemBuyStatus.Buy
                    table.insert(data, {
                        Id = Value.id,
                        Status = Value.status
                    })
                elseif Value.status ~= Define.ItemBuyStatus.Lock and config.moneyType ~= Define.MoneyType.DiamondGolds1
                        and config.moneyType ~= Define.MoneyType.DiamondGolds2 then
                    Value.status = Define.ItemBuyStatus.Unlock
                    table.insert(data, {
                        Id = Value.id,
                        Status = Value.status
                    })
                elseif Value.status == Define.ItemBuyStatus.Used and (config.moneyType == Define.MoneyType.DiamondGolds1
                        or config.moneyType == Define.MoneyType.DiamondGolds2) then
                    Value.status = Define.ItemBuyStatus.Buy
                    table.insert(data, {
                        Id = Value.id,
                        Status = Value.status
                    })
                end
            end
            i = i + 1
        end

    end

    if itemId ~= -1 then
        player.property:changeGene(itemId)
    end
    ShopManager:senderGeneInfo(player, data)
    GameGene:shareDataToTokenGene(player, data, true)

end

function GameGene:shareDataToTokenGene(player, data, isUsed)
    local info = {}
    if isUsed then
        for k, v in pairs(player.tokenShopGene) do
            if v.status == Define.TokenItemBuyStatus.Used then
                v.status = Define.TokenItemBuyStatus.Buy
                table.insert(info, {
                    Id = v.id,
                    Status = v.status
                })
            end
        end
    end

    for _, value in pairs(data) do
        for k, v in pairs(player.tokenShopGene) do
            if value.Id == v.id then
                v.status = value.Status
                table.insert(info, {
                    Id = value.Id,
                    Status = value.Status
                })
            end

            if value.Status == Define.TokenItemBuyStatus.Buy or value.Status == Define.TokenItemBuyStatus.Used then
                local gene = TokenGeneConfig:getGeneById(v.id)
                if gene and gene.unlock == value.Id and v.status == Define.ItemBuyStatus.Lock and player.property.advancedLevel >= gene.advancedId then
                    v.status = Define.ItemBuyStatus.Unlock
                    table.insert(info, {
                        Id = v.id,
                        Status = v.status
                    })
                end
            end
        end
    end
    TokenShopManager:senderTokenGeneInfo(player, info)
end
return GameGene