---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/11/7 19:36
---
PayStore = {}

function PayStore:init()
    --TODO
end

function PayStore:onBuyPayItem(player, itemType)
    if not player then
        return
    end

    local config = PayItemConfig:getPayItemConfig(itemType)
    if not config then
        return
    end

    if player.property.payItemList[tostring(itemType)] then
        return
    end

    if player:getDiamond() < config.price then
        ReportUtil.reportBuyPayItem(player, itemType, false)
        return
    end

    PayHelper.payDiamondsSync(player.userId, config.id, config.price, function(player)
        self:onBuyPayItemSuccess(player, itemType)
    end, nil)
end

function PayStore:onBuySkin(player, id, needMoney)
    if not player then
        return
    end

    local config = SkinConfig:getSkinConfig(id)
    if not config then
        return
    end

    --判断性别
    if player:getSex() ~= config.sex then
        return
    end

    if player.property.skinList[tostring(id)] then
        return
    end

    if needMoney then
        if player:getDiamond() < config.price then
            ReportUtil.reportBuySkinId(player, id, false)
            return
        end
        PayHelper.payDiamondsSync(player.userId, config.id, config.price, function(player)
            self:onBuySkinSuccess(player, id)
        end, nil)
    else
        self:onBuySkinSuccess(player, id)
    end

end

function PayStore:onEquipSkin(player, id)
    if not player then
        return
    end

    if player:isBeGrab() then
        return
    end

    player:equipSkin(id)
end

function PayStore:onBuyPayItemSuccess(player, itemType)
    player.property.payItemList[tostring(itemType)] = 1
    player.property:syncPayData()

    if itemType == Define.PayItemType.DoubleHp then
        player.property:changeHealth(player.property.curHealth, player.property.curHealth, true)
    elseif itemType == Define.PayItemType.InfinityMuscle then
        GamePacketSender:SendLSPlayerMuscleMassChange(player.rakssid, player.property:getMaxMuscleMass(), player.property.muscleMass)
    elseif itemType == Define.PayItemType.DoubleSpeed then
        player:setScale(player.property:getScale())
    elseif itemType == Define.PayItemType.AutoWorkout then
        self.onTeleAutoWorkout(player, "")
        GamePacketSender:sendAutoWorkAdInfo(player.rakssid, 0, 0, 0, 0, 0)
    elseif itemType == Define.PayItemType.ConcealPower then
        self.onConcealPower(player, "")
    end

    ReportUtil.reportBuyPayItem(player, itemType, true)

    --通知玩家购买成功
    local data = DataBuilder.new()
                            :addParam("Type", Define.PayStoreItem.PayItem)
                            :addParam("Param", itemType)
                            :getData()
    PacketSender:sendLuaCommonData(player.rakssid, "BuySuccess", data)

    --触发引导
    local config = PayItemConfig:getPayItemConfig(itemType)
    if not config then
        return
    end
    GameGuide:triggerGuide(player, config.guideId)
end

function PayStore:onBuySkinSuccess(player, id)
    player.property.skinList[tostring(id)] = 1

    --通知玩家购买成功
    local data = DataBuilder.new()
                            :addParam("Type", Define.PayStoreItem.Skin)
                            :addParam("Param", id)
                            :getData()
    PacketSender:sendLuaCommonData(player.rakssid, "BuySuccess", data)

    --购买后立刻装备
    self:onEquipSkin(player, id)

    ReportUtil.reportBuySkinId(player, id, true)

    LogUtil.log("PayStore:onBuySkin " .. id)
end

function PayStore.onTeleAutoWorkout(player, data)
    if not player.property:hasPayItem(Define.PayItemType.AutoWorkout) then
        return
    end

    if player:isBeGrab() then
        return
    end

    if player:isGrab() then
        player:unbindAllEntity()
    end

    player:teleportToAutoWork()

end

function PayStore.onConcealPower(player, data)
    if not player.property:hasPayItem(Define.PayItemType.ConcealPower) then
        return
    end

    if player:isBeGrab() then
        return
    end

    player.property.isConcealPower = not player.property.isConcealPower

    LSRankManager:updatePlayerRank(player)

    player:setConcealPower(player.property.isConcealPower)

    if player.property.isConcealPower then
        TeamManager:destroyTeam(player) --伪装弱小有队伍的话需要解散队伍
    end

    PacketSender:syncEntityPlayerInfo(player.userId, "ConcealPower", player.property.isConcealPower)
end

return PayStore