---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/12/22 17:21
---

require "process.BaseProcess"
require "settlement.TeamSettlement"
require "data.GameTeam"
require "manager.TeamManager"

TeamProcess = class("TeamProcess", BaseProcess)

TeamProcess.Teams = TeamManager.Teams
TeamProcess.winTeam = 0
TeamProcess.Red = TeamManager.Red
TeamProcess.Blue = TeamManager.Blue

function TeamProcess:doWin()
    if TeamManager:isTie() then
        self.curStatus = self.Status.ExtraTime
        self.ExtraTick = self.curTick
    else
        self.curStatus = self.Status.GameOver
        self.GameOverTick = self.curTick
        self.winTeam = TeamManager:getWinTeam()
        local players = PlayerManager:getPlayers()
        for _, player in pairs(players) do
            if player.isLife == false then
                LuaTimer:cancel(player.respawnTaskKey)
            end
            if player:getTeamId() == self.winTeam then
                player.taskController:packingProgressData(player, Define.TaskType.Fright.WinGame, GameMatch.gameType, player.cur_map_id)
                local kills = player.kills
                if kills > GameConfig.maxWinAndKillCount then
                    kills = GameConfig.maxWinAndKillCount
                end
                player.taskController:packingProgressData(player, Define.TaskType.Fright.WinAndKill, GameMatch.gameType, kills)
                for _, process in pairs(player.taskController.winProgresses) do
                    player.taskController:saveTaskProcesses(player, process)
                end
            end
            player.taskController:packingProgressData(player, Define.TaskType.Fright.CompleteGame, GameMatch.gameType, player.cur_map_id)
        end
        TeamSettlement:SendSettlementResult(PlayerManager:copyPlayers(), self.winTeam, 3)
    end
    HostApi.sendStartGame(PlayerManager:getPlayerCount())
end

function TeamProcess:ifExtraTimeEnd()
    --extratime --> gameover
    local ticks = self.curTick - self.ExtraTick

    local seconds = GameConfig.extraTime - ticks
    self:showGameInfo(seconds)
    local players = PlayerManager:getPlayers()
    for i, player in pairs(players) do
        player:onTick()
    end
    --msgExtraTimeHint
    if seconds <= 3 then
        HostApi.sendPlaySound(0, 12)
    else
        HostApi.sendPlaySound(0, 11)
    end

    if seconds <= 0 then
        self:doWin()
    end
end

function TeamProcess:assignTeam(player)
    local id = TeamManager:randomTeam()
    player:setTeamId(id)
    self.Teams[id]:addPlayer(player)
    if self:isRunning() then
        self:teleGamePos(player)
    end
    self:showGameInfo(0)
end

function TeamProcess:onPlayerQuit(player)
    if self:isGameBegin() and player.isReward == false then
        SeasonManager:addUserHonor(player.userId, GameConfig.quitSubHonor, player.level)
    end
    if player.teamId ~= 0 then
        self.Teams[player.teamId]:subPlayer(player)
        self:showGameInfo(0)
    end
    self:ifClose()
end

function TeamProcess:showGameInfo(time)
    local red = self.Teams[self.Red]
    local blue = self.Teams[self.Blue]
    local players = PlayerManager:getPlayers()
    for i, player in pairs(players) do
        if player.teamId == self.Blue then
            GamePacketSender:sendPixelGunTeamGameData(player.rakssid, time, red.kills, red.curPlayerCount, GameConfig.teamMaxPlayers,
                    blue.kills, blue.curPlayerCount, GameConfig.teamMaxPlayers, player.teamId)
        else
            GamePacketSender:sendPixelGunTeamGameData(player.rakssid, time, blue.kills, blue.curPlayerCount, GameConfig.teamMaxPlayers,
                    red.kills, red.curPlayerCount, GameConfig.teamMaxPlayers, player.teamId)
        end
    end
end

function TeamProcess:teleGamePos(player)
    local respawn = RespawnConfig:randomRespawn(player.teamId)
    if respawn ~= nil then
        player:teleportPosWithYaw(respawn.position, respawn.yaw)
        player.isLife = true
    end
end

function TeamProcess:onPlayerKill(player)
    if player.teamId ~= 0 then
        self.Teams[player.teamId]:addTeamKill()
    end
end

function TeamProcess:buildShowName(player, same)
    local nameList = {}

    local disName = player.name
    if same then
        if BaseMain:isChina() then
            disName = TextFormat.colorBlue .. disName .. "[蓝队]"
        else
            disName = TextFormat.colorBlue .. disName .. "[Blue]"
        end
    else
        if BaseMain:isChina() then
            disName = TextFormat.colorRed .. disName .. "[红队]"
        else
            disName = TextFormat.colorRed .. disName .. "[Red]"
        end
    end
    if player:isGameVip() then
        if BaseMain:isChina() then
            disName = TextFormat.colorGold .. "[会员]" .. disName
        else
            disName = TextFormat.colorGold .. "[VIP]" .. disName
        end
    end
    PlayerIdentityCache:buildNameList(player.userId, nameList, disName)
    return table.concat(nameList, "\n")
end

return TeamProcess