---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaolai.
--- DateTime: 2018/11/28 12:19
---
require "data.GameNpc"
require "config.ActorNpcConfig"

CustomListener = {}

function CustomListener:init()
    ConsumeTipMsgEvent.registerCallBack(self.onConsumeTipMsg)
    ConsumeDiamondsEvent.registerCallBack(self.onConsumeDiamonds)
end

function CustomListener.onConsumeTipMsg(rakssid, extra, isRight)
    local player = PlayerManager:getPlayerByRakssid(rakssid)
    if isRight == false  or  player == nil then
        return
    end
    if isRight == true then
        local npc = ActorNpcConfig:getActorByEntityId(tonumber(extra))
        if npc ~= nil then
            npc:onPlayerConfirm(player)
        end
    end
end

function CustomListener.onConsumeDiamonds(rakssid, isSuccess, message, extra)
    local player = PlayerManager:getPlayerByRakssid(rakssid)
    if isSuccess == false or player == nil then
        return
    end
    if isSuccess == true then
        local npc = ActorNpcConfig:getActorByEntityId(tonumber(extra))
        if npc ~= nil then
            npc:onPlayerHit(player)
        end
    end
end