---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/7/4 11:49
---
GameMusicBox = class()

function GameMusicBox:ctor(pos, config, playerEntityId)
    self.musicBoxConfig = MusicBoxConfig:getMusicBoxConfig(config.itemId)
    if self.musicBoxConfig == nil then
        --HostApi.log("self.musicBoxConfig == nil")
        return
    end

    self.birthPos = VectorUtil.newVector3(pos.x, pos.y + 1, pos.z)
    local entityId = EngineWorld:addActorNpc(self.birthPos, 0, config.dropActorName, function(entity)
        local name = TextFormat:getTipType2("gui_walkingdead_5")
        entity:setHeadName(name)
        entity:setHaloEffectName(config.effectName or "")
    end)
    self.entityId = entityId
    self.totalLiveTime = 0
    self.effectRange = self.musicBoxConfig.effectRange
    self.effectPlayerUserIds = {} --受影响的玩家userId列表
    self.channelId = MusicBoxManager.channelId
    MusicBoxManager.channelId = MusicBoxManager.channelId - 1
end

function GameMusicBox:playMusic(player)
    if BaseUtil:isTableHave(self.effectPlayerUserIds, player.userId) then
        return
    end

    HostApi.sendPlaySound(player.rakssid, self.musicBoxConfig.musicId, false, self.channelId)
    table.insert(self.effectPlayerUserIds, player.userId)
end

function GameMusicBox:stopMusic(player)
    for i = 1, #self.effectPlayerUserIds do
        if self.effectPlayerUserIds[i] == player.userId then
            HostApi.closeBGM(player.rakssid)
            table.remove(self.effectPlayerUserIds, i)
            break
        end
    end
end

function GameMusicBox:stopAllMusic()
    for i = 1, #self.effectPlayerUserIds do
        local player = PlayerManager:getPlayerByUserId(self.effectPlayerUserIds[i])
        if player then
            HostApi.closeBGM(player.rakssid)
        end
    end
    self.effectPlayerUserIds = {}
end

function GameMusicBox:onTick(ticks)
    self:checkPlayMusic()
    self:checkDisappear()
    self:checkMonster()
end

function GameMusicBox:checkPlayMusic()
    for i, vPlayer in pairs(PlayerManager:getPlayers()) do
        if vPlayer then
            if MathUtil:checkDisLessThan(self.birthPos, vPlayer:getPosition(), self.effectRange) then
                self:playMusic(vPlayer)
            else
                self:stopMusic(vPlayer)
            end
        end
    end
end

function GameMusicBox:checkMonster()
    for _, vMonster in pairs(MonsterManager:getMonsters()) do
        if vMonster and MathUtil:checkDisLessThan(self.birthPos, vMonster:getPosition(), self.effectRange) then
            EngineWorld:getWorld():forceCreatureToPos(vMonster.entityId, self.birthPos)
        end
    end
end

function GameMusicBox:checkDisappear()
    if self.totalLiveTime >= self.musicBoxConfig.liveTime then
        self:onRemove()
    end
    self.totalLiveTime = self.totalLiveTime + 1
end

function GameMusicBox:onRemove()
    self:stopAllMusic()
    MusicBoxManager:removeMusicBox(self.entityId)
    EngineWorld:removeEntity(self.entityId)
end

return GameMusicBox