---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/9/3 15:05
---
GameChest = class()

local blockId = 54

function GameChest:ctor(newPos, playerName)
    self.pos = VectorUtil.toVector3i(newPos)
    self.createTime = os.time()
    self.playerName = playerName
    self.itemSlot = 0

    EngineWorld:setBlock(self.pos, blockId)

    local inv = EngineWorld.getWorld():getInventory(blockId, self.pos)
    if inv == nil then
        return
    end

    self.headName = self.playerName .. TextFormat:getTipType2("gui_walkingdead_4")
    inv:setHeadName(self.headName)
    self:syncChestInfo(nil, true)
end

function GameChest:onTick(ticks)
    if os.time() - self.createTime >= GameConfig.PlayerChestExistTime then
        self:remove()
    end
end

function GameChest:addItem(itemID, itemDamage, itemCount)
    local inv = EngineWorld.getWorld():getInventory(blockId, self.pos)
    if inv == nil then
        return
    end

    inv:initByItem(self.itemSlot, itemID, itemCount, itemDamage)
    self.itemSlot = self.itemSlot + 1
end

function GameChest:remove()
    self:syncChestInfo(nil, false)
    EngineWorld:setBlock(self.pos, 0)
    ChestManager:removeChest(self)
end

function GameChest:syncChestInfo(rakssid, action)
    local dataBuilder = DataBuilder.new()
    local data = dataBuilder
            :addParam("posX", self.pos.x)
            :addParam("posY", self.pos.y)
            :addParam("posZ", self.pos.z)
            :addParam("headName", self.headName)
            :addParam("action", action)
            :getData()

    if rakssid == nil then
        for _, vPlayer in pairs(PlayerManager:getPlayers()) do
            PacketSender:sendServerCommonData(vPlayer.rakssid, "syncChestInfoMsg", "", data)
        end
    else
        PacketSender:sendServerCommonData(rakssid, "syncChestInfoMsg", "", data)
    end
end

return GameChest