---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wu.
--- DateTime: 2019/6/19 11:59
---
GameTask = {}

GameTask.TaskStatus = {
    NotActive = 1,
    Active = 2,
    Finish = 3
}

GameTask.TaskType = {
    KillWalkingDead = 1,
    KillPlayer = 2,
    GradeUp = 3,
    KillMonsterA = 4,
    SurvivalTime = 5
}

function GameTask:initTask(player)
    for _, task in pairs(TaskConfig.TaskList) do
        local taskMap = player.task_map[task.TaskTypeId]
        if not taskMap then
            player.task_map[task.TaskTypeId] = {}
        end
        local isHas = false
        for _, value in pairs(player.task_map[task.TaskTypeId]) do
            if value.Id == task.Id then
                isHas = true
                break
            end
        end
        if not isHas then
            local data = {
                id = task.Id,
                status = GameTask.TaskStatus.NotActive
            }
            table.insert(player.task_map[task.TaskTypeId], data)
        end
        local taskProcess = player.task_process[task.TaskTypeId]
        if not taskProcess then
            local data = {
                process = 0
            }
            table.insert(player.task_process[task.TaskTypeId], data)
        end
    end
end

function GameTask:sendTaskToClient(player)

end

function GameTask:onUpdateTask(player, taskTypeId, num)
    local taskMap = player.task_map[taskTypeId]
    local taskProcess = player.task_process[taskTypeId]
    if not taskMap or not taskProcess then
        return
    end
    taskProcess.process = taskProcess.process + num
    for _, task in pairs(taskMap) do
        if task.status ~= GameTask.TaskStatus.Finish then
            local config=TaskConfig:getTaskById(task.id)
            if not config then
                return
            end
            if config.GoalNum <= taskProcess.process then
                task.status=GameTask.TaskStatus.Finish
                self:getTaskReward(player,task.id)
            end
        end
    end
end

function GameTask:getTaskReward(player, taskId)
    local configTask=TaskConfig:getTaskById(taskId)
    if not configTask then
        return
    end
    for _, id in pairs(configTask.RewardIds) do
        local configReward=RewardConfig:getRewardById(tonumber(id))
        if not configReward then
            return
        end
        --type not course
        if configReward.RewardType==Define.RewardType.Title then
            GameTask:doTitleReward(player,configReward.RewardId)
        end
    end
end

function GameTask:doTitleReward(player,rewardId)
    GameTitle:updateTitle(player, rewardId, GameTitle.TitleStatus.Has)
end

return GameTask

