---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/8/12 11:10
---
MonsterManager = {}

MonsterManager.Monsters = {}
--setmetatable(MonsterManager.Monsters, {__mode = "kv"}) --weak table

function MonsterManager:init()
    MonsterManager:prepareMonster()
    --TODO
end

function MonsterManager:prepareMonster()
    for _, setting in pairs(MonsterConfig.settings) do
        local monster = MonsterSetting.new()
        monster.monsterId = setting.monsterId
        monster.monsterBtTree = setting.monsterBtTree
        monster.actorName = setting.actorName
        monster.monsterType = setting.monsterType
        monster.attackType = setting.attackType
        monster.isAutoAttack = setting.isAutoAttack
        monster.attackDistance = setting.attackDistance
        monster.attackCd = setting.attackCd
        monster.attackCount = setting.attackCount
        monster.moveSpeed = setting.moveSpeed
        monster.patrolDistance = setting.patrolDistance
        monster.chaseRange = setting.chaseRange
        monster.skillId = setting.skillId
        monster.skillCd = setting.skillCd
        monster.bombEffect = setting.bombEffect
        HostApi.addMonsterSetting(monster)
    end
end

function MonsterManager:onTick(ticks)
    MonsterManager:updateMonsters(ticks)
    --TODO
end

function MonsterManager:updateMonsters(ticks)
    local count = 0
    for _, vMonster in pairs(MonsterManager.Monsters) do
        vMonster:onTick(ticks)
        count = count + 1
    end
    --HostApi.log(string.format("monster count %d", count))
end

function MonsterManager:addMonster(monster)
    MonsterManager.Monsters[monster.entityId] = monster
    --TODO
end

function MonsterManager:removeMonster(entityId)
    MonsterManager.Monsters[entityId] = nil
    --TODO
end

return MonsterManager