---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2019/9/26 11:12
---

GameTeam = class()
GameTeam.teamId = 0
GameTeam.teamName = ""
GameTeam.teamPlayers = {}
GameTeam.curPlayers = 0
GameTeam.island = {}

function GameTeam:ctor(teamConfig)
    self.teamId = teamConfig.teamId
    self.name = teamConfig.name
    self.islandId = teamConfig.areaId
    self.island = IslandConfig:getIslandById(self.islandId)
end

function GameTeam:getTeamCount()
    local players = PlayerManager:getPlayers()
    local count = 0
    for _, player in pairs(players) do
        if player.isLife and player:getTeamId() == self.teamId then
            count = count + 1
        end
    end
    return count
end

function GameTeam:isDeath()
    return self:getTeamCount() == 0
end

function GameTeam:getTeleportPos(player)
    local posInfo = self.island:randomTwoPos()
    local pos = VectorUtil.newVector3(posInfo.x, posInfo.y, posInfo.z)
    player:teleportPosWithYaw(pos, posInfo.yaw)
end

return GameTeam