---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/9/26 15:52
---

Island = class()
Island.Position = {}

function Island:ctor(config)
    self.config = config
    self:initPosition()
end

function Island:initPosition()
    local config = AreaConfig:getPositionsByGroupId(self.config.id)
    if config ~= nil then
        self.Position = config
    end
    self.rest = #self.Position
end

function Island:isInArea(vec3)
    return vec3.x >= self.config.startPos.x and vec3.x <= self.config.endPos.x
            and vec3.y >= self.config.startPos.y and vec3.y <= self.config.endPos.y
            and vec3.z >= self.config.startPos.z and vec3.z <= self.config.endPos.z
end

function Island:randomPos()
    if self.Position == nil then
        return nil
    end
    local index = math.random(1, #self.Position)
    if self.Position[index] ~= nil then
        return self.Position[index]
    end
    return self.Position[1]
end

function Island:getCenterPos()
    local x = (self.config.startPos.x + self.config.endPos.x) / 2
    local y = (self.config.startPos.y + self.config.endPos.y) / 2
    local z = (self.config.startPos.z + self.config.endPos.z) / 2
    return VectorUtil.newVector3(x, y, z)
end

function Island:randomTwoPos()
    if self.Position == nil then
        return nil
    end
    local random = math.random(1, #self.Position)
    local pos = self.Position[random]
    while self.rest > 1 and pos.sign do
        random = math.random(1, #self.Position)
        pos = self.Position[random]
    end
    if self.rest ~= #self.Position then
        self.rest = self.rest - 1
    end
    self.Position[random].sign = true
    return pos
end

return Island