---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/8/9 18:10
---
local CGameTimeTask = class("GameTimeTask", ITask)

function CGameTimeTask:onCreate()
    ActorManager:init()
    SeasonRankManager:init()
    SkillManager:init()
    AreaEventManager:init()
    PayStore:init()
    AreaManager:createArea()
end

function CGameTimeTask:onTick(ticks)
    --print("CGameTimeTask:onTick " .. ticks)

    MonsterManager:onTick(ticks)
    PlayerManager:onTick(ticks)
    ActorManager:onTick(ticks)
    SeasonRankManager:onTick(ticks)
    SkillManager:onTick(ticks)
    SceneManager:onTick(ticks)
    AreaEventManager:onTick(ticks)
    TeamManager:tick(ticks)
    CheckCheatManager:onTick(ticks)
    MemoryLeakDetector:onTick(ticks)
    JumpGameManager:onTick()
    EntityRankManager:onTick(ticks)

    --发送排行榜
    if ticks % (5 * GameMatch.tickPerSecond) == 0 then
        LSRankManager:senderAllPlayerRank()
    end

end

GameTimeTask = CGameTimeTask.new(1, GameMatch.tickInterval)

return GameTimeTask