---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/8/8 16:16
---
package.path = package.path ..';..\\?.lua';

require "Header"

local ScriptMain = {}

function ScriptMain:init()
    LogUtil.log("ScriptMain:init")
    BaseMain:setGameType(GameMatch.gameType)
    DBManager:setGameType("g1055")
    ScriptMain:initListener()
    ScriptMain:setPlayerPrefs()
    ScriptMain:initLog()
    GamePacketHandler:init()
    GameMatch:init()
    if GameMatch.debug then
        Test:doTest()
    end
end

function ScriptMain:initListener()
    GameListener:init()
    PlayerListener:init()
    DBDataListener:init()
    BlockListener:init()
    ShopListener:init()
end

function ScriptMain:setPlayerPrefs()
    HostApi.setThirdPersonDistance(0.75)
    HostApi.setSeparateCameraControl(true)
    HostApi.setUseLocalScaleInHand(true)
    HostApi.setSceneSwitch(2, 0, false, false, false)

    ServerHelper.putIntPrefs("ActorNpcViewDis", 512)
    ServerHelper.putIntPrefs("CreatureAIViewDis", 512)
    ServerHelper.putIntPrefs("SpeedAddMax", 10000)
    ServerHelper.putFloatPrefs("MaxMoveDis", 100.0)
    ServerHelper.putBoolPrefs("SendSystemsChat", false)
    ServerHelper.putIntPrefs("TestAttrSex", 2)
    ServerHelper.putBoolPrefs("IsCreatureCollision", false)
    ServerHelper.putIntPrefs("HurtProtectTime", 0)
    PlayerManager.IsMessages = false
end

function ScriptMain:initLog()
    --LogUtil.setHighest(LogUtil.LogLevel.Debug)
    LogUtil.setDebug(Platform.isWindow())
    --LogUtil.disableAll()
    --LogUtility.setHighest("FATAL")
end

ScriptMain:init()