---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 98632.
--- DateTime: 2019/10/20 10:37
---

ShopManager = {}

function ShopManager:onButtonClick(player, data)

    local builder = DataBuilder.new():fromData(data)
    local kind = builder:getNumberParam("Kind")
    local itemId = builder:getNumberParam("ItemId")
    --print(kind)
    --print(itemId)
    if kind == Define.ShopKind.FitnessEquip then
        GameFitnessEquip:onButtonClick(player, itemId)
    end

    if kind == Define.ShopKind.Gene then
        GameGene:onButtonClick(player, itemId)
    end

    if kind == Define.ShopKind.Skill then
        GameSkill:onButtonClick(player, itemId)
    end
end

function ShopManager:initItem(player)
    GameFitnessEquip:initFitnessEquipItem(player)
    GameGene:initGeneItem(player)
    GameSkill:initSkillItem(player)
end

function ShopManager:senderAllItemInfo(player)
    local data1 = {}
    for _, Value in pairs(player.shopFitnessEquip) do
        if Value.status ~= Define.ItemBuyStatus.Lock then
            table.insert(data1, {
                Id = Value.id,
                Status = Value.status
            })
        end
    end
    self:senderFitnessEquipInfo(player, data1)

    local data2 = {}
    for _, Value in pairs(player.shopGene) do
        if Value.status ~= Define.ItemBuyStatus.Lock then
            table.insert(data2, {
                Id = Value.id,
                Status = Value.status
            })
        end
    end
    self:senderGeneInfo(player, data2)

    local data3 = {}
    for _, Value in pairs(player.shopAdvanced) do
        if Value.status ~= Define.ItemBuyStatus.Lock then
            table.insert(data3, {
                Id = Value.id,
                Status = Value.status
            })
        end
    end
    self:senderAdvancedInfo(player, data3)

    local data4 = {}
    for _, Value in pairs(player.shopSkill) do
        if Value.status ~= Define.ItemBuyStatus.Lock then
            table.insert(data4, {
                Id = Value.id,
                Status = Value.status
            })
        end
    end
    self:senderSkillInfo(player, data4)

    --
    for _, Value in pairs(player.equipmentSkill) do
        if Value.id ~= 0 then
            GamePacketSender:SendEquipSkill(player.rakssid, Value.id, Value.position, false)
        end
    end

end

function ShopManager:senderFitnessEquipInfo(player, data)

    GamePacketSender:SendShopFitnessEquip(player.rakssid, json.encode(data))
end

function ShopManager:senderGeneInfo(player, data)

    GamePacketSender:SendShopGene(player.rakssid, json.encode(data))
end

function ShopManager:senderAdvancedInfo(player, data)

    GamePacketSender:SendShopAdvanced(player.rakssid, json.encode(data))
end

function ShopManager:senderSkillInfo(player, data)

    GamePacketSender:SendShopSkill(player.rakssid, json.encode(data))
end

return ShopManager