---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/8/24 18:50
---
CustomListener = {}

function CustomListener:init()
    CommonReceiveRewardEvent:registerCallBack(self.onCommonReceiveReward)
    ConsumeTipMsgEvent.registerCallBack(self.onConsumeTipMsg)
    ConsumeDiamondsEvent.registerCallBack(self.onConsumeDiamonds)
end

function CustomListener.onCommonReceiveReward(player, propsType, propsId, propsCount, expireTime)
    if propsType == "YaoShi" then
        player.yaoshi = player.yaoshi + propsCount
        player:syncHallInfo()
        player.taskController:packingProgressData(player, Define.TaskType.GrowUp.GainCoin, GameMatch.gameType, Define.Money.KEY, propsCount)
    end
    if propsType == "Currency" then
        player:addCurrency(propsCount or 0)
        player.taskController:packingProgressData(player, Define.TaskType.GrowUp.GainCoin, GameMatch.gameType, Define.Money.MONEY, propsCount)
    end
    if propsType == "GunChip" then
        GameReward:onPlayerRewardGunChip(player, tonumber(propsId), propsCount)
        player.taskController:packingProgressData(player, Define.TaskType.GrowUp.GainCoin, GameMatch.gameType, Define.Money.CHIP, propsCount)
    end
    if propsType == "Privilege" then
        if expireTime == 0 then
            return
        end
        local isVip = player:isGameVip()
        if player.vip_time <= os.time() then
            player.vip_time = os.time()
        end
        player.vip_time = player.vip_time + expireTime
        if not isVip then
            player:setShowName(player:buildShowName())
        end
        player:syncHallInfo()
    end
    if propsType == "Gun" then
        GameReward:onPlayerRewardGun(player, propsId, propsCount)
    end
    if propsType == "Prop" then
        GameReward:onPlayerRewardProp(player, propsId, propsCount)
    end
    if propsType == "PropChip" then
        GameReward:onPlayerRewardPropChip(player, propsId, propsCount)
    end
    if propsType == "Ticket" then
        GameReward:addPlayerTicket(player, propsId, propsCount)
    end

end

function CustomListener.onConsumeTipMsg(rakssid, extra, isRight)
    if isRight == false then
        return
    end
    local player = PlayerManager:getPlayerByRakssid(rakssid)
    if player == nil then
        return
    end
    local info = StringUtil.split(extra, "#")
    if #info == 2 then
        local extra1 = tostring(info[1])
        local extra2 = tonumber(info[2])
        if extra1 == Define.OpenLotteryChest then
            GameChestLottery:onPlayerConfirmPayLottery(player, extra2)
            return
        end
    end
end

function CustomListener.onConsumeDiamonds(rakssid, isSuccess, message, extra)
    if isSuccess == false then
        return
    end
    local player = PlayerManager:getPlayerByRakssid(rakssid)
    if player == nil then
        return
    end
    local info = StringUtil.split(extra, "#")
    if #info == 2 then
        local extra1 = tostring(info[1])
        local extra2 = tonumber(info[2])
        if extra1 == Define.UnlockMap then
            player:unlockMap(extra2)
            return
        end
        if extra1 == Define.BuyGun then
            GameGunStore:onBuyStoreGunSuccess(player, extra2)
            return
        end
        if extra1 == Define.UpgradeGun then
            GameGunStore:onUpgradeStoreGunSuccess(player, extra2)
            return
        end
        if extra1 == Define.QuickUpgradeGun then
            GameGunStore:onQuickUpgradeStoreGunSuccess(player, extra2)
            return
        end
        if extra1 == Define.BuyProp then
            GameGunStore:onBuyStorePropSuccess(player, extra2)
            return
        end
        if extra1 == Define.UpgradeProp then
            GameGunStore:onUpgradeStorePropSuccess(player, extra2)
            return
        end
        if extra1 == Define.QuickUpgradeProp then
            GameGunStore:onQuickUpgradeStorePropSuccess(player, extra2)
            return
        end

        if extra1 == Define.BuyModule then
            GameModule:onBuyModuleSuccess(player, extra2)
        end

        if extra1 == Define.OpenLotteryChest then
            GameChestLottery:onPlayerLottery(player, extra2)
            return
        end

        if extra1 == Define.UpArmor then
            GameArmor:armorUping(player, extra2)
            return
        end
        if extra1 == Define.SpeedUpGradeArmor then
            GameArmor:quickUpgradeArmorFinished(player, extra2)
        end

        if extra1 == Define.BuyGiftBag then
            player:onBuyGiftBag(extra2)
        end
    end
end

return CustomListener