---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/3/8 0008 15:41
---
TaskListener = {}

function TaskListener:init()
    ReceiveTaskActiveRewardEvent:registerCallBack(self.onReceiveTaskActiveReward)
    ReceiveTaskRewardEvent:registerCallBack(self.onReceiveTaskReward)
end

function TaskListener.onReceiveTaskActiveReward(userId, data)
    local player = PlayerManager:getPlayerByUserId(userId)
    if not player then
        return
    end
    local activeId = DataBuilder.new():fromData(data):getNumberParam("activeId")
    player.taskController:onReceiveActiveRewards(activeId)
end

function TaskListener.onReceiveTaskReward(userId, data)
    local player = PlayerManager:getPlayerByUserId(userId)
    if player == nil then
        return
    end
    local taskId = DataBuilder.new():fromData(data):getNumberParam("taskId")
    player.taskController:receiveTaskReward(player, taskId)
end

return TaskListener

