---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/6/1 13:22
---
require "common.privilege.GoldIngotPrivilege"
require "common.privilege.AddMaxHPPrivilege"
require "common.privilege.FireSwordPrivilege"
require "common.privilege.GoodsStorePrivilege"
require "common.privilege.RespawnPrivilege"
require "common.privilege.DoubleExpPrivilege"

local Privileges = {}

local function init()
    local mappings = {
        ["AddMaxHPPrivilege"] = AddMaxHPPrivilege,
        ["FireSwordPrivilege"] = FireSwordPrivilege,
        ["GoldIngotPrivilege"] = GoldIngotPrivilege,
        ["GoodsStorePrivilege"] = GoodsStorePrivilege,
        ["RespawnPrivilege"] = RespawnPrivilege,
        ["DoubleExpPrivilege"] = DoubleExpPrivilege,
    }
    local config = FileUtil.getConfigFromYml("setting/PrivilegeSetting", true)
    for _, item in pairs(config.Privileges or {}) do
        local class = mappings[item.Name]
        if class then
            class:init(item)
        end
        Privileges[tostring(item.Id)] = {
            BuyTime = tonumber(item.BuyTime) or 43200,
            Class = class
        }
    end
end

init()

Privilege = {}

---检查用户是否拥有某个特权
function Privilege.checkHavePrivilege(player, privilegeId)
    if #player.privilegeCard == 0 then
        return false
    end
    for _, privilege in pairs(player.privilegeCard) do
        if privilege.privilegeId == privilegeId then
            if privilege.time >= os.time() then
                return true
            end
        end
    end
    return false
end

---同步玩家的特权时间
function Privilege.syncPrivilegeTime(player)
    local data = {}
    for _, privilege in pairs(player.privilegeCard) do
        table.insert(data, {
            Id = privilege.privilegeId,
            Time = math.max(privilege.time - os.time(), 0)
        })
    end
    CommonPacketSender:sendBedWarPrivilegeData(player.rakssid, json.encode(data))
end

---给用户某个特权增加时长
function Privilege.addPrivilegeTime(player, privilegeId, addTime)
    local config = Privileges[tostring(privilegeId)]
    if not config then
        return
    end
    local time = addTime or config.BuyTime
    for _, privilege in pairs(player.privilegeCard) do
        if privilege.privilegeId == privilegeId then
            local isNewAdd = privilege.time < os.time()
            privilege.time = math.max(privilege.time, os.time()) + time
            Privilege.syncPrivilegeTime(player)
            if isNewAdd and GameType ~= "g1046" then
                config.Class:onPlayerBuy(player)
            end
            return
        end
    end
    local privilege = {
        privilegeId = privilegeId,
        time = os.time() + time
    }
    table.insert(player.privilegeCard, privilege)
    Privilege.syncPrivilegeTime(player)
    if GameType ~= "g1046" then
        config.Class:onPlayerBuy(player)
    end
end