---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by work.
--- DateTime: 2018/7/16 12:13
---
GameGetPortal = class()
local LastPortalTime = 0
function GameGetPortal:ctor(portal, initPos, yaw, actor, name, isGoBackPortal)
    self.entityId = 0
    self.portal = portal
    self.initPos = initPos
    self.yaw = yaw
    self.actor = actor
    self.name = name or ""
    self.goback = false
    self.isGoBackPortal = isGoBackPortal
    self.ClllisionPlayers = {}
    self:onCreate()
end

function GameGetPortal:onTick(tick)
    self:update()
end

function GameGetPortal:update()
    local distance = 1.5
    local players = PlayerManager:getPlayers()
    for _, player in pairs(players) do
        local id = player:getEntityId()
        local playerPos = player.position
        local curDistance = math.abs(playerPos.x - self.initPos.x) ^ 2 + math.abs(playerPos.z - self.initPos.z) ^ 2
        if math.abs(playerPos.y - self.initPos.y) <= 2 then
            if curDistance <= distance ^ 2 and self.ClllisionPlayers[id] == nil then
                self:onPlayerHit(player)
                self.ClllisionPlayers[id] = player
            elseif curDistance > distance ^ 2 and self.ClllisionPlayers[id] then
                self.ClllisionPlayers[id] = nil
            end
        end
    end
end

function GameGetPortal:onPlayerHit(player)
    if self.isGoBackPortal then
        if player.domain ~= nil then
            self.portal:hitPortal(player.rakssid, player.domain:getGoBackExitPos())
        end
    else
        if player == self.portal:getPlayer() then
            if os.time() - LastPortalTime >= self.portal.config.cd then
                self.portal:hitPortal(player.rakssid, self.portal.config.portalExitPos)
                LastPortalTime = os.time()
            else
                local geptime = os.time() - LastPortalTime
                MsgSender.sendCenterTipsToTarget(player.rakssid, 2, Messages:portalOverload(self.portal.config.cd - geptime))
            end
        end
    end
end

function GameGetPortal:onCreate()
    local entityId = EngineWorld:addActorNpc(self.initPos, self.yaw, self.actor, function(entity)
        entity:setHeadName(self.name)
        entity:setSkillName("idle")
    end)
    self.entityId = entityId
    if self.isGoBackPortal then
        GameManager:onAddGoBackPortal(self)
        GameManager.getPortals[#GameManager.getPortals + 1] = self
    else
        GameManager:onAddPortal(self)
        GameManager.getPortals[#GameManager.getPortals + 1] = self
    end
end

function GameGetPortal:onRemove()
    EngineWorld:removeEntity(self.entityId)
    if self.isGoBackPortal then
        GameManager:onRemoveGoBackPortal(self)
    else
        GameManager:onRemovePortal(self)
    end
end
