---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by work.
--- DateTime: 2018/7/13 14:37
---

GameGateBuilder = class()

function GameGateBuilder:ctor(gate, initPos, yaw, actor, name)
    self.entityId = 0
    self.gate = gate
    self.initPos = initPos
    self.yaw = yaw
    self.actor = actor
    self.name = name
    self:onCreate()
end

function GameGateBuilder:onCreate()
    if self.name == "#" then
        self.name = ""
    end
    local name = self.name .. "=($" .. self.gate:getPrice() .. ")"
    local entityId = EngineWorld:addActorNpc(self.initPos, self.yaw, self.actor, function(entity)
        entity:setHeadName(name)
        entity:setSkillName("idle")
    end)
    self.entityId = entityId
    GameManager:onAddGateBuilder(self)
end

function GameGateBuilder:isSamePlayer(player)
    return self.gate:getPlayer() == player
end

function GameGateBuilder:onPlayerHit(player)
    if self:isSamePlayer(player) == false then
        MsgSender.sendCenterTipsToTarget(player.rakssid, 2, Messages:noSelfItem())
        return
    end
    local price = self:getPrice()
    local money = player:getCurrency()
    if price <= money then
        self:onBuild(player, price)
    else
        VideoAdHelper:checkShowBuildingAd(player, self)
        MsgSender.sendCenterTipsToTarget(player.rakssid, 2, Messages:noMoney())
    end
end

function GameGateBuilder:getPrice()
    return self.gate:getPrice()
end

function GameGateBuilder:onBuild(player, price)
    player:subCurrency(price)
    self:onRemove()
    self.gate:buildGuard()
    MsgSender.sendCenterTipsToTarget(player.rakssid, 2, Messages:buildsucceed())
end

function GameGateBuilder:onRemove()
    EngineWorld:removeEntity(self.entityId)
    GameManager:onRemoveGateBuilder(self)
end

