---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2019/8/9 18:10
---
local CGameTimeTask = class("GameTimeTask", ITask)

function CGameTimeTask:onCreate()
    MonsterManager:init()
end

function CGameTimeTask:onTick(ticks)
    MonsterManager:onTick(ticks)
    --TODO
end

GameTimeTask = CGameTimeTask.new(1)

return GameTimeTask