---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guoyusheng.
--- DateTime: 2019/6/28 9:40
---
AddWaterLevelProperty = class("AddWaterLevelProperty", BaseProperty)

function AddWaterLevelProperty:onPlayerUsed(player,itemId)
        player:addWaterLevel(self.config.value[1])
end

return AddWaterLevelProperty