---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Leilei.
--- DateTime: 2018/11/14 9:32
---

RewardUtil = {}

function RewardUtil:sortPlayerRank()
    local players = {}
    local c_players = PlayerManager:copyPlayers()
    for i, player in pairs(c_players) do
        if player.role ~= GamePlayer.ROLE_PENDING then
            table.insert(players, player)
        end
    end

    table.sort(players, function(a, b)
        if a.isWiner ~= b.isWiner then
            return a.isWiner > b.isWiner
        elseif a.kills ~= b.kills then
            return a.kills > b.kills
        elseif a.hideTime ~= b.hideTime then
            return a.hideTime > b.hideTime
        end
        return tonumber(tostring(a.userId)) > tonumber(tostring(b.userId))
    end)

    return players
end

function RewardUtil:sortPlayerRankOnRunning()
    local players = {}
    local allplayers = PlayerManager:copyPlayers()
    for i, player in pairs(allplayers) do
        if player.role ~= GamePlayer.ROLE_PENDING then
            table.insert(players, player)
        end
    end

    table.sort(players, function(a, b)
        if a.score ~= b.score then
            return a.score > b.score
        end
        return tonumber(tostring(a.userId)) > tonumber(tostring(b.userId))
    end)

    return players
end

function RewardUtil:doReward(role)
    local players = self:sortPlayerRank()
    for rank, player in pairs(players) do
        RewardManager:addRewardQueue(player.userId, rank)
    end
    RewardManager:getQueueReward(function(data, role)
        self:sendGameSettlement(role)
    end, role)
end

function RewardUtil:doReport()
    local players = self:sortPlayerRank()
    for rank, player in pairs(players) do
        if player.isReport == false then
            ReportManager:reportUserData(player.userId, player.kills, rank, 1)
            player.isReport = true
        end
    end
end

function RewardUtil:sendGameSettlement(winner)
    local Players = self:sortPlayerRank()

    local players = {}

    for rank, player in pairs(Players) do
        players[rank] = self:newSettlementItem(player, rank, winner)
        if player.isAddMoney == false then
            player:addMoney(player.gold)
            player.isAddMoney = true
        end
    end

    for rank, player in pairs(Players) do
        local result = {}
        result.players = players
        result.own = self:newSettlementItem(player, rank, winner)
        HostApi.sendGameSettlement(player.rakssid, json.encode(result), false)
        UserExpManager:addUserExp(player.userId, role == player.role, 2)
    end
end

function RewardUtil:newSettlementItem(player, rank, winner)
    local item = {}
    item.name = player.name
    item.rank = rank
    item.points = player.scorePoints
    item.gold = player.gold
    item.available = player.available
    item.hasGet = player.hasGet
    item.vip = player.vip
    item.kills = player.kills
    item.adSwitch = player.adSwitch or 0
    if item.gold <= 0 then --or player.isSingleReward then
        item.adSwitch = 0
    end
    if player.role == winner then
        item.isWin = 1
    else
        item.isWin = 0
    end
    return item
end

function RewardUtil:getPlayerRank(player)
    local players = self:sortPlayerRankOnRunning()
    return RankManager:getPlayerRank(players, player)
end

return RewardUtil