---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2018/11/16 0016 12:08
---
BackHallManager = {}
BackHallManager.players = {}

function BackHallManager:addPlayer(player)
    EngineUtil.sendEnterOtherGame(player.rakssid, "g1032", player.userId)
    self.players[tostring(player.userId)] = { rakssid = player.rakssid, time = os.time() }
    MsgSender.sendTopTipsToTarget(player.rakssid, 3600, Messages:msgWaitMatching())
end

function BackHallManager:onTick()
    self:checkPlayers()
    self:tryPlayerMatching()
end

function BackHallManager:checkPlayers()
    for userId, player in pairs(self.players) do
        if PlayerManager:getPlayerByRakssid(player.rakssid) == nil then
            self.players[userId] = nil
        end
    end
end

function BackHallManager:tryPlayerMatching()
    for userId, player in pairs(self.players) do
        if os.time() - player.time > 10 then
            player.time = os.time()
            local c_player = PlayerManager:getPlayerByRakssid(player.rakssid)
            if c_player ~= nil then
                EngineUtil.sendEnterOtherGame(c_player.rakssid, "g1032", c_player.userId)
            end
        end
    end
end

return BackHallManager