---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/6/8 10:28
---

function CustomShopCommand:onEquipGoods(player, goods)
    local command = self.Settings[goods.SettingId]
    if not command then
        return
    end

    ---同步给客户端
end