---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/6/4 21:29
---
function CustomShopPet:onEquipGoods(player, goods)
    local setting = self.Settings[goods.SettingId]
    if not setting then
        return
    end
    player.info:setValue("petId", setting.Id)
end

function CustomShopPet:onUnloadGoods(player, goods)
    local setting = self.Settings[goods.SettingId]
    if not setting then
        return
    end
    player.info:setValue("petId", "0")
end