---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/1/8 17:55
---

ExtraAwardConfig = {}
ExtraAwardConfig.firstAward = {}
ExtraAwardConfig.randomMapAward = {}
ExtraAwardConfig.vipAward = {}
ExtraAwardConfig.First = 1
ExtraAwardConfig.RandomMap = 2
ExtraAwardConfig.Vip = 3

function ExtraAwardConfig:init(config)
    self:initExtraAward(config)
end

function ExtraAwardConfig:initExtraAward(config)
    for id, extra in pairs(config) do
        local item = {}
        item.id = id
        item.type = tonumber(extra.type)
        item.name = extra.name
        item.num = tonumber(extra.num) or 1
        if item.type == self.First then
            self.firstAward[item.name] = item
        elseif item.type == self.RandomMap then
            self.randomMapAward[item.name] = item
        elseif item.type == self.Vip then
            self.vipAward[item.name] = item
        end
    end
end

function ExtraAwardConfig:getFirstAward(name)
    local award = self.firstAward[name]
    if award ~= nil then
        return award.num
    end
    return 1
end

function ExtraAwardConfig:getRandomMapAward(name)
    local award = self.randomMapAward[name]
    if award ~= nil then
        return award.num
    end
    return 1
end

function ExtraAwardConfig:getVipAward(name)
    local award = self.vipAward[name]
    if award ~= nil then
        return award.num
    end
    return 1
end

return ExtraAwardConfig
