---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/7/8 17:29
---

require "data.WeaponSupply"

WeaponSupplyConfig = {}
WeaponSupplyConfig.Areas = {}
WeaponSupplyConfig.Positions = {}
WeaponSupplyConfig.Qualitys = {}
WeaponSupplyConfig.Pool = {}
WeaponSupplyConfig.RandomTimes = 1

function WeaponSupplyConfig:initArea(config)
    for _, area in pairs(config) do
        local item = {}
        item.id = tonumber(area.id)
        item.totalNum = StringUtil.split(area.totalNum, "#")
        item.epicNum = StringUtil.split(area.epicNum, "#")
        item.legendNum = StringUtil.split(area.legendNum, "#")
        item.rifleLimit = {
            tonumber(area.rifleMin) or 0,
            tonumber(area.rifleMax) or 0
        }
        item.pistolLimit = {
            tonumber(area.pistolMin) or 0,
            tonumber(area.pistolMax) or 0
        }
        item.snipeLimit = {
            tonumber(area.snipeMin) or 0,
            tonumber(area.snipeMax) or 0
        }
        item.bazookaLimit = {
            tonumber(area.bazookaMin) or 0,
            tonumber(area.bazookaMax) or 0
        }
        item.positions = {}
        self.Areas[item.id] = item
    end
end

function WeaponSupplyConfig:initPosition(config)
    local data = {}
    for id, position in pairs(config) do
        local item = {}
        item.id = tonumber(position.id)
        item.pos = VectorUtil.newVector3(position.x, position.y, position.z)
        table.insert(self.Areas[tonumber(position.areaId)].positions, item)
        if data[tonumber(position.areaId)] == nil then
            data[tonumber(position.areaId)] = {}
        end
        if self.Pool[tonumber(position.areaId)] == nil then
            self.Pool[tonumber(position.areaId)] = {}
        end
        table.insert(data[tonumber(position.areaId)], #data[tonumber(position.areaId)] + 1)
        table.insert(self.Pool[tonumber(position.areaId)], item)
    end
    self:setRandomSeed(data)
    self:randomSupply(1)
end

function WeaponSupplyConfig:setRandomSeed(data)
    for _, area in pairs(self.Areas) do
        RandomUtil:setRandomSeed()
        RandomUtil:initRandomSeed("weapon_supply" .. area.id, data[area.id])
    end
end

function WeaponSupplyConfig:initQuality(config)
    for _, quality in pairs(config) do
        local item = {}
        item.id = tonumber(quality.id)
        item.effect = quality.effect
        item.image = quality.image
        self.Qualitys[quality.id] = item
    end
end

function WeaponSupplyConfig:randomSupply(times)
    self.RandomTimes = times or 1
    for id, area in pairs(self.Areas) do
        local guns = self:randomGun(area)
        self:randomPositions(area, guns)
        self:removeBlock(area.positions)
    end
end

function WeaponSupplyConfig:getRandomTimes()
    return self.RandomTimes
end

function WeaponSupplyConfig:removeBlock(positions)
    for _, position in pairs(positions) do
        local pos = VectorUtil.newVector3i(position.pos.x, position.pos.y, position.pos.z)
        EngineWorld:getWorld():destroyBlock(pos, false)
    end
end

function WeaponSupplyConfig:randomGun(area)
    local result = {}
    local quality = {}
    quality[GunConfig.Quality.Epic] = tonumber(area.epicNum[self.RandomTimes])
    quality[GunConfig.Quality.Legend] = tonumber(area.legendNum[self.RandomTimes])
    quality[GunConfig.Quality.Surplus] = tonumber(area.totalNum[self.RandomTimes])
            - tonumber(area.epicNum[self.RandomTimes])
            - tonumber(area.legendNum[self.RandomTimes])

    local gunNum = self:randomGunType(area)
    local gun = {}
    local function random(num, type)
        for i = 1, num do
            gun = GunConfig:getRandomGun(type)
            while(gun == nil or (self:checkQualityNum(quality, gun.quality))) do
                gun = GunConfig:getRandomGun(type)
            end
            quality = self:subQualityNum(quality, gun.quality)
            table.insert(result, gun.itemId)
        end
    end

    for type, num in pairs(gunNum) do
        random(num, tonumber(type))
    end
    return result
end

function WeaponSupplyConfig:randomPositions(area, guns)
    --if area.totalNum[self.RandomTimes] == 0 then
    --    return
    --end
    local num = tonumber(area.totalNum[self.RandomTimes] or 1)
    if next(self.Pool[area.id]) == nil then
        return
    end

    local tableNum = #(self.Pool[area.id])
    if tableNum < num then
        num = tableNum
    end

    local supply = {}
    local posId = 0
    for i = 1, num do
        posId = RandomUtil:get("weapon_supply" .. area.id)
        local pos = self.Pool[area.id][posId]
        while pos == nil do
            posId = RandomUtil:get("weapon_supply" .. area.id)
            pos = self.Pool[area.id][posId]
        end
        supply = WeaponSupply.new(pos, guns[i], 1000)
        table.insert(self.Positions, supply)
        table.remove(self.Pool[area.id], posId)
    end
end

function WeaponSupplyConfig:getTableLength(Table)
    local table_item = Table
    local index = 0
    for k, v in pairs(table_item) do
        index = index + 1
    end
    return index
end

function WeaponSupplyConfig:getSumOfWeight(items)
    local sumOfWeight = 0
    for _, item in pairs(items) do
        sumOfWeight = sumOfWeight + item.weight
    end
    return sumOfWeight
end

function WeaponSupplyConfig:checkQualityNum(quality, gunQuality)
    if quality[gunQuality] == nil then
        return quality[GunConfig.Quality.Surplus] == 0
    end

    return quality[gunQuality] == 0
end

function WeaponSupplyConfig:subQualityNum(quality, gunQuality)
    if quality[gunQuality] == nil then
        quality[GunConfig.Quality.Surplus] = quality[GunConfig.Quality.Surplus] - 1
        return quality
    end
    quality[gunQuality] = quality[gunQuality] - 1
    return quality
end

function WeaponSupplyConfig:randomGunType(area)
    local gunNum = {}
    gunNum[GunConfig.Type.Rifle] = 0
    gunNum[GunConfig.Type.Pistol] = 0
    gunNum[GunConfig.Type.Snipe] = 0
    gunNum[GunConfig.Type.Bazooka] = 0

    math.randomseed(os.clock() * 1000000)
    local rifle = math.random(area.rifleLimit[1], area.rifleLimit[2])
    local pistol = math.random(area.pistolLimit[1], area.pistolLimit[2])
    local snipe = math.random(area.snipeLimit[1], area.snipeLimit[2])
    local bazooka = math.random(area.bazookaLimit[1], area.bazookaLimit[2])
    local total = rifle + pistol + snipe + bazooka
    while total ~= tonumber(area.totalNum[self.RandomTimes]) do
        math.randomseed(os.clock() * 1000000)
        rifle = math.random(area.rifleLimit[1], area.rifleLimit[2])
        pistol = math.random(area.pistolLimit[1], area.pistolLimit[2])
        snipe = math.random(area.snipeLimit[1], area.snipeLimit[2])
        bazooka = math.random(area.bazookaLimit[1], area.bazookaLimit[2])
        total = rifle + pistol + snipe + bazooka
    end
    gunNum[GunConfig.Type.Rifle] = rifle
    gunNum[GunConfig.Type.Pistol] = pistol
    gunNum[GunConfig.Type.Snipe] = snipe
    gunNum[GunConfig.Type.Bazooka] = bazooka
    return gunNum
end

function WeaponSupplyConfig:getEffectByQuality(quality)
    return self.Qualitys[tostring(quality)].effect or ""
end

function WeaponSupplyConfig:getImageByQuality(quality)
    return self.Qualitys[tostring(quality)].image or ""
end
